// ============================================================
// SwingVantage — Tennis Drill Library
// Drills mapped to visual swing issues and phases.
// All YouTube links are SEARCH LINKS only — never hardcoded video IDs.
// ============================================================

import type { SportDrillRecommendation } from '../types';

function ytSearch(query: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
}

export const TENNIS_DRILLS: SportDrillRecommendation[] = [
  // ── Late Contact ─────────────────────────────────────────────
  {
    id: 'tennis_feed_out_front',
    sport_id: 'tennis',
    issue_id: 'late_contact',
    phase: 'contact_zone',
    name: 'Toss-and-Hit Contact Point Drill',
    goal: 'Train consistent forward contact point in front of the hip',
    steps: [
      'Stand at baseline with no racket — just your non-dominant hand holding a ball',
      'Toss the ball to exactly the spot you want to contact it (in front and out)',
      'Then add the racket — toss and hit, focusing on reaching forward',
      'Place a cone at your ideal contact point; hit over the cone',
      'Progress: have a partner feed balls to that spot',
    ],
    reps_or_duration: '3 sets of 20 feeds, focus on contact position',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls, cone',
    safety_note: null,
    youtube_search_query: 'tennis forehand contact point drill forward',
    youtube_search_url: ytSearch('tennis forehand contact point drill forward'),
    coach_channel_hint: 'Essential Tennis, Top Tennis Training',
    focus_feel: 'Feel your arm fully extending to reach for the ball out in front of you.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Wrist Rollover ───────────────────────────────────────────
  {
    id: 'tennis_windshield_wiper',
    sport_id: 'tennis',
    issue_id: 'wrist_rollover',
    phase: 'contact_zone',
    name: 'Windshield Wiper Follow-Through Drill',
    goal: 'Teach low-to-high brushing contact without premature rollover',
    steps: [
      'Drop-feed balls at hip height from inside the baseline',
      'Focus on brushing up the back of the ball — 6 o\'clock to 12 o\'clock',
      'Racket face stays perpendicular at contact — no rollover until well after contact',
      'Feel the windshield-wiper motion as racket goes from low to high',
      'Practice in slow motion first, then at match pace',
    ],
    reps_or_duration: '3 sets of 15, slow then full speed',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls',
    safety_note: null,
    youtube_search_query: 'tennis topspin windshield wiper drill forehand',
    youtube_search_url: ytSearch('tennis topspin windshield wiper drill forehand'),
    coach_channel_hint: 'Jeff Salzenstein, Intuitive Tennis',
    focus_feel: 'Brush up the back of the ball — feel the strings grip and spin it forward.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Bent Arm at Contact ───────────────────────────────────────
  {
    id: 'tennis_extension_shadow',
    sport_id: 'tennis',
    issue_id: 'bent_arm_contact',
    phase: 'contact_zone',
    name: 'Shadow Swing Extension Drill',
    goal: 'Develop arm extension through the contact zone',
    steps: [
      'Stand in front of a full-length mirror or glass',
      'Shadow-swing in slow motion — pause at contact',
      'Check that hitting arm is at about 80% extension at contact (not fully locked)',
      'Feel the reach — arm should be visibly longer than at address',
      'Add a wall touch: place hand on wall at correct contact point, feel the reach',
    ],
    reps_or_duration: '3 minutes of shadow swings, 10 wall touches',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket (no ball needed), mirror or wall',
    safety_note: 'Do not lock elbow at contact — slight bend is normal and healthy.',
    youtube_search_query: 'tennis forehand arm extension drill reach',
    youtube_search_url: ytSearch('tennis forehand arm extension drill reach'),
    coach_channel_hint: 'Essential Tennis',
    focus_feel: 'Reach out and shake hands — your arm should feel long and extended.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Head Pull ─────────────────────────────────────────────────
  {
    id: 'tennis_head_still_drill',
    sport_id: 'tennis',
    issue_id: 'head_pull_tennis',
    phase: 'contact_zone',
    name: 'Head Down — Eyes on Contact Drill',
    goal: 'Keep head still through contact to improve strike consistency',
    steps: [
      'Drop-feed balls at a comfortable height',
      'Hit each ball while consciously keeping your chin down',
      'After contact, hold the head-down position for a 1-second count',
      'Only look up after that count — you should "see" where the ball went in your peripheral',
      'Progression: have a partner call the direction after you hit (you cannot look)',
    ],
    reps_or_duration: '4 sets of 10 feeds',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls',
    safety_note: null,
    youtube_search_query: 'tennis keep head down contact drill eyes on ball',
    youtube_search_url: ytSearch('tennis keep head down contact drill eyes on ball'),
    coach_channel_hint: 'Top Tennis Training',
    focus_feel: 'See the strings hit the ball. Hold your head still for a full second after.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Short Follow-Through ──────────────────────────────────────
  {
    id: 'tennis_full_finish_drill',
    sport_id: 'tennis',
    issue_id: 'follow_through_short',
    phase: 'follow_through',
    name: 'Full Finish Pose Drill',
    goal: 'Reinforce complete follow-through to proper finish position',
    steps: [
      'Hit a ball, then hold your finish position for 3 full seconds',
      'Racket should finish by your non-dominant shoulder or wrapped around body',
      'Have a training partner check your finish — take a photo',
      'If you can\'t hold the finish, you decelerated before contact',
      'Progression: Rally and call out "finish!" every rep you complete properly',
    ],
    reps_or_duration: '3 sets of 15 — hold each finish for 3 seconds',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls, optional camera',
    safety_note: null,
    youtube_search_query: 'tennis follow through finish drill topspin',
    youtube_search_url: ytSearch('tennis follow through finish drill topspin'),
    coach_channel_hint: 'Intuitive Tennis',
    focus_feel: 'Finish feels like you\'re catching your racket over your shoulder.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Unit Turn / Late Preparation ─────────────────────────────
  {
    id: 'tennis_unit_turn_shadow',
    sport_id: 'tennis',
    issue_id: null,
    phase: 'unit_turn',
    name: 'Unit Turn Shadow Drill',
    goal: 'Build automatic shoulder-hip unit turn as first movement',
    steps: [
      'Stand in ready position at the baseline',
      'Have a partner point left or right randomly',
      'On their signal, complete a full unit turn in that direction — no racket swing',
      'Focus: shoulders and hips move together, non-dominant hand guides',
      'Add a crossover step after the turn to simulate moving to the ball',
    ],
    reps_or_duration: '3 sets of 20 random signals',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket',
    safety_note: null,
    youtube_search_query: 'tennis unit turn drill preparation split step',
    youtube_search_url: ytSearch('tennis unit turn drill preparation split step'),
    coach_channel_hint: 'Essential Tennis',
    focus_feel: 'Your chest should feel like it turns toward the back fence instantly.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Open Hips Early ───────────────────────────────────────────
  {
    id: 'tennis_closed_stance_rally',
    sport_id: 'tennis',
    issue_id: 'open_hips_early',
    phase: 'loading',
    name: 'Closed Stance Baseline Rally',
    goal: 'Teach hip coil before hip release — building topspin torque',
    steps: [
      'Use a closed or semi-open stance for every forehand in the rally',
      'Front foot must be parallel or slightly angled closed at loading',
      'Hips stay closed until front foot pushes — then hips fire',
      'Feel the hip coil and delay before explosion',
      'Compare power to your normal open-stance shots',
    ],
    reps_or_duration: '20 minutes closed-stance forehand rally',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Racket, court, partner',
    safety_note: null,
    youtube_search_query: 'tennis hip coil closed stance forehand drill',
    youtube_search_url: ytSearch('tennis hip coil closed stance forehand drill'),
    coach_channel_hint: 'Jeff Salzenstein',
    focus_feel: 'Feel your hips trying to stay closed as long as possible before unleashing.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Loop Timing ───────────────────────────────────────────────
  {
    id: 'tennis_loop_timing_rally',
    sport_id: 'tennis',
    issue_id: 'loop_timing_off',
    phase: 'backswing',
    name: 'Rhythmic Loop Timing Drill',
    goal: 'Build consistent racket loop that arrives at contact without rushing',
    steps: [
      'Stand at the service line and have a partner soft-feed balls',
      'Start your loop as soon as the ball bounces on the other side',
      'Do not rush — the loop should arrive at the loading position by the time the ball reaches you',
      'Count "bounce-loop-hit" rhythmically as you drill',
      'Increase ball pace progressively when timing feels solid',
    ],
    reps_or_duration: '3 sets of 20 feeds, call out "bounce-loop-hit"',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Racket, balls, partner or ball machine',
    safety_note: null,
    youtube_search_query: 'tennis forehand loop timing drill bounce hit rhythm',
    youtube_search_url: ytSearch('tennis forehand loop timing drill bounce hit rhythm'),
    coach_channel_hint: 'Top Tennis Training',
    focus_feel: 'Feel the loop falling naturally into place — never rushed, always ready.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Split Step ───────────────────────────────────────────
  {
    id: 'tennis_split_step_ladder',
    sport_id: 'tennis',
    issue_id: 'poor_split_step',
    phase: 'ready_position',
    name: 'Agility Ladder Split-Step Drill',
    goal: 'Automate the split step as an instant reaction to opponent contact',
    steps: [
      'Set up an agility ladder and stand at one end in ready position',
      'Have a partner call "now!" simulating opponent contact',
      'On the call, perform a split step — both feet leave the ground simultaneously',
      'Immediately push off in the direction they point after calling',
      'Progress: use a ball toss instead of a verbal cue',
    ],
    reps_or_duration: '3 sets of 20 reaction reps',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Agility ladder, partner',
    safety_note: null,
    youtube_search_query: 'tennis split step drill reaction footwork agility',
    youtube_search_url: ytSearch('tennis split step drill reaction footwork agility'),
    coach_channel_hint: 'Top Tennis Training, Essential Tennis',
    focus_feel: 'Land softly on both feet at the exact moment the opponent hits — spring-loaded.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Weak Unit Turn ────────────────────────────────────────────
  {
    id: 'tennis_unit_turn_wall',
    sport_id: 'tennis',
    issue_id: 'weak_unit_turn',
    phase: 'unit_turn',
    name: 'Wall Shoulder Turn Check Drill',
    goal: 'Confirm full shoulder coil is achieved on every preparation',
    steps: [
      'Stand facing a wall, 3 feet away, racket in hand',
      'Practice unit turn — your off-shoulder should almost touch the wall when fully turned',
      'If shoulder does not reach within 6 inches, turn is insufficient',
      'Add a spoken cue: "shoulder to the fence" on every turn',
      'Progress to shadow swings with the full turn habit ingrained',
    ],
    reps_or_duration: '3 sets of 20 shadow turns',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, wall',
    safety_note: null,
    youtube_search_query: 'tennis unit turn shoulder rotation drill preparation',
    youtube_search_url: ytSearch('tennis unit turn shoulder rotation drill preparation'),
    coach_channel_hint: 'Intuitive Tennis',
    focus_feel: 'Your off-shoulder drives toward the back fence — chest turns away from the net.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Loading ──────────────────────────────────────────────
  {
    id: 'tennis_weight_load_cone',
    sport_id: 'tennis',
    issue_id: 'poor_loading',
    phase: 'loading',
    name: 'Back Leg Load Cone Drill',
    goal: 'Build the habit of loading weight onto the back leg before swinging',
    steps: [
      'Place a cone behind your back foot at address',
      'On every swing, feel your weight shift back — back calf should press toward the cone',
      'The load should happen before any forward movement begins',
      'Check that front heel is light during load — weight is clearly back',
      'Progress: drop-feed and feel load before every swing',
    ],
    reps_or_duration: '3 sets of 15 feed-and-load swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls, cone',
    safety_note: null,
    youtube_search_query: 'tennis weight transfer loading back leg drill forehand',
    youtube_search_url: ytSearch('tennis weight transfer loading back leg drill forehand'),
    coach_channel_hint: 'Jeff Salzenstein',
    focus_feel: 'Back leg presses into the ground — you coil before you uncoil.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Off Balance Contact ───────────────────────────────────────
  {
    id: 'tennis_balance_beam_swing',
    sport_id: 'tennis',
    issue_id: 'off_balance_contact',
    phase: 'contact_zone',
    name: 'Balance Beam Shadow Swing',
    goal: 'Develop balance control through the entire swing arc',
    steps: [
      'Place a piece of tape on the ground as your "balance beam" foot line',
      'Shadow swing — both feet must stay on or very near the tape during the entire swing',
      'If you wobble or step off, start again — no swings until foot control is locked in',
      'Progress: add a drop-feed and hit while keeping feet controlled',
      'Advanced: hit while standing on a balance pad',
    ],
    reps_or_duration: '3 sets of 15 shadow swings, then 15 feed-and-hit',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, tape, optional balance pad',
    safety_note: null,
    youtube_search_query: 'tennis balance drill footwork control hitting',
    youtube_search_url: ytSearch('tennis balance drill footwork control hitting'),
    coach_channel_hint: 'Intuitive Tennis',
    focus_feel: 'Your weight stays centered — you hit out of stillness, not out of falling.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Excessive Wrist ───────────────────────────────────────────
  {
    id: 'tennis_wrist_tape_drill',
    sport_id: 'tennis',
    issue_id: 'excessive_wrist',
    phase: 'contact_zone',
    name: 'Wrist Stability Tape Constraint Drill',
    goal: 'Reduce excessive wrist flip and build passive-wrist contact',
    steps: [
      'Apply athletic tape around the wrist and back of the hand — loosely, not tight',
      'The tape provides proprioceptive feedback when wrist bends excessively',
      'Hit drop-feed balls at half-speed — focus on maintaining wrist angle through contact',
      'Racket face should not roll over until well after contact',
      'Remove tape and replicate the feeling at full speed',
    ],
    reps_or_duration: '3 sets of 15 drop-feed hits with tape on',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Racket, balls, athletic tape',
    safety_note: 'Tape should be loose — feedback only, not restrictive.',
    youtube_search_query: 'tennis wrist control drill stable contact topspin',
    youtube_search_url: ytSearch('tennis wrist control drill stable contact topspin'),
    coach_channel_hint: 'Top Tennis Training',
    focus_feel: 'Wrist stays quiet through contact — let the swing arc create spin, not the wrist.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Extension ────────────────────────────────────────────
  {
    id: 'tennis_target_reach_drill',
    sport_id: 'tennis',
    issue_id: 'poor_extension',
    phase: 'contact_zone',
    name: 'Target Reach Extension Drill',
    goal: 'Train full arm extension through contact toward the target',
    steps: [
      'Place a cone or target 18 inches past your normal contact point',
      'After hitting each ball, your racket must "reach" toward that target',
      'Hold the reach position for a 2-second count — arm extended, racket pointing at target',
      'Start at 60% swing speed, progress to 90%',
      'Partner checks: arm visibly extends toward target after each contact',
    ],
    reps_or_duration: '3 sets of 15 reach-and-hold reps',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls, cone',
    safety_note: null,
    youtube_search_query: 'tennis forehand extension through contact reach drill',
    youtube_search_url: ytSearch('tennis forehand extension through contact reach drill'),
    coach_channel_hint: 'Essential Tennis',
    focus_feel: 'Arm feels like it is shaking hands with someone past the contact point.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Recovery ─────────────────────────────────────────────
  {
    id: 'tennis_recover_cone_drill',
    sport_id: 'tennis',
    issue_id: 'poor_recovery',
    phase: 'follow_through',
    name: 'Hit and Recover Cone Drill',
    goal: 'Build automatic split-step and recovery movement after each shot',
    steps: [
      'Place a center mark cone behind the baseline at the center of the court',
      'Hit a shot, then immediately push off and sprint back to touch the cone',
      'Partner feeds the next ball just as you touch the cone',
      'You must reach the cone between every shot — no resting in follow-through',
      'Progress: reduce time between shots as recovery becomes automatic',
    ],
    reps_or_duration: '3 sets of 10 shots with full cone recovery',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Racket, balls, cone, partner',
    safety_note: null,
    youtube_search_query: 'tennis recovery footwork drill between shots center',
    youtube_search_url: ytSearch('tennis recovery footwork drill between shots center'),
    coach_channel_hint: 'Top Tennis Training',
    focus_feel: 'The shot is done — the next point starts now. Move!',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Footwork ─────────────────────────────────────────────
  {
    id: 'tennis_crossover_shuffle_drill',
    sport_id: 'tennis',
    issue_id: 'poor_footwork',
    phase: 'ready_position',
    name: 'Crossover and Shuffle Approach Drill',
    goal: 'Build efficient footwork patterns for approaching the ball',
    steps: [
      'Have a partner feed balls alternating wide left and wide right',
      'Use a crossover first step for balls beyond 2 steps away',
      'Use shuffle steps for balls within 1-2 steps',
      'Focus: first step is always toward the ball, not a hesitation step',
      'Progression: partner varies speed and direction of feeds',
    ],
    reps_or_duration: '3 sets of 20 alternating feeds',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls, partner',
    safety_note: null,
    youtube_search_query: 'tennis footwork crossover shuffle drill baseline movement',
    youtube_search_url: ytSearch('tennis footwork crossover shuffle drill baseline movement'),
    coach_channel_hint: 'Essential Tennis',
    focus_feel: 'First step explodes toward the ball — decisive, no hesitation.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Falling Away ─────────────────────────────────────────────
  {
    id: 'tennis_into_the_ball_drill',
    sport_id: 'tennis',
    issue_id: 'falling_away',
    phase: 'contact_zone',
    name: 'Drive Into the Ball Constraint Drill',
    goal: 'Stop body from falling away — train weight moving into the contact',
    steps: [
      'Place a flat marker 12 inches in front of your hitting-side foot at address',
      'On each swing, front foot must step forward onto or past the marker',
      'If you step back or sideways, that rep does not count',
      'Feel weight moving forward through contact, not backward',
      'Partner observes: is torso tilting forward or away?',
    ],
    reps_or_duration: '3 sets of 15 marker-step swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls, flat marker',
    safety_note: null,
    youtube_search_query: 'tennis drive through ball drill weight forward contact',
    youtube_search_url: ytSearch('tennis drive through ball drill weight forward contact'),
    coach_channel_hint: 'Intuitive Tennis',
    focus_feel: 'Body weight moves into the ball — lean in, drive forward.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Serve Toss Inconsistency ──────────────────────────────────
  {
    id: 'tennis_toss_wall_drill',
    sport_id: 'tennis',
    issue_id: 'serve_toss_inconsistency',
    phase: 'unit_turn',
    name: 'Serve Toss Wall Target Drill',
    goal: 'Build a repeatable, consistent ball toss for serving',
    steps: [
      'Stand near a wall and hold a racket across the wall at the height of your ideal toss',
      'Practice tossing the ball and having it hit the racket consistently',
      'Toss arm should rise straight up — no sideways or backward movement',
      'Toss 50 balls in a row, aiming for the same spot each time',
      'Progress: toss in serve motion without actually serving — just the toss',
    ],
    reps_or_duration: '50 consecutive toss reps daily for one week',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, balls, wall',
    safety_note: null,
    youtube_search_query: 'tennis serve toss consistency drill wall target',
    youtube_search_url: ytSearch('tennis serve toss consistency drill wall target'),
    coach_channel_hint: 'Jeff Salzenstein, Essential Tennis',
    focus_feel: 'The toss arm goes straight up like an elevator — no spin, no curve.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Serve Trophy Breakdown ────────────────────────────────────
  {
    id: 'tennis_trophy_mirror_drill',
    sport_id: 'tennis',
    issue_id: 'serve_trophy_breakdown',
    phase: 'loading',
    name: 'Trophy Position Mirror Drill',
    goal: 'Groove the trophy position before every serve motion',
    steps: [
      'Stand in front of a mirror or glass wall',
      'Slowly move into the trophy position: both arms raised, hitting elbow at shoulder height',
      'Hold the position for 3 seconds — check elbow height, toss arm direction, knee bend',
      'Repeat 20 times without actually serving — muscle memory only',
      'Add the swing when the position feels natural and consistent',
    ],
    reps_or_duration: '3 sets of 20 trophy position holds',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, mirror or glass wall',
    safety_note: null,
    youtube_search_query: 'tennis serve trophy position drill mirror technique',
    youtube_search_url: ytSearch('tennis serve trophy position drill mirror technique'),
    coach_channel_hint: 'Intuitive Tennis, Essential Tennis',
    focus_feel: 'Both arms rise together — like you are lifting a trophy above your head.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Late Preparation ──────────────────────────────────────────
  {
    id: 'tennis_early_prep_rally',
    sport_id: 'tennis',
    issue_id: 'late_preparation',
    phase: 'unit_turn',
    name: 'Early Preparation Bounce-Call Drill',
    goal: 'Force early racquet preparation triggered by opponent contact, not bounce',
    steps: [
      'During a rally, call "turn!" the instant the opponent\'s racquet contacts the ball',
      'By the time the ball bounces on your side, racquet must already be in loading position',
      'Practice recognizing the opponent\'s contact cue — not the ball trajectory',
      'Video yourself: racquet should be back at loading by ball\'s peak',
      'Progression: reduce verbal cues until preparation becomes automatic',
    ],
    reps_or_duration: '20-minute rally session focused on early prep',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Racket, balls, partner',
    safety_note: null,
    youtube_search_query: 'tennis early preparation drill trigger contact cue',
    youtube_search_url: ytSearch('tennis early preparation drill trigger contact cue'),
    coach_channel_hint: 'Top Tennis Training',
    focus_feel: 'Read the opponent\'s contact — be turned and loaded before the ball bounces.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Inconsistent Swing Plane ──────────────────────────────────
  {
    id: 'tennis_plane_gate_drill',
    sport_id: 'tennis',
    issue_id: 'inconsistent_swing_plane',
    phase: 'backswing',
    name: 'Swing Plane Gate Drill',
    goal: 'Build a repeatable low-to-high swing plane on every groundstroke',
    steps: [
      'Set two cones at low-to-high angles along your swing path',
      'Shadow swing — racket must pass through the "gate" formed by the two cones',
      'Adjust cone spacing until you can pass through consistently',
      'Add drop-feed balls — same gate constraint applies',
      'Video check: swing plane should look the same from rep to rep',
    ],
    reps_or_duration: '3 sets of 20 gate swings',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Racket, balls, two cones',
    safety_note: null,
    youtube_search_query: 'tennis swing plane drill consistent low to high forehand',
    youtube_search_url: ytSearch('tennis swing plane drill consistent low to high forehand'),
    coach_channel_hint: 'Jeff Salzenstein',
    focus_feel: 'Same path, same angle, same result — repeatability is the goal.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Racquet Path ─────────────────────────────────────────
  {
    id: 'tennis_racquet_path_shadow',
    sport_id: 'tennis',
    issue_id: 'poor_racquet_path',
    phase: 'backswing',
    name: 'Racquet Path Shadow Drilling',
    goal: 'Ingrain a consistent racquet loop from backswing to follow-through',
    steps: [
      'Stand in front of a camera on tripod or have a partner record from the side',
      'Shadow swing 20 times — no ball',
      'Watch the recording: does the racquet follow the same arc every time?',
      'Identify where variability occurs and slow the motion at that point',
      'Rebuild the loop slowly, then accelerate when the path is consistent',
    ],
    reps_or_duration: '3 sets of 20 shadow swings with video review',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Racket, phone camera or partner',
    safety_note: null,
    youtube_search_query: 'tennis racquet path loop drill forehand consistency shadow',
    youtube_search_url: ytSearch('tennis racquet path loop drill forehand consistency shadow'),
    coach_channel_hint: 'Essential Tennis',
    focus_feel: 'Same loop every time — feel the racquet follow a predictable track.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Over-Rotation ─────────────────────────────────────────────
  {
    id: 'tennis_front_leg_post_drill',
    sport_id: 'tennis',
    issue_id: 'over_rotation',
    phase: 'follow_through',
    name: 'Front Leg Post Drill',
    goal: 'Use the front leg as a post to stop over-rotation at the correct moment',
    steps: [
      'Set up at the baseline with a closed or semi-open stance',
      'After contact, consciously plant and stiffen the front leg — it becomes a post',
      'The rotation should stop as hips and shoulders reach the target line',
      'Hold that position for 2 seconds — body should be facing the net, not past it',
      'Adjust if hips spin past: the front leg post stops the chain at the right moment',
    ],
    reps_or_duration: '3 sets of 15 — hold the post for 2 seconds each',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Racket, balls',
    safety_note: null,
    youtube_search_query: 'tennis over rotation front leg post drill finish control',
    youtube_search_url: ytSearch('tennis over rotation front leg post drill finish control'),
    coach_channel_hint: 'Intuitive Tennis',
    focus_feel: 'Front leg plants firm — rotation ends there, not past it.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },
];

// ──────────────────────────────────────────────────────────────
// Lookup helpers
// ──────────────────────────────────────────────────────────────

export function getTennisDrillsForIssue(issueId: string): SportDrillRecommendation[] {
  return TENNIS_DRILLS.filter((d) => d.issue_id === issueId);
}

export function getTennisDrillsForPhase(phase: string): SportDrillRecommendation[] {
  return TENNIS_DRILLS.filter((d) => d.phase === phase);
}
