// ============================================================
// /admin/practice-plans/manage — Plan Template Editor
// ------------------------------------------------------------
// Practice plans are generated per athlete, so there is no static
// registry to edit. This seeds editable TEMPLATES from the REAL planner's
// representative outputs, then lets operators override/create/retire them
// as a LOCAL-FIRST overlay and export to commit globally. The browser
// never writes to live data. Mirrors the Drill Editor pattern.
// ============================================================

import type { Metadata } from 'next';
import { ClipboardList } from 'lucide-react';
import { PageHeader } from '@/components/admin/PageHeader';
import { HelpPanel } from '@/components/admin/HelpPanel';
import { buildSamplePlans } from '@/lib/admin/practice-plans/samples';
import type { BasePlanTemplate } from '@/lib/admin/plan-editor/merge';
import { PlanManager } from './PlanManager';

export const metadata: Metadata = { title: 'Plan Template Editor | Admin', robots: 'noindex, nofollow' };
export const dynamic = 'force-dynamic';

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export default function AdminPlanEditorPage() {
  const catalog = buildSamplePlans();
  const base: BasePlanTemplate[] = catalog.samples.map((s) => ({
    id: `${slug(s.sport)}-${slug(s.variant)}`,
    name: `${s.sportLabel} — ${s.variant}`,
    sport: s.sport,
    level: s.variant,
    focus: s.plan.practiceFocus,
    minutes: s.plan.estimatedTimeMinutes,
    warmup: s.plan.warmup,
    drills: s.plan.mainDrills.map((d) => ({ name: d.name, detail: `${d.repsOrTime} — ${d.why}` })),
    pressureTest: s.plan.pressureTest,
    successMetric: s.plan.successMetric,
  }));

  return (
    <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
      <PageHeader
        title="Plan Template Editor"
        icon={ClipboardList}
        description="Edit and create practice-plan templates. The starting templates are generated by the real planner; your edits are a preview overlay saved in this browser only. Export to commit them for everyone — nothing is written to live production data until a developer commits the exported JSON."
      />

      <PlanManager baseTemplates={base} />

      <HelpPanel>
        <p>
          <strong className="text-foreground">Why templates.</strong> Plans are personalized per athlete by the
          planner, so there is no fixed list to manage. These templates seed that system — a curated starting
          point per sport and level that you can shape. Editing here builds a <em>local overlay</em>; the
          planner logic still lives in <code>lib/agents/workflows/practice-planner.ts</code>.
        </p>
        <p>
          <strong className="text-foreground">Going global.</strong> Click <em>Export JSON</em> and commit the
          file (or hand it to a developer) to apply your templates for all users. Production data stays safe:
          no destructive writes ever happen from the browser.
        </p>
        <p>
          <strong className="text-foreground">Status &amp; safety.</strong> New and edited templates start as
          <em> draft</em>; mark them <em>active</em> when reviewed, or <em>retired</em> to phase one out.
          Deleting a custom template or resetting all edits asks for confirmation first.
        </p>
      </HelpPanel>
    </div>
  );
}
