import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/layout/Providers';
import { Analytics } from '@/components/analytics/Analytics';
// Vercel's first-party metrics — separate from the local Analytics component
// above (Plausible/GA4/PostHog). Both are cookieless and only beacon when
// deployed on Vercel with the feature enabled, so they no-op locally.
import { Analytics as VercelAnalytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { siteConfig } from '@/config/site';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'SwingVantage — AI Swing Performance Platform',
  description:
    'AI-powered swing analysis for golf, tennis, baseball, and softball. Upload a video or import launch monitor data to identify your top swing fault, get personalized drills, and track improvement.',
  keywords: [
    'swing analysis',
    'AI swing coach',
    'golf swing analysis',
    'tennis swing analysis',
    'baseball swing analysis',
    'softball swing analysis',
    'launch monitor',
    'swing improvement',
    'golf training',
  ],
  metadataBase: new URL(siteConfig.liveSiteUrl),
  // Google Search Console verification (meta-tag method). Set
  // NEXT_PUBLIC_GSC_VERIFICATION to the token from GSC's "HTML tag" option,
  // then submit /sitemap.xml. Omitted entirely when unset.
  verification: process.env.NEXT_PUBLIC_GSC_VERIFICATION
    ? { google: process.env.NEXT_PUBLIC_GSC_VERIFICATION }
    : undefined,
  openGraph: {
    title: 'SwingVantage — AI Swing Performance Platform',
    description:
      'Upload a swing video or import launch monitor data. Get a free AI diagnosis, personalized drills, and a practice plan — golf, tennis, baseball, and softball.',
    type: 'website',
    url: siteConfig.liveSiteUrl,
    siteName: 'SwingVantage',
    images: [{ url: '/og-default.png', width: 1200, height: 630, alt: 'SwingVantage — Free AI Swing Analysis' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SwingVantage — AI Swing Performance Platform',
    description:
      'Free AI swing analysis for golf, tennis, baseball, and softball. Upload a swing, get your top fault, drills, and a practice plan.',
    images: ['/og-default.png'],
  },
  // App icons + favicon (real PNGs in /public, generated by scripts/generate-brand-assets.mjs).
  icons: {
    icon: [
      { url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/apple-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  // PWA / installability hints
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    title: 'SwingVantage',
    statusBarStyle: 'black-translucent',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Pinch-zoom is intentionally left enabled (no `maximumScale` / `userScalable`):
  // disabling it fails WCAG 2.1 SC 1.4.4 (Resize Text) and 1.4.10 (Reflow) and
  // hurts low-vision users on phones. The companion rule in globals.css renders
  // form controls at ≥16px on small screens so allowing zoom does not trigger
  // iOS Safari's focus auto-zoom (the usual reason teams disable scaling).
  viewportFit: 'cover',
  themeColor: '#1a3a2a',
};

// Pre-paint theme bootstrap: applies the persisted curated theme to <html>
// before React hydrates so there is no flash of the default theme. Kept in
// sync with lib/theme/themes (theme ids) and ThemeApplicator.
const THEME_BOOTSTRAP = `(function(){try{var ids=['standard','dark-performance','coach-mode','heritage-club','field-court','arcade-practice','bird-print'];var dark={'dark-performance':1,'arcade-practice':1};var t='standard';var raw=localStorage.getItem('swingiq-store');if(raw){var s=JSON.parse(raw);var c=s&&s.state&&s.state.settings&&s.state.settings.colorTheme;if(ids.indexOf(c)!==-1){t=c;}}var el=document.documentElement;el.setAttribute('data-theme',t);if(dark[t]){el.classList.add('dark');}}catch(e){}})();`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning data-theme="standard">
      <head>
        {/* Trusted, developer-authored static constant (THEME_BOOTSTRAP) with no
            user input — not an XSS sink; safe to inline. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP }} />
      </head>
      <body className={`${inter.variable} font-sans antialiased bg-background min-h-screen`}>
        <Providers>{children}</Providers>
        <Analytics />
        <VercelAnalytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
