import type { Metadata, Viewport } from 'next';
import { Inter, Space_Grotesk } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/layout/Providers';
import { FoundingFathersCounterBanner } from '@/components/founding/FoundingFathersCounterBanner';
import { Analytics } from '@/components/analytics/Analytics';
// Vercel's first-party metrics — separate from the local Analytics component
// above (Plausible/GA4/PostHog). Both are cookieless and only beacon when
// deployed on Vercel with the feature enabled, so they no-op locally.
import { Analytics as VercelAnalytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { siteConfig, absoluteUrl } from '@/config/site';
import { ServiceWorkerRegistrar } from '@/components/pwa/ServiceWorkerRegistrar';

// Body font — used for nearly all text on every page, so it's the one font we
// keep preloaded on the critical path (preload defaults to true).
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
// Display face for the Dark Performance (B) brand — bold, technical headings.
// Exposed as a CSS variable and consumed via `--font-heading` per theme.
//
// Kept OFF the critical render path on purpose: it's a headings-only face used
// by just 2 of the 8 themes and always sits behind a `system-ui` fallback, yet
// next/font preloads by default — emitting a render-blocking <link rel=preload>
// on every page (even the 6 themes that never use it), which competes with the
// body font and regressed FCP/LCP (see docs/PERFORMANCE.md). `preload: false`
// drops that critical-path request; `display: 'swap'` (next/font's default,
// pinned here for clarity) still paints headings instantly in the fallback and
// swaps Space Grotesk in once it arrives — no invisible text, no layout shift.
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-space-grotesk',
  preload: false,
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'SwingVantage — AI Swing Performance Platform',
  description:
    'AI-powered swing analysis for golf, tennis, baseball, and softball. Upload a video or import launch monitor data to identify your top swing fault, get personalized drills, and track improvement.',
  // No `keywords` meta tag on purpose — Google ignores it and Bing can read a
  // stuffed list as a spam signal. See docs/SEO_CONTENT_PLAN.md.
  metadataBase: new URL(siteConfig.liveSiteUrl),
  // Google Search Console verification (meta-tag method). Set
  // NEXT_PUBLIC_GSC_VERIFICATION to the token from GSC's "HTML tag" option,
  // then submit /sitemap.xml. Omitted entirely when unset.
  verification: process.env.NEXT_PUBLIC_GSC_VERIFICATION
    ? { google: process.env.NEXT_PUBLIC_GSC_VERIFICATION }
    : undefined,
  openGraph: {
    title: 'SwingVantage — AI Swing Performance Platform',
    description:
      'Upload a swing video or import launch monitor data. Get a free AI diagnosis, personalized drills, and a practice plan — golf, tennis, pickleball, padel, baseball, and softball.',
    type: 'website',
    locale: 'en_US',
    url: siteConfig.liveSiteUrl,
    siteName: 'SwingVantage',
    // The link-preview card. `type` + `secureUrl` + explicit dimensions let
    // strict scrapers (WhatsApp, iMessage, Facebook) render the image eagerly
    // without a second fetch; the PNG itself is flattened opaque RGB (no alpha)
    // so transparency-averse clients don't blank it. See
    // scripts/generate-brand-assets.mjs for how the card is built.
    images: [
      {
        url: '/og-default.png',
        secureUrl: absoluteUrl('/og-default.png'),
        width: 1200,
        height: 630,
        type: 'image/png',
        alt: 'SwingVantage — Free AI Swing Analysis for golf, tennis, pickleball, padel, baseball, and softball',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SwingVantage — AI Swing Performance Platform',
    description:
      'Free AI swing analysis for golf, tennis, pickleball, padel, baseball, and softball. Upload a swing, get your top fault, drills, and a practice plan.',
    images: ['/og-default.png'],
  },
  // App icons + favicon (real PNGs in /public, generated by scripts/generate-brand-assets.mjs).
  icons: {
    icon: [
      { url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/apple-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  // PWA / installability hints
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    title: 'SwingVantage',
    statusBarStyle: 'black-translucent',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Pinch-zoom is intentionally left enabled (no `maximumScale` / `userScalable`):
  // disabling it fails WCAG 2.1 SC 1.4.4 (Resize Text) and 1.4.10 (Reflow) and
  // hurts low-vision users on phones. The companion rule in globals.css renders
  // form controls at ≥16px on small screens so allowing zoom does not trigger
  // iOS Safari's focus auto-zoom (the usual reason teams disable scaling).
  viewportFit: 'cover',
  // Dark Performance (B) base — near-black, matches the default theme so the
  // mobile browser chrome blends into the page instead of flashing green.
  themeColor: '#0B0F0C',
};

// Pre-paint theme bootstrap: applies the *resolved* curated theme to <html>
// before React hydrates so there is no flash of the wrong theme. Mirrors the
// Theme Lab resolution order used by ThemeApplicator: operator force
// (device-local override, then the build-env pin baked in below) wins, else the
// user's persisted preference, else the default. Kept in sync with
// lib/theme/themes (ids), lib/theme-lab/control (storage key) and ThemeApplicator.
const THEME_ENV_FORCE = process.env.NEXT_PUBLIC_THEME_LAB_FORCE || '';
const THEME_BOOTSTRAP = `(function(){try{var ids=['standard','dark-performance','coach-mode','heritage-club','field-court','arcade-practice','bird-print','christmas-swing-lab'];var dark={'dark-performance':1,'arcade-practice':1,'christmas-swing-lab':1};var t='dark-performance';var forced='';var fraw=localStorage.getItem('swingiq-theme-lab');if(fraw){var f=JSON.parse(fraw);if(f&&ids.indexOf(f.forcedThemeId)!==-1){forced=f.forcedThemeId;}}var envForce=${JSON.stringify(THEME_ENV_FORCE)};if(!forced&&ids.indexOf(envForce)!==-1){forced=envForce;}if(forced){t=forced;}else{var raw=localStorage.getItem('swingiq-store');if(raw){var s=JSON.parse(raw);var c=s&&s.state&&s.state.settings&&s.state.settings.colorTheme;if(ids.indexOf(c)!==-1){t=c;}}}var el=document.documentElement;el.setAttribute('data-theme',t);if(dark[t]){el.classList.add('dark');}else{el.classList.remove('dark');}}catch(e){}})();`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-theme="dark-performance"
      className={`dark ${inter.variable} ${spaceGrotesk.variable}`}
    >
      <head>
        {/* Trusted, developer-authored static constant (THEME_BOOTSTRAP) with no
            user input — not an XSS sink; safe to inline. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP }} />
      </head>
      <body className="font-sans antialiased bg-background min-h-screen">
        <Providers>
          {/* Global Founding Members counter — slim, normal-flow bar at the very
              top of every public/app page (self-hides on /admin + auth). */}
          <FoundingFathersCounterBanner />
          {children}
        </Providers>
        <Analytics />
        <VercelAnalytics />
        <SpeedInsights />
        <ServiceWorkerRegistrar />
      </body>
    </html>
  );
}
