// ============================================================
// SwingVantage Admin — SEO + blog publishing store (SERVER-ONLY)
// ------------------------------------------------------------
// SEO pages and blog posts live in TypeScript data files, so instead of
// rewriting source we keep a small committed OVERRIDES file per type:
//   • src/data/seo-publish-overrides.json   (slug → 'published' | 'draft')
//   • src/data/blog-publish-overrides.json
//
// The read path merges the override on top of each item's own status
// (seoPages.ts effectiveSeoStatus / blog-posts.ts effectiveBlogStatus), so a
// page can be pulled — or a draft pushed live — without editing the registry.
// We only store an override when it DIFFERS from the item's base status, so the
// file stays a minimal, readable git diff.
//
// Same honesty model as updates-store: writes are a local-dev git diff you push;
// production's read-only FS makes this view-only. NEVER import from a client.
// ============================================================

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { SEO_PAGES, effectiveSeoStatus } from '@/content/seoPages';
import { BLOG_POSTS, effectiveBlogStatus } from '@/data/blog-posts';
import { canWriteUpdates, type PublishRow } from './updates-store';

export type OverrideKind = 'seo' | 'blog';
type Status = 'published' | 'draft';

const OVERRIDE_FILES: Record<OverrideKind, string> = {
  seo: 'seo-publish-overrides.json',
  blog: 'blog-publish-overrides.json',
};

/** Resolve a data file whether cwd is apps/web (turbo) or the repo root. */
function resolveDataFile(name: string): string {
  const candidates = [
    path.join(process.cwd(), 'src', 'data', name),
    path.join(process.cwd(), 'apps', 'web', 'src', 'data', name),
  ];
  return candidates.find((c) => existsSync(c)) ?? candidates[0];
}

function readOverrides(kind: OverrideKind): Record<string, Status> {
  try {
    const raw = readFileSync(resolveDataFile(OVERRIDE_FILES[kind]), 'utf8').trim();
    if (!raw) return {};
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

/** SEO pages flattened for the publishing table (effective status applied). */
export function readSeoRows(): PublishRow[] {
  return SEO_PAGES.map(
    (p): PublishRow => ({
      kind: 'seo',
      id: p.slug,
      title: p.title,
      date: '',
      category: p.sport,
      published: effectiveSeoStatus(p) === 'published',
      autoGenerated: false,
    }),
  ).sort((a, b) => a.title.localeCompare(b.title));
}

/** Blog posts flattened for the publishing table (effective status applied). */
export function readBlogRows(): PublishRow[] {
  return BLOG_POSTS.map(
    (p): PublishRow => ({
      kind: 'blog',
      id: p.slug,
      title: p.title,
      date: p.publishDate,
      category: p.sport,
      published: effectiveBlogStatus(p) === 'published',
      autoGenerated: false,
    }),
  ).sort((a, b) => b.date.localeCompare(a.date));
}

/** The item's base status (ignoring overrides), used to keep the file minimal. */
function baseStatus(kind: OverrideKind, id: string): Status | undefined {
  if (kind === 'seo') {
    const p = SEO_PAGES.find((x) => x.slug === id);
    return p ? p.publishStatus : undefined;
  }
  const p = BLOG_POSTS.find((x) => x.slug === id);
  return p ? p.status ?? 'published' : undefined;
}

export type SetContentPublishResult =
  | { ok: true; published: boolean }
  | { ok: false; reason: 'read-only' | 'not-found' | 'io-error' };

/**
 * Flip an SEO page or blog post between published and draft via its overrides
 * file. Stores an override only when it differs from the item's base status
 * (so reverting to default removes the line).
 */
export function setContentPublishState(
  kind: OverrideKind,
  id: string,
  publish: boolean,
): SetContentPublishResult {
  if (!canWriteUpdates()) return { ok: false, reason: 'read-only' };

  const base = baseStatus(kind, id);
  if (!base) return { ok: false, reason: 'not-found' };

  const overrides = readOverrides(kind);
  const target: Status = publish ? 'published' : 'draft';
  if (target === base) delete overrides[id];
  else overrides[id] = target;

  try {
    writeFileSync(resolveDataFile(OVERRIDE_FILES[kind]), JSON.stringify(overrides, null, 2) + '\n');
  } catch {
    return { ok: false, reason: 'io-error' };
  }
  return { ok: true, published: publish };
}
