// ============================================================
// SwingVantage Admin — auto-update publishing store (SERVER-ONLY)
// ------------------------------------------------------------
// Reads and writes the two auto-generated changelog data files that feed the
// public /updates and /dev-updates pages:
//   • src/data/auto-updates.json      (product updates)
//   • src/data/auto-dev-updates.json  (developer updates)
//
// These files are populated by scripts/generate-updates.mjs from opt-in commit
// trailers, where every entry now lands as a DRAFT. This module lets the admin
// Publishing screen flip an entry between draft and live WITHOUT hand-editing
// JSON — but it stays honest about how publishing actually works here:
//
//   Content lives in VERSIONED data files. A toggle writes the file on disk, so
//   the change is a reviewable git diff you then commit & push (the same model
//   as every other content surface). The production runtime filesystem is
//   read-only, so writes are only possible from a local dev environment.
//
// NEVER import this from a client component — it uses node:fs. The client gets
// plain data via props and calls the guarded API route to mutate.
// ============================================================

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import type { Update } from '@/data/updates';
import type { DevUpdate } from '@/data/devUpdates';

const FILES = {
  product: 'auto-updates.json',
  dev: 'auto-dev-updates.json',
} as const;

export type UpdateKind = keyof typeof FILES;

/** Every content type the admin Publishing screen can flip live. */
export type PublishKind = UpdateKind | 'seo' | 'blog';

/** A single entry, flattened for the publishing table. */
export interface PublishRow {
  kind: PublishKind;
  id: string;
  title: string;
  date: string;
  category: string;
  published: boolean;
  autoGenerated: boolean;
  sourceCommit?: string;
}

export interface PublishSnapshot {
  product: PublishRow[];
  dev: PublishRow[];
  /** Whether this environment can persist toggles (local dev, writable FS). */
  writable: boolean;
}

/**
 * Whether toggles can be persisted. Content writes are a local-dev operation:
 * the change becomes a git diff you commit & push. Vercel's runtime FS is
 * read-only, so production is view-only. An explicit override is supported for
 * self-hosted, writable deployments.
 */
export function canWriteUpdates(): boolean {
  if (process.env.ALLOW_UPDATES_WRITE === '1') return true;
  return process.env.NODE_ENV !== 'production';
}

/** Resolve a data file whether cwd is apps/web (turbo) or the repo root. */
function resolveDataFile(name: string): string {
  const candidates = [
    path.join(process.cwd(), 'src', 'data', name),
    path.join(process.cwd(), 'apps', 'web', 'src', 'data', name),
  ];
  return candidates.find((c) => existsSync(c)) ?? candidates[0];
}

function readArray<T>(name: string): T[] {
  try {
    const raw = readFileSync(resolveDataFile(name), 'utf8').trim();
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as T[]) : [];
  } catch {
    return [];
  }
}

/** A product entry is live only when both status and visibility are public. */
function productIsPublished(u: Update): boolean {
  return u.status === 'published' && u.visibility === 'public';
}

/** A dev entry is live unless explicitly a draft (missing status = published). */
function devIsPublished(u: DevUpdate): boolean {
  return u.status !== 'draft';
}

function toProductRow(u: Update): PublishRow {
  return {
    kind: 'product',
    id: u.id,
    title: u.title,
    date: u.releaseDate,
    category: u.category,
    published: productIsPublished(u),
    autoGenerated: Boolean((u as { autoGenerated?: boolean }).autoGenerated),
    sourceCommit: (u as { sourceCommit?: string }).sourceCommit,
  };
}

function toDevRow(u: DevUpdate): PublishRow {
  return {
    kind: 'dev',
    id: u.id,
    title: u.title,
    date: u.date,
    category: u.category,
    published: devIsPublished(u),
    autoGenerated: Boolean((u as { autoGenerated?: boolean }).autoGenerated),
    sourceCommit: (u as { sourceCommit?: string }).sourceCommit,
  };
}

const byDateDesc = (a: PublishRow, b: PublishRow) => b.date.localeCompare(a.date);

/**
 * Every auto-generated product update entry as a would-be PUBLISHED + PUBLIC
 * candidate (status/visibility forced). Lets the validation + quality gate
 * score what each entry *would* look like live, regardless of its current state.
 */
export function readProductCandidates(): Update[] {
  return readArray<Update>(FILES.product).map((e) => ({
    ...e,
    status: 'published',
    visibility: 'public',
  }));
}

/**
 * A single auto-generated product update entry by id, as the would-be
 * PUBLISHED + PUBLIC candidate. Returns undefined when the id is unknown.
 */
export function readProductCandidate(id: string): Update | undefined {
  return readProductCandidates().find((e) => e.id === id);
}

/** Read both auto-update files for the admin Publishing screen. */
export function readPublishSnapshot(): PublishSnapshot {
  const product = readArray<Update>(FILES.product).map(toProductRow).sort(byDateDesc);
  const dev = readArray<DevUpdate>(FILES.dev).map(toDevRow).sort(byDateDesc);
  return { product, dev, writable: canWriteUpdates() };
}

export type SetPublishResult =
  | { ok: true; published: boolean }
  | { ok: false; reason: 'read-only' | 'not-found' | 'corrupt' | 'io-error' };

/**
 * Flip a single entry between published and draft, persisting to its data file.
 * Idempotent and surgical — only the targeted entry's status/visibility change,
 * preserving the exact 2-space JSON format the generator writes (clean diffs).
 */
export function setPublishState(kind: UpdateKind, id: string, publish: boolean): SetPublishResult {
  if (!canWriteUpdates()) return { ok: false, reason: 'read-only' };

  const file = resolveDataFile(FILES[kind]);
  let arr: Array<Record<string, unknown>>;
  try {
    const raw = readFileSync(file, 'utf8').trim();
    arr = raw ? JSON.parse(raw) : [];
    if (!Array.isArray(arr)) return { ok: false, reason: 'corrupt' };
  } catch {
    return { ok: false, reason: 'io-error' };
  }

  const entry = arr.find((e) => e && e.id === id);
  if (!entry) return { ok: false, reason: 'not-found' };

  if (kind === 'product') {
    entry.status = publish ? 'published' : 'draft';
    entry.visibility = publish ? 'public' : 'private';
    entry.updatedAt = new Date().toISOString().slice(0, 10);
  } else {
    entry.status = publish ? 'published' : 'draft';
  }

  try {
    writeFileSync(file, JSON.stringify(arr, null, 2) + '\n');
  } catch {
    return { ok: false, reason: 'io-error' };
  }
  return { ok: true, published: publish };
}
