// ============================================================
// Link Intelligence Agent — linkable-asset content recommendations
// ------------------------------------------------------------
// Backlinks aren't just found — they're EARNED with link-worthy content.
// This emits AIRecommendation records (kind `recommendation`) describing
// linkable assets to create (original data, comparisons, glossaries,
// calculators), so they flow into the existing Recommendations module.
// ============================================================

import type { AIRecommendation, PriorityInputs } from '../types';
import { AGENT_OWNER } from './constants';
import { id } from './id';

interface AssetSeed {
  key: string;
  title: string;
  whyLinkable: string;
  steps: string[];
  priority: PriorityInputs;
}

const ASSETS: AssetSeed[] = [
  { key: 'faults-by-handicap', title: 'Original data: "Most common golf swing faults by handicap"', whyLinkable: 'Original, citable data is the strongest backlink + AI-citation magnet.', steps: ['Aggregate anonymized swing-fault data', 'Visualize by handicap band', 'Publish with a methodology note', 'Pitch to golf-tech press'], priority: { impact: 'high', confidence: 'medium', effort: 'high', strategicFit: 'high' } },
  { key: 'best-swing-apps', title: 'Comparison hub: "Best AI swing analysis apps" (honest, inclusive)', whyLinkable: 'Comparison pages attract links and rank for high-intent queries.', steps: ['Build an objective feature matrix', 'Include competitors fairly', 'Add FAQ + schema', 'Interlink to sport hubs'], priority: { impact: 'high', confidence: 'medium', effort: 'medium', strategicFit: 'high' } },
  { key: 'glossary-expansion', title: 'Per-sport technique glossaries (pickleball, padel, softball)', whyLinkable: 'Glossaries earn reference links and feed AEO/GEO definitions.', steps: ['Define 20–30 terms per sport', 'Add DefinedTerm schema', 'Interlink terms to guides'], priority: { impact: 'medium', confidence: 'high', effort: 'medium', strategicFit: 'high' } },
  { key: 'exit-velo-calculator', title: 'Embeddable calculator: exit velocity / smash factor', whyLinkable: 'Free embeddable tools earn natural links when others embed them.', steps: ['Build a simple calculator', 'Add an embed snippet', 'Promote to coaches/sites'], priority: { impact: 'medium', confidence: 'medium', effort: 'high', strategicFit: 'medium' } },
  { key: 'recruiting-checklist', title: 'Downloadable recruiting-video checklist (baseball/softball)', whyLinkable: 'Practical downloadables earn links from recruiting + parent resources.', steps: ['Create a one-page checklist', 'Gate-free PDF + HTML', 'Pitch to recruiting sites'], priority: { impact: 'medium', confidence: 'high', effort: 'low', strategicFit: 'high' } },
  { key: 'coach-resource-kit', title: 'Coach resource kit (drills + how-to-use-AI-analysis)', whyLinkable: 'Coaches link to and share genuinely useful, non-promotional kits.', steps: ['Bundle drills + a coach guide', 'Make it embeddable/shareable', 'Pitch to academies'], priority: { impact: 'medium', confidence: 'medium', effort: 'medium', strategicFit: 'high' } },
];

/** Emit linkable-asset content recommendations (kind `recommendation`). */
export function discoverContentGaps(): AIRecommendation[] {
  const now = new Date().toISOString();
  return ASSETS.map((a) => ({
    id: id('recommendation-li', a.key),
    name: a.title,
    dataSource: 'placeholder',
    owner: AGENT_OWNER,
    notes: 'Generated by the Link Intelligence Agent (linkable-asset opportunity).',
    createdAt: now,
    updatedAt: now,
    lever: 'brand-authority',
    funnelStage: 'awareness',
    reasoning: a.whyLinkable,
    requiredAssets: ['Content brief', 'Design/asset where applicable'],
    implementationSteps: a.steps,
    successMetric: 'Referring domains earned + AI-citation appearances',
    priority: a.priority,
    status: 'idea',
    basis: 'strategic',
  }));
}
