// ============================================================
// SwingIQ — Baseball Drill Library
// Drills mapped to visual swing issues and phases.
// All YouTube links are SEARCH LINKS only — never hardcoded video IDs.
// ============================================================

import type { SportDrillRecommendation } from '../types';

function ytSearch(query: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
}

export const BASEBALL_DRILLS: SportDrillRecommendation[] = [
  // ── Casting Hands ─────────────────────────────────────────────
  {
    id: 'bb_back_to_screen',
    sport_id: 'baseball',
    issue_id: 'casting_hands',
    phase: 'bat_lag',
    name: 'Back-to-the-Screen Drill',
    goal: 'Eliminate bat casting by keeping the knob to the ball path',
    steps: [
      'Stand with your back to a fence or batting cage screen, 6-8 inches away',
      'Take your normal stance and begin the swing',
      'The bat should NOT hit the screen on the backswing or early downswing',
      'If the barrel hits the screen, you are casting — the screen provides immediate feedback',
      'Work in slow motion first, then progress to tee work, then live BP',
    ],
    reps_or_duration: '3 sets of 15 tee swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, batting cage, tee',
    safety_note: 'Ensure no one is in the path of the bat before drilling.',
    youtube_search_query: 'baseball casting drill back to screen hitting',
    youtube_search_url: ytSearch('baseball casting drill back to screen hitting'),
    coach_channel_hint: 'Tanner Koziol, Baseball Hitting Academy',
    focus_feel: 'Feel your hands staying close — knob leading, barrel dragging.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Hip Stall ─────────────────────────────────────────────────
  {
    id: 'bb_hip_fire_tee',
    sport_id: 'baseball',
    issue_id: 'hip_stall',
    phase: 'hip_rotation',
    name: 'Hip-Fire Tee Drill',
    goal: 'Train explosive hip rotation through the contact zone',
    steps: [
      'Set tee at belt height — center of the plate',
      'Take your normal stance and load',
      'On the swing, consciously think "hip-shoulder-hands" in that sequence',
      '"Squish the bug" with your back foot as hips fire',
      'Hold your finish — belt buckle should point at the pitcher',
    ],
    reps_or_duration: '3 sets of 20 — hold finish 2 seconds each',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, batting tee, ball',
    safety_note: null,
    youtube_search_query: 'baseball hip rotation drill squish bug tee work',
    youtube_search_url: ytSearch('baseball hip rotation drill squish bug tee work'),
    coach_channel_hint: 'Driveline Baseball, Cressey Sports',
    focus_feel: 'Feel your back hip driving through — squish the bug, belt to the pitcher.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Lunging Forward ───────────────────────────────────────────
  {
    id: 'bb_soft_stride_drill',
    sport_id: 'baseball',
    issue_id: 'lunging_forward',
    phase: 'stride',
    name: 'Soft Stride — Stay Back Drill',
    goal: 'Train a controlled soft stride without shifting weight forward',
    steps: [
      'Place a cone or line at your normal stride landing spot',
      'Practice the load and stride without swinging — focus on soft landing',
      'Your front foot lands softly, heel-first, while hands stay back',
      'Feel 60% of your weight on your back leg at landing',
      'Add swing once stride feels controlled — tee work first',
    ],
    reps_or_duration: '3 sets of 20 stride-only reps, then 20 tee swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee, cone or line marker',
    safety_note: null,
    youtube_search_query: 'baseball staying back soft stride drill hitting',
    youtube_search_url: ytSearch('baseball staying back soft stride drill hitting'),
    coach_channel_hint: 'ProBaseballInsider',
    focus_feel: 'Stride feels like stepping on a scale — gentle, controlled, not a fall forward.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Early Shoulder Pull ───────────────────────────────────────
  {
    id: 'bb_inside_tee_opposite',
    sport_id: 'baseball',
    issue_id: 'early_shoulder_pull',
    phase: 'hip_rotation',
    name: 'Inside Tee Opposite-Field Drill',
    goal: 'Prevent early front shoulder opening by training opposite-field contact',
    steps: [
      'Set tee on the inside-back portion of the plate (deep contact position)',
      'Goal: drive the ball to opposite field',
      'If front shoulder opens early, ball goes foul or weakly to pull side',
      'Keep front shoulder closed until hips clear — then shoulders follow',
      'Progress to outside pitch location on the tee',
    ],
    reps_or_duration: '3 sets of 15 opposite-field tee swings',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, batting tee, balls',
    safety_note: null,
    youtube_search_query: 'baseball front shoulder opening early drill opposite field',
    youtube_search_url: ytSearch('baseball front shoulder opening early drill opposite field'),
    coach_channel_hint: 'Tanner Koziol',
    focus_feel: 'Keep that front shoulder closed until your hips are through — then let it fly.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Head Off Ball ─────────────────────────────────────────────
  {
    id: 'bb_read_the_seams',
    sport_id: 'baseball',
    issue_id: 'head_off_ball',
    phase: 'contact',
    name: 'Read the Seams Drill',
    goal: 'Train head stillness by requiring the hitter to identify ball details at contact',
    steps: [
      'Pitcher or tossing partner writes a number (1, 2, 3) on several balls in marker',
      'Hitter must call out the number on the ball while hitting or immediately after',
      'If they cannot identify the number, they are not keeping eyes on the ball',
      'Tee variation: put a sticker on the ball; call out the color at contact',
      'Progress to live soft-toss, then machine or BP',
    ],
    reps_or_duration: '3 sets of 15 — call the number/color each time',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Balls with numbers marked, bat, tee or soft-toss',
    safety_note: null,
    youtube_search_query: 'baseball read the seams numbers drill eyes on ball contact',
    youtube_search_url: ytSearch('baseball read the seams numbers drill eyes on ball contact'),
    coach_channel_hint: 'Baseball Rebellion',
    focus_feel: 'See the ball on the bat. Not the result — the actual contact moment.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Chopping Swing ────────────────────────────────────────────
  {
    id: 'bb_level_swing_tee',
    sport_id: 'baseball',
    issue_id: 'chopping_swing',
    phase: 'extension',
    name: 'Level Through the Zone Tee Drill',
    goal: 'Replace chopping motion with a slight upward swing matching the pitch descent angle',
    steps: [
      'Set tee at belt height in the center of the plate',
      'Consciously drive the barrel through on a level to slight-upward path',
      'Aim to hit the ball with a line-drive trajectory, not a bouncer',
      'Check: ball should fly in a line, not arc or bounce immediately',
      'Variation: set two tees — one at normal height, one 2 inches higher and 8 inches in front; barrel must travel between both tees',
    ],
    reps_or_duration: '4 sets of 15 with focus on trajectory',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, two batting tees, balls',
    safety_note: null,
    youtube_search_query: 'baseball level swing path drill tee work line drive',
    youtube_search_url: ytSearch('baseball level swing path drill tee work line drive'),
    coach_channel_hint: 'Driveline Baseball',
    focus_feel: 'Drive through the zone — barrel on the same plane as the ball, not chopping down.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Arm Bar Lead ──────────────────────────────────────────────
  {
    id: 'bb_one_hand_drill',
    sport_id: 'baseball',
    issue_id: 'arm_bar_lead',
    phase: 'bat_lag',
    name: 'Lead Arm One-Hand Swing Drill',
    goal: 'Remove arm bar by training lead arm pull without rigidity',
    steps: [
      'Use a light bat or training bat',
      'Remove your back hand and swing with only the lead arm',
      'The lead arm should bend naturally — pulling, not extending too early',
      'Contact should still feel firm — not floppy',
      'After 10 reps, re-add the back hand and replicate the feeling',
    ],
    reps_or_duration: '3 sets of 10 one-hand, 10 two-hand',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Light bat or training bat, tee',
    safety_note: 'Use a lighter training bat for single-arm work — reduces wrist strain.',
    youtube_search_query: 'baseball one hand lead arm drill bat lag',
    youtube_search_url: ytSearch('baseball one hand lead arm drill bat lag'),
    coach_channel_hint: 'Baseball Hitting Academy',
    focus_feel: 'Feel the lead arm pulling — active but not locked straight.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Stance Setup ─────────────────────────────────────────
  {
    id: 'bb_stance_routine_drill',
    sport_id: 'baseball',
    issue_id: 'poor_stance_setup',
    phase: 'load',
    name: 'Stance Routine Groove Drill',
    goal: 'Build a consistent pre-swing stance routine and setup position',
    steps: [
      'Stand in front of a mirror or video yourself from the front',
      'Check feet: shoulder-width apart, toes angled slightly inward',
      'Check knees: soft flex, not locked or overly bent',
      'Check weight: 50/50 distribution, athletic posture with slight forward lean',
      'Repeat the setup 20 times until the feel becomes automatic',
    ],
    reps_or_duration: '20 deliberate stance setups before each practice',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, mirror optional',
    safety_note: null,
    youtube_search_query: 'baseball batting stance setup drill athletic position',
    youtube_search_url: ytSearch('baseball batting stance setup drill athletic position'),
    coach_channel_hint: 'Baseball Rebellion, ProBaseballInsider',
    focus_feel: 'Balanced, athletic, ready — like a shortstop awaiting the pitch.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Late Load ─────────────────────────────────────────────────
  {
    id: 'bb_early_load_timing',
    sport_id: 'baseball',
    issue_id: 'late_load',
    phase: 'load',
    name: 'Early Load Timing Trigger Drill',
    goal: 'Establish the load cue earlier in the pitching motion',
    steps: [
      'Watch live pitching or video — identify the pitcher\'s "trigger" moment (knee lift or hand separation)',
      'Begin your load at that trigger — not at release',
      'Shadow the pitcher motion: when knee lifts, begin your weight shift back',
      'Practice 20 repetitions against video pitch sequences',
      'Progress to cage work using the load trigger',
    ],
    reps_or_duration: '20 load triggers per session',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, video of pitcher optional',
    safety_note: null,
    youtube_search_query: 'baseball early load drill timing pitcher motion trigger',
    youtube_search_url: ytSearch('baseball early load drill timing pitcher motion trigger'),
    coach_channel_hint: 'Driveline Baseball, Baseball Rebellion',
    focus_feel: 'Load begins with the pitcher — you are already moving when the ball releases.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Stride Direction ─────────────────────────────────────
  {
    id: 'bb_stride_line_drill',
    sport_id: 'baseball',
    issue_id: 'poor_stride_direction',
    phase: 'stride',
    name: 'Stride Line Constraint Drill',
    goal: 'Train stride foot to land on a straight line toward the pitcher',
    steps: [
      'Draw or tape a straight line from back foot toward the pitcher\'s mound',
      'Stride foot must land on or parallel to that line every rep',
      'If foot lands to the left or right, reset and repeat',
      'Video from the front to verify foot direction clearly',
      'Progress to live batting practice after 50 consecutive correct strides',
    ],
    reps_or_duration: '3 sets of 20 stride-only reps on the line',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tape or chalk line',
    safety_note: null,
    youtube_search_query: 'baseball stride direction drill straight line to pitcher',
    youtube_search_url: ytSearch('baseball stride direction drill straight line to pitcher'),
    coach_channel_hint: 'ProBaseballInsider',
    focus_feel: 'Toe points at the pitcher — stride is arrow-straight to the mound.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Over-Striding ─────────────────────────────────────────────
  {
    id: 'bb_stride_length_marker',
    sport_id: 'baseball',
    issue_id: 'over_striding',
    phase: 'stride',
    name: 'Stride Length Marker Drill',
    goal: 'Limit stride to an appropriate, balanced length',
    steps: [
      'Place a flat marker just past your normal comfortable stride landing spot',
      'Your front foot must land AT or BEFORE the marker — not past it',
      'Practice load-and-stride 20 times focusing on short, controlled landing',
      'Front knee should remain flexed at landing — not locked out',
      'Add tee work once stride length is consistently controlled',
    ],
    reps_or_duration: '3 sets of 20 stride-to-marker reps',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, flat marker, tee',
    safety_note: null,
    youtube_search_query: 'baseball short stride drill controlled length marker',
    youtube_search_url: ytSearch('baseball short stride drill controlled length marker'),
    coach_channel_hint: 'Tanner Koziol',
    focus_feel: 'Short, soft step — like landing on eggshells without breaking them.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Hip-Shoulder Separation ──────────────────────────────
  {
    id: 'bb_separation_half_swing',
    sport_id: 'baseball',
    issue_id: 'poor_hip_shoulder_separation',
    phase: 'hip_rotation',
    name: 'Hip-Pause-Shoulders Drill',
    goal: 'Isolate hip rotation from shoulder rotation to build the X-factor stretch',
    steps: [
      'Take your normal stance, then fire the hips open while keeping your hands still',
      'Pause when hips are open but shoulders are still closed — hold 1 second',
      'Now let the hands and shoulders follow',
      'Repeat: hips fire, PAUSE, then hands',
      'Progress to continuous motion keeping the sequence: hips first, then hands',
    ],
    reps_or_duration: '3 sets of 15 hip-pause-hands reps',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat',
    safety_note: null,
    youtube_search_query: 'baseball hip shoulder separation drill X factor stretch hitting',
    youtube_search_url: ytSearch('baseball hip shoulder separation drill X factor stretch hitting'),
    coach_channel_hint: 'Baseball Rebellion, Driveline Baseball',
    focus_feel: 'Hips go — hands stay — then hands explode. Feel the stretch between them.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Collapsing Back Side ──────────────────────────────────────
  {
    id: 'bb_back_hip_drive',
    sport_id: 'baseball',
    issue_id: 'collapsing_back_side',
    phase: 'hip_rotation',
    name: 'Back Hip Drive Through Drill',
    goal: 'Train the back hip to drive forward rather than collapse',
    steps: [
      'Set up at a tee with back foot on a balance disk or soft surface',
      'On the swing, consciously drive the back hip through toward the pitcher',
      'Back toe should point down at finish (squish-the-bug) — not collapse inward',
      'Hold the finish position for 2 seconds and check back knee direction',
      'Perform without the tee as shadow swings if needed',
    ],
    reps_or_duration: '3 sets of 15 tee swings with finish holds',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee, balance disk optional',
    safety_note: null,
    youtube_search_query: 'baseball back hip drive drill squish bug finish tee',
    youtube_search_url: ytSearch('baseball back hip drive drill squish bug finish tee'),
    coach_channel_hint: 'Driveline Baseball',
    focus_feel: 'Back hip drives through — feel the back toe pointing down at finish.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Long Swing Path ───────────────────────────────────────────
  {
    id: 'bb_towel_drill_short',
    sport_id: 'baseball',
    issue_id: 'long_swing_path',
    phase: 'bat_lag',
    name: 'Towel Short-Path Drill',
    goal: 'Train hands inside the ball — shorten the swing path through the zone',
    steps: [
      'Roll a towel into a tight cylinder and tie it to where the bat handle meets the barrel',
      'Swing the bat — the towel extends away on a long path; keep it tucked to your body',
      'Alternatively: swing with a small nerf or light training bat to feel compact path',
      'Focus: knob of the bat goes to the ball first — barrel stays back',
      'Progress to tee work with the same compact-path feel',
    ],
    reps_or_duration: '3 sets of 20 compact-path shadow swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, towel or training bat',
    safety_note: null,
    youtube_search_query: 'baseball short swing path inside the ball drill hands',
    youtube_search_url: ytSearch('baseball short swing path inside the ball drill hands'),
    coach_channel_hint: 'Baseball Hitting Academy',
    focus_feel: 'Hands close to the body — barrel arrives LAST at contact.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Pull Off Early ────────────────────────────────────────────
  {
    id: 'bb_oppo_focus_cage',
    sport_id: 'baseball',
    issue_id: 'pull_off_early',
    phase: 'contact',
    name: 'Opposite-Field Focus Cage Drill',
    goal: 'Eliminate pulling off by training opposite-field intent on every pitch',
    steps: [
      'In the cage, every pitch is an opposite-field pitch — no pull-side contact',
      'Visualize driving every ball to right-center (for right-handers)',
      'Front shoulder stays in — head stays down through contact',
      'Hold the finish and check head position: should still be near the contact point',
      'Progress: alternate oppo and pull-side once pulling off is eliminated',
    ],
    reps_or_duration: '3 sets of 20 opposite-field cage swings',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, batting cage or machine',
    safety_note: null,
    youtube_search_query: 'baseball pulling off ball early drill opposite field head down',
    youtube_search_url: ytSearch('baseball pulling off ball early drill opposite field head down'),
    coach_channel_hint: 'Tanner Koziol, Baseball Rebellion',
    focus_feel: 'Head stays down. Drive it the other way. Hips lead, shoulder follows.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Drifting / Swaying ────────────────────────────────────────
  {
    id: 'bb_wall_stop_load',
    sport_id: 'baseball',
    issue_id: 'drifting_swaying',
    phase: 'load',
    name: 'Wall Stop Load Drill',
    goal: 'Prevent excessive backward sway by using a wall as a physical constraint',
    steps: [
      'Stand with your back foot 4 inches from a wall',
      'Load your weight — back hip should press toward the wall, but not past it',
      'If you sway, your hip or elbow touches the wall giving instant feedback',
      'Keep the load centered over the back foot — not behind it',
      'Repeat 20 times, then move away from the wall and replicate the feel',
    ],
    reps_or_duration: '3 sets of 20 load checks against the wall',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, wall',
    safety_note: null,
    youtube_search_query: 'baseball no sway load drill wall constraint stay centered',
    youtube_search_url: ytSearch('baseball no sway load drill wall constraint stay centered'),
    coach_channel_hint: 'ProBaseballInsider',
    focus_feel: 'Back hip loads into the wall — centered, not drifting behind.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },
];

// ──────────────────────────────────────────────────────────────
// Lookup helpers
// ──────────────────────────────────────────────────────────────

export function getBaseballDrillsForIssue(issueId: string): SportDrillRecommendation[] {
  return BASEBALL_DRILLS.filter((d) => d.issue_id === issueId);
}

export function getBaseballDrillsForPhase(phase: string): SportDrillRecommendation[] {
  return BASEBALL_DRILLS.filter((d) => d.phase === phase);
}
