// ============================================================
// PublishingOS — deploy-backed publish PLAN (PURE)
// ------------------------------------------------------------
// A PublishPlan is the file-level diff + PR copy the executor turns into a real
// GitHub pull request. Pure + deterministic (no IO), so it is fully unit-tested;
// the GitHub side (./github) just executes a plan.
//
// The first concrete plan PROMOTES a runtime publish decision into a committed
// overrides manifest — making a PublishingOS toggle permanent in source (it
// survives a DB reset), via a reviewable PR rather than a direct push.
// ============================================================

export interface PlanFile {
  path: string;
  /** Full UTF-8 file content (the executor commits the file wholesale). */
  content: string;
}

export interface PublishPlan {
  /** New branch name (created off the repo's base branch). */
  branch: string;
  files: PlanFile[];
  commitMessage: string;
  prTitle: string;
  prBody: string;
}

/** Repo path of the committed publish-override manifest. */
export const COMMITTED_OVERRIDES_PATH = 'apps/web/src/content/publishing/committed-overrides.json';

/** Stable `${entityType}:${entityId}` override key. */
export function overrideKey(entityType: string, entityId: string): string {
  return `${entityType}:${entityId}`;
}

function sortKeys(obj: Record<string, boolean>): Record<string, boolean> {
  return Object.fromEntries(Object.keys(obj).sort().map((k) => [k, obj[k]]));
}

function slugify(s: string): string {
  return s.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase().slice(0, 40) || 'entity';
}

export interface OverridePromotionInput {
  entityType: string;
  entityId: string;
  published: boolean;
  title?: string;
  /** Current manifest (merged into); defaults to empty so callers can pass the
   *  repo's existing file to avoid clobbering other entries. */
  existingManifest?: Record<string, boolean>;
  actorEmail?: string;
  /** Injectable for deterministic tests. */
  now?: string;
  branchSuffix?: string;
}

/** Build the PR plan that writes the merged override manifest. Deterministic
 *  when `now` + `branchSuffix` are supplied. */
export function buildOverridePromotionPlan(input: OverridePromotionInput): PublishPlan {
  const key = overrideKey(input.entityType, input.entityId);
  const manifest = sortKeys({ ...(input.existingManifest ?? {}), [key]: input.published });
  const ts = input.now ?? new Date().toISOString();
  const suffix = input.branchSuffix ?? String(Date.now());
  const verb = input.published ? 'publish' : 'unpublish';

  return {
    branch: `publish/${slugify(input.entityType)}-${slugify(input.entityId)}-${suffix}`,
    files: [{ path: COMMITTED_OVERRIDES_PATH, content: JSON.stringify(manifest, null, 2) + '\n' }],
    commitMessage: `chore(publishing): ${verb} ${key}`,
    prTitle: `Publish: ${verb} ${input.title ?? key}`,
    prBody:
      `Promotes a PublishingOS runtime decision to source (committed override manifest).\n\n` +
      `- **Entity:** \`${key}\`\n` +
      `- **Decision:** ${input.published ? 'published' : 'unpublished'}\n` +
      `- **When:** ${ts}\n` +
      (input.actorEmail ? `- **By:** ${input.actorEmail}\n` : '') +
      `\nGenerated by the PublishingOS deploy-backed executor. Merging applies it permanently.`,
  };
}

/** Parse a committed manifest's raw JSON safely (→ {} on any problem). */
export function parseManifest(raw: string | null | undefined): Record<string, boolean> {
  if (!raw) return {};
  try {
    const obj = JSON.parse(raw);
    if (!obj || typeof obj !== 'object') return {};
    const out: Record<string, boolean> = {};
    for (const [k, v] of Object.entries(obj)) if (typeof v === 'boolean') out[k] = v;
    return out;
  } catch {
    return {};
  }
}
