// ============================================================
// SwingVantage — Tutorial video catalogue (shard 1 of 2)
// ------------------------------------------------------------
// Size-shard of RAW_TUTORIAL_VIDEOS, split out of videos.ts so no single file
// exceeds ~600 lines (fewer merge conflicts — roadmap #20). Spread back into
// RAW_TUTORIAL_VIDEOS in videos.ts IN ORDER, then applyRecordings() merges the
// generated recordings — so behavior is unchanged.
// ============================================================

import type { TutorialVideo } from './videos';

export const RAW_VIDEOS_1: TutorialVideo[] = [
  // ── Getting Started ───────────────────────────────────────
  {
    id: 'welcome',
    title: 'Welcome to SwingVantage',
    description: 'A quick guided tour of what SwingVantage is and how it helps you improve.',
    audiences: 'all',
    category: 'getting-started',
    duration: '1:05',
    route: '/dashboard',
    journeyStage: 'discover',
    priority: 'high',
    fallbackText: 'Here’s the 60-second version of how SwingVantage works.',
    script: [
      'SwingVantage is your personal performance system for golf, tennis, baseball, and softball.',
      'The idea is simple: analyze your swing, learn what to work on, practice it, and watch yourself improve over time.',
      'Everything stays private to you — and you can get started right away, no account required.',
      'This tutorial is organized by who you are. Pick Player, Parent, Coach, or Team and we’ll show you the right path.',
      'You can skip the tutorial anytime and come back to it from the menu whenever you like.',
    ],
  },
  {
    id: 'start-here',
    title: 'Set up in 2 minutes (Start Here)',
    description: 'Answer a few quick questions and get your first personalized result.',
    audiences: 'all',
    category: 'getting-started',
    duration: '2:30',
    route: '/start',
    script: [
      'Open “Start Here” from the menu. Pick every sport you play — you can switch between them anytime.',
      'Tell us who this is for: a player, a parent helping a young athlete, a coach, or a team. This tailors the tone and safety reminders.',
      'Choose how to begin: answer a couple of questions, upload a video, or import data. The quiz is the fastest route to a first result.',
      'You’ll get a top thing to work on, a confidence level, three beginner-safe drills, and a 7-day plan.',
      'Used SwingVantage before? Use “Skip setup” to jump straight to your dashboard.',
    ],
  },
  {
    id: 'dashboard',
    title: 'Your Today dashboard',
    description: 'Where your day starts: your focus, recent sessions, and what to do next.',
    audiences: 'all',
    category: 'getting-started',
    duration: '2:00',
    route: '/dashboard',
    journeyStage: 'onboard',
    fallbackText: 'A quick tour of your Today dashboard and where everything lives.',
    script: [
      'The dashboard is “Today.” Everything here is filtered to your active sport.',
      'Up top you’ll see your recommended next action — the single best thing to do right now.',
      'Below that: recent sessions, how your key metrics are trending, and your streak and achievements.',
      'Tap any card to dive deeper. The dashboard is always your home base — the SwingVantage logo brings you back here.',
    ],
  },
  {
    id: 'switch-sport',
    title: 'Pick or switch your sport',
    description: 'Keep separate data for every sport you play and switch in one tap.',
    audiences: 'all',
    category: 'getting-started',
    duration: '1:30',
    route: '/dashboard',
    script: [
      'SwingVantage supports golf, tennis, baseball, slow-pitch and fast-pitch softball.',
      'Use the sport switcher near the bottom of the side menu to change your active sport.',
      'Each sport keeps its own profile, sessions, drills, and progress — nothing gets mixed together.',
      'Switching sport instantly re-tailors the whole app: labels, metrics, drills, and coaching all follow the sport you choose.',
    ],
  },
  {
    id: 'navigation',
    title: 'Finding your way around',
    description: 'A quick map of the menu so you never feel lost.',
    audiences: 'all',
    category: 'getting-started',
    duration: '1:30',
    route: '/dashboard',
    script: [
      'The side menu follows one path: Today → Analyze → Practice → Progress → Share & Coach.',
      'Analyze, Practice, and Progress each expand to reveal more tools — tap the arrow to open a section.',
      'On a phone, tap the menu icon (or “More”) to open the same navigation.',
      'The “?” Guide button on each screen explains exactly what you’re looking at, in plain language.',
      'And the Tutorials link in the menu brings you right back here anytime.',
    ],
  },

  // ── Analyze Your Swing ────────────────────────────────────
  {
    id: 'video-analysis',
    title: 'Upload & analyze a swing video',
    description: 'Film a swing, upload it, and get clear, AI-assisted feedback.',
    audiences: 'all',
    category: 'analyze',
    duration: '3:30',
    route: '/video',
    journeyStage: 'capture',
    priority: 'high',
    fallbackText: 'How to film and upload a swing the AI can read confidently.',
    script: [
      'Film from a steady position — down-the-line (behind you, toward the target) or face-on. Keep the whole body in frame.',
      'Upload the clip on the Video Analysis screen. SwingVantage breaks the swing into phases and looks for common faults in each.',
      'Every finding comes with a plain-language explanation and how strongly we believe it — shown as a confidence level.',
      'Visual conclusions are labeled as estimates, not measurements. Use them as a smart starting point, not the final word.',
      'Your results are saved so you can compare future swings against this one.',
    ],
  },
  {
    id: 'diagnose',
    title: 'Diagnose your swing',
    description: 'Turn session data into the key issues holding you back — ranked.',
    audiences: ['athlete', 'coach'],
    category: 'analyze',
    duration: '3:00',
    route: '/diagnose',
    journeyStage: 'understand',
    fallbackText: 'How to read your AI analysis: scores, issues, and what to do next.',
    script: [
      'Pick a session and SwingVantage finds the most significant patterns in your shots.',
      'Each issue gets a severity (Critical, High, Medium, Low) and a confidence score, so you know what to fix first.',
      'Your swing score rates the session’s consistency. It’s built to track trends, not to define your ability.',
      'From here, jump straight to the recommended drills that target what the analysis found.',
    ],
  },
  {
    id: 'motion-lab',
    title: 'Motion Lab: 3D analysis',
    description: 'Browser-side 3D motion capture from your camera — no extra hardware.',
    audiences: ['athlete', 'coach'],
    category: 'analyze',
    duration: '3:00',
    route: '/motion-lab',
    script: [
      'Motion Lab estimates your body’s motion in 3D, right in the browser, from a normal video.',
      'Record or upload a swing and SwingVantage tracks key body points through the movement.',
      'Use it to see rotation, sequence, and timing that are hard to judge with the naked eye.',
      'Like all visual analysis, it’s an estimate — great for spotting patterns and comparing before/after.',
    ],
  },
  {
    id: 'avatar',
    title: 'Your 3D Swing Avatar',
    description: 'See your swing as a clean 3D model you can rotate and replay.',
    audiences: ['athlete'],
    category: 'analyze',
    duration: '2:00',
    route: '/avatar',
    script: [
      'The Swing Avatar turns your motion into a simple 3D figure you can orbit and replay.',
      'Stripping away the background makes positions and sequence much easier to see.',
      'Scrub through the phases to check positions at takeaway, top, and impact.',
      'It’s a visualization aid — pair it with Diagnose or Video Analysis for the “what to fix” part.',
    ],
  },
  {
    id: 'ai-coach',
    title: 'Ask the AI Coach',
    description: 'Ask anything about your swing, your data, or what to do next.',
    audiences: 'all',
    category: 'analyze',
    duration: '2:30',
    route: '/ai-coach',
    script: [
      'Type any question — “Why is my carry inconsistent?” or “What should I work on next?”',
      'When you have sessions saved, the AI Coach can reference your actual data for more specific answers.',
      'It’s great for explaining a metric, a drill, or a diagnosis in plain language.',
      'One limit to know: it doesn’t watch your swing live. For that, use Video Analysis or Motion Lab.',
    ],
  },
  {
    id: 'import-data',
    title: 'Import launch-monitor data',
    description: 'Bring in CSV data from FlightScope, Trackman, SkyTrak, and more.',
    audiences: ['athlete', 'coach'],
    category: 'analyze',
    duration: '3:00',
    route: '/sessions/import',
    script: [
      'Export a CSV from your launch monitor and drop it onto the import screen.',
      'SwingVantage reads the columns and maps them to the right metrics — carry, ball speed, launch, spin, and more.',
      'Review the preview to make sure everything mapped correctly, then save it as a session.',
      'Imported sessions feed your diagnosis, progress charts, and benchmarks — the more data, the sharper the picture.',
    ],
  },
  {
    id: 'import-image',
    title: 'Snap a photo of your numbers',
    description: 'No CSV? Photograph the launch-monitor screen and let SwingVantage read it.',
    audiences: ['athlete', 'coach'],
    category: 'analyze',
    duration: '2:00',
    route: '/sessions/import/image',
    script: [
      'Take a clear, well-lit photo of the data table on your launch monitor screen.',
      'Upload it and SwingVantage reads the numbers from the image automatically.',
      'Always check the extracted values for accuracy and fix any misreads before saving.',
      'It’s the fastest way to capture a session when you can’t export a file.',
    ],
  },

  // ── Practice & Improve ────────────────────────────────────
  {
    id: 'training',
    title: 'Your training plan',
    description: 'A focused plan built from your diagnosis — what to work on, in order.',
    audiences: ['athlete', 'parent', 'coach'],
    category: 'practice',
    duration: '2:30',
    route: '/training',
    script: [
      'Your plan highlights the highest-priority issue first, so practice time goes where it counts.',
      'Each focus area has specific drills. Work through them in order — they build on each other.',
      'Check off drills as you go. SwingVantage tracks your consistency and suggests when to retest.',
      'Practicing on consecutive days builds your streak, which earns XP and badges.',
    ],
  },
  {
    id: 'fix-stack',
    title: 'Today’s Fix',
    description: 'The one thing to work on today — a tiny, doable next step.',
    audiences: ['athlete', 'parent'],
    category: 'practice',
    duration: '2:00',
    route: '/fix',
    script: [
      'The Fix Stack gives you one clear thing to work on right now — no overwhelm.',
      'It’s drawn from your most recent analysis and stacked in priority order.',
      'Do the fix, mark it done, and the next one moves up. Small steps, stacked daily, add up fast.',
      'Perfect for busy days or younger athletes who do best with a single focus.',
    ],
  },
  {
    id: 'drills',
    title: 'The Drill Library',
    description: 'Browse drills by sport, skill level, and the exact issue they fix.',
    audiences: ['athlete', 'parent', 'coach'],
    category: 'practice',
    duration: '2:00',
    route: '/drills',
    journeyStage: 'improve',
    fallbackText: 'Turn your top fix into a focused, doable practice plan.',
    script: [
      'Filter drills by your sport, skill level, and the issue you want to fix.',
      'Drills are grouped by what they target — path, face, timing, contact, and more.',
      'Start with the ones marked high-priority for your current diagnosis.',
      'Doing drills in a focused sequence beats doing random ones — quality over quantity.',
    ],
  },
  {
    id: 'practice-schedule',
    title: 'Build a practice schedule',
    description: 'Turn your focus areas into a realistic weekly plan.',
    audiences: ['athlete', 'parent', 'coach'],
    category: 'practice',
    duration: '2:00',
    route: '/practice',
    script: [
      'Tell SwingVantage how many days a week you practice and how long sessions run.',
      'You’ll get a day-by-day plan, each with a single clear focus.',
      'Sticking to the focus for each session is what drives real change.',
      'Adjust anytime — the schedule flexes around your week, not the other way around.',
    ],
  },
  {
    id: 'pre-round',
    title: 'Warm up before you play',
    description: 'A targeted warm-up based on what you’ve been training.',
    audiences: ['athlete'],
    category: 'practice',
    duration: '1:30',
    route: '/pre-round',
    script: [
      'Before a round or game, get a quick warm-up tuned to your current focus.',
      'It activates the movements you’ve been practicing so they show up when it counts.',
      'It also surfaces early if your timing or contact is off, before the first shot matters.',
      'A few focused minutes here beats a generic warm-up every time.',
    ],
  },

  // ── Track Your Progress ───────────────────────────────────
  {
    id: 'progress',
    title: 'Track your progress',
    description: 'See your key metrics trend over time across all your sessions.',
    audiences: 'all',
    category: 'progress',
    duration: '2:30',
    route: '/progress',
    journeyStage: 'track',
    fallbackText: 'How progress tracking works: trends, comparisons, and streaks.',
    script: [
      'Progress charts each key metric over time — carry, swing score, contact, and more.',
      'An upward trend on a positive metric means it’s working. Flat or down tells you where to look.',
      'The metrics shown match your active sport, so you always see what matters for your game.',
      'Charts get more reliable with more sessions — five or more in a category shows a real trend.',
    ],
  },
  {
    id: 'player-arc',
    title: 'Your Player Arc story',
    description: 'Your improvement told as a story, not just charts.',
    audiences: ['athlete', 'parent'],
    category: 'progress',
    duration: '2:00',
    route: '/arc',
    script: [
      'Player Arc stitches your sessions into a narrative of how far you’ve come.',
      'It highlights breakthroughs, plateaus, and what changed around them.',
      'It’s a motivating way to look back — especially for young athletes and the parents cheering them on.',
      'The more you practice and retest, the richer your arc becomes.',
    ],
  },
];
