// ============================================================
// SwingVantage — Tutorial video catalogue (shard 2 of 2)
// ------------------------------------------------------------
// Size-shard of RAW_TUTORIAL_VIDEOS, split out of videos.ts so no single file
// exceeds ~600 lines (fewer merge conflicts — roadmap #20). Spread back into
// RAW_TUTORIAL_VIDEOS in videos.ts IN ORDER, then applyRecordings() merges the
// generated recordings — so behavior is unchanged.
// ============================================================

import type { TutorialVideo } from './videos';

export const RAW_VIDEOS_2: TutorialVideo[] = [
  {
    id: 'sessions',
    title: 'Your session history',
    description: 'Every practice session, with its data, findings, and scores.',
    audiences: ['athlete', 'coach'],
    category: 'progress',
    duration: '2:00',
    route: '/sessions',
    script: [
      'Every session you log or import lives here, newest first.',
      'Open one to see shot-by-shot data, the issues found, the swing score, and recommended drills.',
      'Add a new session by logging it manually or importing from a launch monitor.',
      'Your session history powers everything: progress, streaks, challenges, and benchmarks.',
    ],
  },
  {
    id: 'retest',
    title: 'Retest to measure improvement',
    description: 'Re-run the same check later to prove a change actually worked.',
    audiences: ['athlete', 'coach'],
    category: 'progress',
    duration: '2:00',
    route: '/retest',
    script: [
      'A retest repeats an earlier check so you can compare apples to apples.',
      'SwingVantage shows the before and after side by side, with what moved.',
      'It’s the honest way to know whether a swing change helped — not just felt good.',
      'Set a retest reminder so you actually circle back at the right time.',
    ],
  },
  {
    id: 'milestones',
    title: 'Milestones & achievements',
    description: 'Markers for the moments that matter in your journey.',
    audiences: ['athlete', 'parent'],
    category: 'progress',
    duration: '1:30',
    route: '/milestones',
    script: [
      'Milestones celebrate real progress — your 10th session, a 7-day streak, a new personal best.',
      'They’re awarded automatically as you train, no setup needed.',
      'They’re a great motivator for kids and a simple way for parents to see effort paying off.',
      'All milestones are saved in your backup, so your history is safe.',
    ],
  },
  {
    id: 'labs',
    title: 'SwingVantage Labs',
    description: 'Early foundations: readiness, a private player model, and more.',
    audiences: ['athlete'],
    category: 'progress',
    duration: '2:00',
    route: '/labs',
    script: [
      'Labs is where new, forward-looking features live — readiness scores, a private player model, skill transfer, and benchmark mirrors.',
      'Some are early v1s, and each is honest about what it does and doesn’t yet know.',
      'They build on your Player Arc and practice history.',
      'Explore them to get a peek at where your SwingVantage is heading.',
    ],
  },
  {
    id: 'compare',
    title: 'Compare & references',
    description: 'Stack your numbers against benchmarks or your own past self.',
    audiences: ['athlete', 'coach'],
    category: 'progress',
    duration: '2:00',
    route: '/compare',
    script: [
      'Compare your metrics to benchmark data, or two of your own sessions side by side.',
      'Session-to-session comparison is perfect for checking whether a change actually helped.',
      'Benchmarks give context — where you stand and what “good” looks like at your level.',
      'Use it to settle the question: did that adjustment move the numbers, or just feel different?',
    ],
  },
  {
    id: 'benchmarks',
    title: 'Benchmarks: how you stack up',
    description: 'Reference numbers by level so you know what to aim for.',
    audiences: ['athlete', 'coach', 'team'],
    category: 'progress',
    duration: '2:00',
    route: '/benchmarks',
    script: [
      'Benchmarks show typical numbers by skill level and sport.',
      'They turn your data into context — not just “my carry is 230,” but how that compares.',
      'Use them to set realistic targets for the next few weeks.',
      'Pair benchmarks with your progress charts to aim at the right next step.',
    ],
  },

  // ── Share & Coach ─────────────────────────────────────────
  {
    id: 'reports',
    title: 'Share & coach reports',
    description: 'Turn sessions into a clean report to share with a coach.',
    audiences: ['athlete', 'coach', 'parent', 'team'],
    category: 'share',
    duration: '2:30',
    route: '/reports',
    script: [
      'Select one or more sessions and generate a report with metrics, issues, trends, and drills.',
      'Download it as a PDF or copy a summary to send to a coach.',
      'It gives whoever helps you the full context of what you’ve been working on.',
      'Reports are a simple bridge between solo practice and real coaching.',
    ],
  },
  {
    id: 'coach-summary',
    title: 'Coaching multiple athletes',
    description: 'For coaches: build per-athlete summaries and track a roster.',
    audiences: ['coach', 'team'],
    category: 'share',
    duration: '2:30',
    route: '/reports',
    script: [
      'As a coach, use reports to build a clear summary for each athlete you work with.',
      'Each summary captures the priorities, the data behind them, and the recommended drills.',
      'Share it before or after a lesson so everyone’s on the same page.',
      'It’s a lightweight way to keep a whole group moving in the same direction.',
    ],
  },
  {
    id: 'parent-summary',
    title: 'A parent’s weekly summary',
    description: 'For parents: a simple read on effort, progress, and what’s next.',
    audiences: ['parent'],
    category: 'share',
    duration: '2:00',
    route: '/dashboard',
    script: [
      'SwingVantage is built for parent-guided youth practice — encouraging and safety-first.',
      'Your dashboard and Player Arc give a simple read on effort and progress, no jargon required.',
      'Focus on the streak and the single “Today’s Fix” — consistency matters more than intensity for young athletes.',
      'Generate a report to share with a coach, or just to celebrate how far your athlete has come.',
    ],
  },

  // ── Profile & Equipment ───────────────────────────────────
  {
    id: 'profile',
    title: 'Your player profile',
    description: 'Tell SwingVantage about you so coaching fits your game.',
    audiences: 'all',
    category: 'account',
    duration: '2:00',
    route: '/profile',
    script: [
      'Your profile tunes every recommendation to you — the more you add, the better the fit.',
      'For golf: handicap, scoring average, typical miss, and skill level.',
      'For tennis, baseball, and softball: position, swing side, level, and gear.',
      'A beginner needs different feedback than an advanced player — your profile is how SwingVantage knows the difference.',
    ],
  },
  {
    id: 'equipment',
    title: 'Your equipment',
    description: 'Add clubs, bats, or rackets for more specific advice.',
    audiences: ['athlete', 'parent'],
    category: 'account',
    duration: '2:00',
    route: '/equipment',
    script: [
      'Add the gear you actually use — clubs, a bat, or a racket and string setup.',
      'For golf, lofts and carry distances let SwingVantage spot gapping issues between clubs.',
      'For bats and rackets, the specs help tailor advice to your equipment.',
      'It all saves to your backup, so you only enter it once.',
    ],
  },

  // ── Community & Motivation ────────────────────────────────
  {
    id: 'community',
    title: 'Community, XP & streaks',
    description: 'Stay motivated with experience points, streaks, and milestones.',
    audiences: ['athlete', 'parent'],
    category: 'community',
    duration: '2:30',
    route: '/community',
    script: [
      'Community turns real training into momentum: XP for sessions, streaks for showing up, badges for progress.',
      'Everything is tied to genuine effort — there are no shortcuts that skip the work.',
      'Your profile is private by default, and you choose what, if anything, to share.',
      'Youth athletes get extra privacy protections automatically.',
    ],
  },
  {
    id: 'badges',
    title: 'Badges & achievements',
    description: 'Earn badges for real milestones — and see what’s next.',
    audiences: ['athlete', 'parent'],
    category: 'community',
    duration: '1:30',
    route: '/community/badges',
    script: [
      'Badges are earned automatically when you hit a goal — first session, week-long streak, a personal best.',
      'They’re grouped by theme: consistency, improvement, sport mastery, even data protection.',
      'Locked badges show a progress bar so you can see what to chase next.',
      'They’re a fun nudge to keep the good habits going.',
    ],
  },
  {
    id: 'challenges',
    title: 'Join a challenge',
    description: 'Short, data-backed goals that keep practice interesting.',
    audiences: ['athlete', 'parent'],
    category: 'community',
    duration: '1:30',
    route: '/community/challenges',
    script: [
      'Challenges are short goals powered by your real sessions — like “5 sessions in 7 days.”',
      'Tap Join and your sessions start counting automatically.',
      'Finishing earns XP and often a badge.',
      'They’re a great way to add a little structure and fun to a practice week.',
    ],
  },
  {
    id: 'leaderboard',
    title: 'Leaderboards — fair & private',
    description: 'Ranked by improvement and consistency, not raw talent.',
    audiences: ['athlete', 'parent'],
    category: 'community',
    duration: '1:30',
    route: '/community/leaderboard',
    script: [
      'Rankings reward improvement and consistency, so beginners and pros can compete fairly.',
      'Your real name is never shown unless you choose to — you appear anonymous by default.',
      'You can opt out of leaderboards entirely in privacy settings.',
      'Youth athletes are never ranked against adults.',
    ],
  },
  {
    id: 'groups',
    title: 'Groups & clubs',
    description: 'Train alongside others who share your sport and goals.',
    audiences: ['team', 'coach'],
    category: 'community',
    duration: '2:00',
    route: '/community/groups',
    script: [
      'Join a group to train alongside athletes who share your sport.',
      'Public groups you can join instantly; private ones need an invite.',
      'Many groups run their own challenges with exclusive badges.',
      'For coaches and programs, groups are a simple home base for a roster.',
    ],
  },

  // ── Your Data & Settings ──────────────────────────────────
  {
    id: 'data-center',
    title: 'Back up & protect your data',
    description: 'Keep your progress safe and move it between devices.',
    audiences: 'all',
    category: 'data',
    duration: '2:30',
    route: '/data',
    script: [
      'SwingVantage saves your data on your device and syncs it to your account, so your progress is safe across devices.',
      'Tap Download Backup to save a complete copy: sessions, profiles, equipment, progress, and badges.',
      'You can password-protect the file. Keep that password safe — without it, an encrypted backup can’t be recovered.',
      'To restore, upload the file and preview what comes back. Use Merge to add without deleting, or Replace for a full reset.',
    ],
  },
  {
    id: 'settings',
    title: 'Settings: language, units & tone',
    description: 'Make SwingVantage yours — language, units, coaching style, privacy.',
    audiences: 'all',
    category: 'data',
    duration: '2:00',
    route: '/settings',
    script: [
      'Switch between 20 languages — the whole app updates instantly.',
      'Choose yards/feet or meters for every distance.',
      'Pick a coaching style: detailed, concise, encouraging, or balanced.',
      'Set privacy controls for what (if anything) the community can see. Your preferences travel in your backup.',
    ],
  },

  // ── Racket sports: Pickleball & Padel ─────────────────────
  {
    id: 'analyze-pickleball',
    title: 'Analyze your pickleball stroke',
    description: 'How to film and analyze a dink, third-shot drop, or drive — built for pickleball, not tennis.',
    audiences: 'all',
    category: 'analyze',
    duration: '2:10',
    route: '/video',
    journeyStage: 'capture',
    fallbackText: 'A written walkthrough for analyzing your pickleball stroke.',
    script: [
      'Pick Pickleball as your sport, then choose the shot you want to analyze (dink, third-shot drop, drive, reset, or volley).',
      'Film side-on so your paddle face, contact height, and the arc over the net are all visible — keep your full body and the kitchen line in frame.',
      'Capture a few reps of the same shot rather than mixing shots, so SwingVantage can read a consistent pattern.',
      'Upload the clip. SwingVantage checks pickleball-specific things: backswing compactness (no tennis loop), paddle-face angle, contact out front, and your footwork to the kitchen line.',
      'Read your top priority and the evidence, follow the three drills, then retest in a week.',
    ],
  },
  {
    id: 'analyze-padel',
    title: 'Analyze your padel stroke',
    description: 'How to film and analyze a bandeja, volley, or ball off the glass — built for padel, not tennis.',
    audiences: 'all',
    category: 'analyze',
    duration: '2:15',
    route: '/video',
    journeyStage: 'capture',
    fallbackText: 'A written walkthrough for analyzing your padel stroke.',
    script: [
      'Pick Padel as your sport, then choose the shot you want to analyze (bandeja, víbora, smash, volley, lob, or wall play).',
      'Film side-on so your overhead motion and contact height are visible — include a few back-glass reps so your wall read and recovery are in frame.',
      'Capture a few reps of the same shot so the pattern is clear.',
      'Upload the clip. SwingVantage checks padel-specific things: overhead control (bandeja vs. an over-hit smash), giving the ball space off the glass, contact point, lob depth, and net positioning.',
      'Read your top priority and the evidence, follow the drills, then retest in a week.',
    ],
  },
];
