// ============================================================
// PublishingOS — admin dashboard data aggregator (SERVER-ONLY)
// ------------------------------------------------------------
// Assembles everything the /admin/publishing command center renders, from REAL
// sources: the existing changelog/SEO/blog publish snapshot, the durable
// override store, the publishable-areas registry, and the audit event feed.
// No fabricated numbers — every count is derived from a real row or event.
// ============================================================

import { readPublishSnapshot, type PublishRow } from '@/lib/admin/updates-store';
import { readSeoRows, readBlogRows } from '@/lib/admin/content-publish-store';
import { classifyRisk } from './risk';
import { areaForType, PUBLISHABLE_AREAS, summarizeAreas, type PublishableArea } from './entity-registry';
import { getRecentEvents } from './service';
import { isPublishingPersistent } from './store';
import type { PublishEntityType, PublishEvent, PublishMode, RiskLevel } from './types';

const KIND_TO_ENTITY: Record<PublishRow['kind'], PublishEntityType> = {
  product: 'update',
  dev: 'dev-update',
  seo: 'seo-page',
  blog: 'blog-post',
};

export interface QueueItem {
  kind: PublishRow['kind'];
  entityType: PublishEntityType;
  id: string;
  title: string;
  date: string;
  category: string;
  published: boolean;
  risk: RiskLevel;
  publishMode: PublishMode;
  autoGenerated: boolean;
}

export interface PublishingOSStats {
  total: number;
  live: number;
  drafts: number;
  highRisk: number;
  recentlyPublished: number;
  failed: number;
}

export interface PublishingOSData {
  /** Durable DB persistence active (Supabase configured). */
  persistent: boolean;
  /** Local writable FS (file-backed publish available). */
  writable: boolean;
  /** How a publish will physically happen in THIS environment. */
  environment: 'local-file' | 'durable-db' | 'ephemeral-memory';
  stats: PublishingOSStats;
  queue: QueueItem[];
  areas: PublishableArea[];
  areasSummary: ReturnType<typeof summarizeAreas>;
  recentEvents: PublishEvent[];
}

function toQueueItem(row: PublishRow): QueueItem {
  const entityType = KIND_TO_ENTITY[row.kind];
  return {
    kind: row.kind,
    entityType,
    id: row.id,
    title: row.title,
    date: row.date,
    category: row.category,
    published: row.published,
    risk: classifyRisk(entityType, 'publish'),
    publishMode: areaForType(entityType)?.publishMode ?? 'instant',
    autoGenerated: row.autoGenerated,
  };
}

export async function getPublishingOSData(): Promise<PublishingOSData> {
  const { product, dev, writable } = readPublishSnapshot();
  const seo = readSeoRows();
  const blog = readBlogRows();

  const queue: QueueItem[] = [
    ...product.map(toQueueItem),
    ...dev.map(toQueueItem),
    ...seo.map(toQueueItem),
    ...blog.map(toQueueItem),
  ];

  const recentEvents = await getRecentEvents(25);
  const persistent = isPublishingPersistent();

  const live = queue.filter((q) => q.published).length;
  const drafts = queue.length - live;
  const highRisk = queue.filter((q) => q.risk === 'high' || q.risk === 'critical').length;
  const recentlyPublished = recentEvents.filter((e) => e.eventType === 'publish').length;
  const failed = recentEvents.filter((e) => e.toStatus === 'failed').length;

  const environment: PublishingOSData['environment'] = writable
    ? 'local-file'
    : persistent
      ? 'durable-db'
      : 'ephemeral-memory';

  return {
    persistent,
    writable,
    environment,
    stats: { total: queue.length, live, drafts, highRisk, recentlyPublished, failed },
    queue,
    areas: PUBLISHABLE_AREAS,
    areasSummary: summarizeAreas(),
    recentEvents,
  };
}
