// ============================================================
// PublishingOS — admin dashboard data aggregator (SERVER-ONLY)
// ------------------------------------------------------------
// Assembles everything the /admin/publishing command center renders, from REAL
// sources: the existing changelog/SEO/blog publish snapshot, the durable
// override store, the publishable-areas registry, and the audit event feed.
// No fabricated numbers — every count is derived from a real row or event.
// ============================================================

import { readPublishSnapshot, type PublishRow } from '@/lib/admin/updates-store';
import { readSeoRows, readBlogRows } from '@/lib/admin/content-publish-store';
import { MILESTONE_CATALOG } from '@/lib/milestones/catalog';
import { PUBLISHED_MILESTONES } from '@/content/milestones/published';
import { getTrainingItems, isTrainingPublic } from '@/lib/library/training-videos';
import { classifyRisk } from './risk';
import { areaForType, PUBLISHABLE_AREAS, summarizeAreas, type PublishableArea } from './entity-registry';
import { getRecentEvents } from './service';
import { isPublishingPersistent, listEntities, listEvents, listPublishOverrides } from './store';
import type { PublishableEntity, PublishEntityType, PublishEvent, PublishMode, RiskLevel } from './types';

const KIND_TO_ENTITY: Record<PublishRow['kind'], PublishEntityType> = {
  product: 'update',
  dev: 'dev-update',
  seo: 'seo-page',
  blog: 'blog-post',
};

/** Queue rows come from the changelog/SEO/blog stores (toggle-backed) plus the
 *  read-only inventory surfaces (milestones, library) whose publish state lives
 *  in their own store and is managed from their native admin tool. */
export type QueueKind = PublishRow['kind'] | 'milestone' | 'library';

export interface QueueItem {
  kind: QueueKind;
  entityType: PublishEntityType;
  id: string;
  title: string;
  date: string;
  category: string;
  published: boolean;
  risk: RiskLevel;
  publishMode: PublishMode;
  autoGenerated: boolean;
  /** True when this surface's publish state is NOT controlled by the durable
   *  override store — the queue shows its real state but never toggles it (the
   *  native tool owns the change). Honest: no fake control. */
  readOnly?: boolean;
  /** Where the change actually happens, for read-only rows. */
  manageHref?: string;
  manageLabel?: string;
}

/** Milestones with a committed public page (PUBLISHED_MILESTONES is the live
 *  source of truth — a page exists only once an entry is committed there). */
function milestoneQueueRows(): QueueItem[] {
  return PUBLISHED_MILESTONES.map((m) => ({
    kind: 'milestone' as const,
    entityType: 'milestone' as const,
    id: m.slug,
    title: MILESTONE_CATALOG.find((d) => d.id === m.definitionId)?.title ?? m.verifiedMetric,
    date: m.achievedAt,
    category: 'Milestone',
    published: true, // committed to published.ts == a live public page
    risk: classifyRisk('milestone', 'publish'),
    publishMode: areaForType('milestone')?.publishMode ?? 'instant',
    autoGenerated: false,
    readOnly: true,
    manageHref: '/admin/milestones',
    manageLabel: 'Milestone Center',
  }));
}

/** Training videos and their EFFECTIVE public state (override-aware via the
 *  library's own store). Read-only here; flips happen in Library Publishing. */
function libraryQueueRows(): QueueItem[] {
  return getTrainingItems().map((v) => ({
    kind: 'library' as const,
    entityType: 'library-video' as const,
    id: v.id,
    title: v.title,
    date: '',
    category: v.category,
    published: isTrainingPublic(v.id),
    risk: classifyRisk('library-video', 'publish'),
    publishMode: areaForType('library-video')?.publishMode ?? 'instant',
    autoGenerated: false,
    readOnly: true,
    manageHref: '/admin/library',
    manageLabel: 'Library Publishing',
  }));
}

export interface PublishingOSStats {
  total: number;
  live: number;
  drafts: number;
  highRisk: number;
  recentlyPublished: number;
  failed: number;
}

export interface PublishingOSData {
  /** Durable DB persistence active (Supabase configured). */
  persistent: boolean;
  /** Local writable FS (file-backed publish available). */
  writable: boolean;
  /** How a publish will physically happen in THIS environment. */
  environment: 'local-file' | 'durable-db' | 'ephemeral-memory';
  stats: PublishingOSStats;
  queue: QueueItem[];
  areas: PublishableArea[];
  areasSummary: ReturnType<typeof summarizeAreas>;
  recentEvents: PublishEvent[];
  /** Durable entity snapshots keyed by `${entityType}:${entityId}` — powers the
   *  per-item detail drawer (lifecycle/version). Only populated entities exist
   *  (an entity is created on its first publish decision), so this stays small. */
  entities: Record<string, PublishableEntity>;
  /** This-entity audit events keyed by the same entity key (newest-first). */
  eventsByEntity: Record<string, PublishEvent[]>;
}

function toQueueItem(row: PublishRow): QueueItem {
  const entityType = KIND_TO_ENTITY[row.kind];
  return {
    kind: row.kind,
    entityType,
    id: row.id,
    title: row.title,
    date: row.date,
    category: row.category,
    published: row.published,
    risk: classifyRisk(entityType, 'publish'),
    publishMode: areaForType(entityType)?.publishMode ?? 'instant',
    autoGenerated: row.autoGenerated,
  };
}

export async function getPublishingOSData(): Promise<PublishingOSData> {
  const { product, dev, writable } = readPublishSnapshot();
  const seo = readSeoRows();
  const blog = readBlogRows();

  const queue: QueueItem[] = [
    ...product.map(toQueueItem),
    ...dev.map(toQueueItem),
    ...seo.map(toQueueItem),
    ...blog.map(toQueueItem),
  ];

  // In production the runtime FS is read-only, so a publish is recorded as a
  // durable OVERRIDE (the public read path honours it) rather than a file edit.
  // The base rows above therefore still read "draft" — merge the overrides in so
  // the admin queue reflects the EFFECTIVE state, matching what the public sees.
  // Additive: with no overrides the queue is unchanged.
  const overrideRows = await listPublishOverrides();
  if (overrideRows.length > 0) {
    const ov: Partial<Record<PublishEntityType, Record<string, boolean>>> = {};
    for (const o of overrideRows) (ov[o.entityType] ??= {})[o.entityId] = o.published;
    for (const item of queue) {
      const o = ov[item.entityType]?.[item.id];
      if (o !== undefined) item.published = o;
    }
  }

  // Read-only inventory: milestone pages + training videos. They surface in the
  // queue with their REAL published state for a complete picture, but their
  // toggle lives in the native tool (commit to published.ts / Library
  // Publishing) — the override store above does not control them, so they are
  // never falsely toggled here. Appended after the override merge by design.
  queue.push(...milestoneQueueRows(), ...libraryQueueRows());

  const recentEvents = await getRecentEvents(25);
  const persistent = isPublishingPersistent();

  // Per-entity snapshots + audit history for the detail drawer. Two store reads
  // total, grouped in memory — no per-item round-trips.
  const allEntities = await listEntities();
  const allEvents = await listEvents();
  const entities: Record<string, PublishableEntity> = {};
  for (const e of allEntities) entities[e.id] = e;
  const eventsByEntity: Record<string, PublishEvent[]> = {};
  for (const ev of allEvents) {
    (eventsByEntity[ev.publishableEntityId] ??= []).push(ev);
  }

  const live = queue.filter((q) => q.published).length;
  const drafts = queue.length - live;
  const highRisk = queue.filter((q) => q.risk === 'high' || q.risk === 'critical').length;
  const recentlyPublished = recentEvents.filter((e) => e.eventType === 'publish').length;
  const failed = recentEvents.filter((e) => e.toStatus === 'failed').length;

  const environment: PublishingOSData['environment'] = writable
    ? 'local-file'
    : persistent
      ? 'durable-db'
      : 'ephemeral-memory';

  return {
    persistent,
    writable,
    environment,
    stats: { total: queue.length, live, drafts, highRisk, recentlyPublished, failed },
    queue,
    areas: PUBLISHABLE_AREAS,
    areasSummary: summarizeAreas(),
    recentEvents,
    entities,
    eventsByEntity,
  };
}
