'use client';

// Action Reports library: compact list with type/tier filters, search, storage
// tier + linked-task indicators. Each row links to the report detail.

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { StatusBadge } from '@/components/admin/StatusBadge';
import { EmptyState } from '@/components/ui/EmptyState';
import type { ActionReport, RetentionTier } from '@/lib/intelligence-os/types';

const TIER_TONE: Record<RetentionTier, 'routine' | 'watch' | 'neutral'> = {
  hot: 'routine', warm: 'watch', cold: 'neutral',
};

export function ReportsBrowser({ initial }: { initial: ActionReport[] }) {
  const [q, setQ] = useState('');
  const [tier, setTier] = useState<'all' | RetentionTier>('all');

  const rows = useMemo(() => {
    let r = initial;
    if (tier !== 'all') r = r.filter((x) => x.retentionTier === tier);
    const term = q.trim().toLowerCase();
    if (term) r = r.filter((x) => x.searchMetadata.includes(term) || x.executiveSummary.toLowerCase().includes(term));
    return r;
  }, [initial, tier, q]);

  if (initial.length === 0) {
    return <EmptyState title="No reports yet" description="Reports (system health, AI quality, upload reliability, SEO, UX, revenue, …) are generated by audits or created manually. Each is deduped, retention-tiered (hot → warm → cold), and can generate Action Tasks that link back." />;
  }

  const TIERS: Array<['all' | RetentionTier, string]> = [['all', 'All'], ['hot', 'Hot'], ['warm', 'Warm'], ['cold', 'Cold']];

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        {TIERS.map(([key, label]) => (
          <button
            key={key}
            onClick={() => setTier(key)}
            className={`rounded-full border px-3 py-1 text-xs font-medium transition-colors ${
              tier === key ? 'border-primary/40 bg-primary/10 text-link' : 'border-border text-muted-foreground hover:text-foreground'
            }`}
          >
            {label}
          </button>
        ))}
        <input
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder="Search reports…"
          className="ml-auto w-full max-w-xs rounded-lg border border-border bg-background px-3 py-1.5 text-sm text-foreground outline-none focus:border-ring"
        />
      </div>

      {rows.length === 0 ? (
        <p className="py-8 text-center text-sm text-muted-foreground">No reports match this filter.</p>
      ) : (
        <ul className="space-y-2">
          {rows.map((r) => (
            <li key={r.id}>
              <Link href={`/admin/intelligence-os/reports/${r.id}`} className="block rounded-lg border border-border p-3 text-sm transition-colors hover:border-primary/40 hover:bg-card/60">
                <div className="flex flex-wrap items-center gap-2">
                  <StatusBadge tone={TIER_TONE[r.retentionTier]}>{r.retentionTier}</StatusBadge>
                  <span className="font-medium text-foreground">{r.title}</span>
                  <span className="text-xs text-muted-foreground">{r.type} · {r.lifecycleStatus}</span>
                  <span className="ml-auto text-xs text-muted-foreground">{r.findings.length} finding(s) · {r.generatedTaskIds.length} task(s)</span>
                </div>
                {r.executiveSummary && <p className="mt-1 line-clamp-1 text-muted-foreground">{r.executiveSummary}</p>}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
