// Regression: in production (read-only FS) a publish is recorded as a durable
// override, not a base-row edit. The admin PublishingOS queue must reflect that
// EFFECTIVE state — otherwise a published item keeps showing as unpublished.

jest.mock('@/lib/admin/updates-store', () => ({
  readPublishSnapshot: () => ({
    product: [
      { kind: 'product', id: 'u1', title: 'Update One', date: '2026-01-01', category: 'general', published: false, autoGenerated: false },
    ],
    dev: [],
    writable: false,
  }),
}));

jest.mock('@/lib/admin/content-publish-store', () => ({
  readSeoRows: () => [],
  readBlogRows: () => [],
}));

import { getPublishingOSData } from '../admin-data.server';
import { setPublishOverride, __resetMemoryStore } from '../store';

beforeEach(() => __resetMemoryStore());

describe('PublishingOS admin queue — effective publish state', () => {
  it('reflects a durable override (the production publish path)', async () => {
    await setPublishOverride('update', 'u1', true, 'admin@example.com');

    const data = await getPublishingOSData();
    const item = data.queue.find((q) => q.id === 'u1');

    expect(item?.published).toBe(true); // was showing false (base row) before the fix
    expect(data.stats.live).toBe(1);
    expect(data.stats.drafts).toBe(0);
  });

  it('leaves the base state untouched when there is no override (additive)', async () => {
    const data = await getPublishingOSData();
    expect(data.queue.find((q) => q.id === 'u1')?.published).toBe(false);
    expect(data.stats.live).toBe(0);
  });

  it('an unpublish override pulls a live base row back to draft', async () => {
    await setPublishOverride('update', 'u1', false, 'admin@example.com');
    const data = await getPublishingOSData();
    expect(data.queue.find((q) => q.id === 'u1')?.published).toBe(false);
  });
});
