// SwingVantage Academy — Knowledge-check quizzes (seed content).
import type { Quiz } from '../types';

export const QUIZZES: Quiz[] = [
  {
    id: 'q-what-is', title: 'What SwingVantage Is — Knowledge Check', passingScore: 70, shuffle: true,
    questions: [
      { id: 'q-what-is-1', kind: 'multiple-choice',
        prompt: 'Which sports does SwingVantage support today?',
        options: [
          'Golf only',
          'Golf, tennis, baseball, slow-pitch softball, and fast-pitch softball',
          'Every sport with a swing',
          'Golf and tennis only',
        ],
        correct: [1],
        explanation: 'SwingVantage is multi-sport: golf, tennis, baseball, slow-pitch and fast-pitch softball.' },
      { id: 'q-what-is-2', kind: 'true-false',
        prompt: 'SwingVantage requires a paid account before a user can analyze a swing.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'No — the product is try-first. Users can analyze without an account; signing in then saves and syncs progress to their private account.' },
      { id: 'q-what-is-3', kind: 'multiple-choice',
        prompt: 'How should we describe SwingVantage results to a new user?',
        options: [
          'Lab-grade, medically precise measurements',
          'Guaranteed improvement in a set number of weeks',
          'Confident, data-backed coaching estimates that sharpen as more data is added',
          'Opinions with no basis',
        ],
        correct: [2],
        explanation: 'We are confident but honest: results are data-backed estimates labeled with confidence, not lab/medical measurements or guarantees.' },
    ],
  },
  {
    id: 'q-personas', title: 'Core User Personas — Knowledge Check', passingScore: 70,
    questions: [
      { id: 'q-personas-1', kind: 'multi-select',
        prompt: 'Which of these are primary SwingVantage personas? (Select all that apply.)',
        options: ['Individual athlete', 'Parent of a young athlete', 'Coach', 'Hospital radiologist'],
        correct: [0, 1, 2],
        explanation: 'Athletes, parents, and coaches are core personas. SwingVantage is not a medical tool.' },
      { id: 'q-personas-2', kind: 'multiple-choice',
        prompt: 'A parent setting up SwingVantage for a 12-year-old cares MOST about…',
        options: ['Tour-level biomechanics jargon', 'Simple guidance, safety, and privacy', 'Leaderboards against strangers', 'Raw data exports'],
        correct: [1],
        explanation: 'Parent flows should stay parent-oriented: plain guidance, youth safety, and privacy.' },
    ],
  },
  {
    id: 'q-responsible-ai', title: 'Responsible AI & User Trust — Knowledge Check', passingScore: 80,
    questions: [
      { id: 'q-rai-1', kind: 'multiple-choice',
        prompt: 'A user asks "Will this fix my shoulder pain?" The right response is to…',
        options: [
          'Promise the drills will heal the injury',
          'Diagnose the injury from the swing video',
          'Avoid medical claims and suggest consulting a qualified professional',
          'Ignore the question',
        ],
        correct: [2],
        explanation: 'Never make medical or injury claims. Redirect to a qualified professional; SwingVantage is a performance tool, not a medical device.' },
      { id: 'q-rai-2', kind: 'multi-select',
        prompt: 'Which statements are SAFE to make about AI feedback? (Select all that apply.)',
        options: [
          '"This is a data-backed estimate, labeled with a confidence level."',
          '"This is a guaranteed diagnosis of exactly what is wrong."',
          '"It works best alongside a qualified coach."',
          '"It replaces the need for any coach or doctor."',
        ],
        correct: [0, 2],
        explanation: 'Confident-but-honest framing and "pairs with a coach" are safe. Guarantees and "replaces professionals" are not.' },
      { id: 'q-rai-3', kind: 'true-false',
        prompt: 'It is fine to publish AI-generated training content without human review.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'AI-generated content must be human-reviewed before publishing — a core Academy guardrail.' },
    ],
  },
  {
    id: 'q-upload', title: 'Uploading a Swing Video — Knowledge Check', passingScore: 70,
    questions: [
      { id: 'q-upload-1', kind: 'multiple-choice',
        prompt: 'What is the most common cause of a poor or failed swing analysis?',
        options: ['The user’s phone is too new', 'A bad camera angle or partially out-of-frame swing', 'Using Wi-Fi instead of cellular', 'Recording in color'],
        correct: [1],
        explanation: 'Framing/angle is the #1 issue. Coach users to keep the whole body and swing in frame from the recommended angle.' },
      { id: 'q-upload-2', kind: 'true-false',
        prompt: 'When AI video analysis runs, the user’s full video is uploaded to our servers.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'The full video stays on the device; only a small sample of the swing is sent for analysis. This is a real privacy feature — state it accurately.' },
      { id: 'q-upload-3', kind: 'multi-select',
        prompt: 'Good camera guidance includes… (Select all that apply.)',
        options: ['Steady camera / tripod', 'Whole body in frame', 'Film into a bright light behind the athlete', 'Recommended angle for the sport'],
        correct: [0, 1, 3],
        explanation: 'Steady, full-body, correct angle, good lighting (light on the athlete, not behind). Backlighting hurts analysis.' },
    ],
  },
  {
    id: 'q-explain-feedback', title: 'Explaining AI Feedback — Knowledge Check', passingScore: 75,
    questions: [
      { id: 'q-ef-1', kind: 'multiple-choice',
        prompt: 'A beginner is overwhelmed by their results. Best first move?',
        options: ['List every metric in order', 'Lead with the single highest-priority fix and one drill', 'Tell them to hire a coach', 'Explain kinematic sequencing in detail'],
        correct: [1],
        explanation: 'Lead with one priority + one action. SwingVantage is designed to prioritize, not overwhelm.' },
      { id: 'q-ef-2', kind: 'multiple-choice',
        prompt: 'How should confidence levels be framed?',
        options: ['Hide them — they confuse people', 'As proof the AI is uncertain and unreliable', 'As an honest signal that sharpens with more/better data', 'As a guarantee'],
        correct: [2],
        explanation: 'Confidence is an honesty feature: low with thin input, higher with measured data and more sessions.' },
    ],
  },
  {
    id: 'q-3d', title: '3D Motion Mapping — Knowledge Check', passingScore: 75,
    questions: [
      { id: 'q-3d-1', kind: 'multiple-choice',
        prompt: 'What does 3D motion mapping do?',
        options: [
          'Provides certified medical biomechanics',
          'Estimates body movement and sequencing to give visual, sport-specific insight',
          'Guarantees a swing speed increase',
          'Replaces a launch monitor',
        ],
        correct: [1],
        explanation: 'It estimates movement/sequencing for insight — not certified biomechanics or guarantees.' },
      { id: 'q-3d-2', kind: 'true-false',
        prompt: 'It is accurate to tell a parent that 3D motion mapping is a medical-grade injury scan.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'Never. It is a performance-insight estimate, not a medical or injury-diagnostic tool.' },
    ],
  },
  {
    id: 'q-support-triage', title: 'Support Triage — Knowledge Check', passingScore: 75,
    questions: [
      { id: 'q-st-1', kind: 'multiple-choice',
        prompt: 'A user says "the analysis looks wrong." First troubleshooting step?',
        options: ['Issue a refund', 'Escalate to engineering immediately', 'Check the input: camera angle, framing, and lighting of the uploaded swing', 'Tell them the AI is always right'],
        correct: [2],
        explanation: 'Most "wrong analysis" reports trace to input quality. Check the video first before escalating.' },
      { id: 'q-st-2', kind: 'multiple-choice',
        prompt: 'When should you escalate instead of resolving directly?',
        options: ['Whenever a user is mildly annoyed', 'For confirmed bugs, data/privacy issues, or anything outside documented playbooks', 'Never', 'Only on weekends'],
        correct: [1],
        explanation: 'Escalate confirmed bugs, data/privacy/security, or anything not covered by a playbook.' },
    ],
  },
  {
    id: 'q-sales-position', title: 'Product Positioning — Knowledge Check', passingScore: 75,
    questions: [
      { id: 'q-sp-1', kind: 'multiple-choice',
        prompt: 'The cleanest one-line positioning for SwingVantage is…',
        options: [
          '"A medical device for swing injuries"',
          '"An AI swing-performance coach across golf, tennis, baseball and softball that tells you the one thing to work on next"',
          '"A social network for athletes"',
          '"A video storage app"',
        ],
        correct: [1],
        explanation: 'Lead with the multi-sport AI coaching value and the "one priority next" promise.' },
      { id: 'q-sp-2', kind: 'multi-select',
        prompt: 'Strong differentiators to mention? (Select all that apply.)',
        options: ['Multi-sport in one app', 'Prioritized, honest coaching (one fix at a time)', 'Privacy: your video stays on your device', 'Guaranteed pro-level results'],
        correct: [0, 1, 2],
        explanation: 'Multi-sport, honest prioritization, and privacy are real differentiators. Never guarantee results.' },
    ],
  },
  {
    id: 'q-admin-basics', title: 'Admin & Security Basics — Knowledge Check', passingScore: 80,
    questions: [
      { id: 'q-ab-1', kind: 'multiple-choice',
        prompt: 'Internal admin tools (incl. this Academy) are protected by…',
        options: ['Nothing', 'A public link', 'A server-side guard (ADMIN_SECRET) and noindex; not exposed publicly', 'Only client-side hiding'],
        correct: [2],
        explanation: 'Admin routes are server-guarded and noindex — never rely on client-side hiding for security.' },
      { id: 'q-ab-2', kind: 'true-false',
        prompt: 'Secret keys (service-role, DB password) may be pasted into chats or committed to the repo.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'Never. Secrets stay in env/secret stores; if exposed, rotate them immediately.' },
    ],
  },
  {
    id: 'q-coach-final', title: 'Coach Mode Certification — Final Assessment', passingScore: 80, shuffle: true,
    questions: [
      { id: 'q-cf-1', kind: 'multiple-choice',
        prompt: 'In Coach Mode, the best way to give a player feedback is to…',
        options: ['Send all metrics at once', 'Assign one priority fix plus a drill, then track the retest', 'Only talk in person', 'Compare them publicly to others'],
        correct: [1],
        explanation: 'Coach the priority + drill + retest loop; keep it supportive and private.' },
      { id: 'q-cf-2', kind: 'multiple-choice',
        prompt: 'A parent asks how their child compares to others. You should…',
        options: ['Share a public leaderboard of minors', 'Focus on the child’s own progress over time, respecting youth privacy', 'Refuse to talk to parents', 'Guarantee a scholarship'],
        correct: [1],
        explanation: 'Keep youth data private; frame around the athlete’s own progress, never public comparison or guarantees.' },
      { id: 'q-cf-3', kind: 'multi-select',
        prompt: 'Healthy coaching habits in the product include… (Select all.)',
        options: ['Avoiding overcorrection', 'Escalating to a human/pro when needed', 'Stacking five fixes at once', 'Honest confidence framing'],
        correct: [0, 1, 3],
        explanation: 'One fix at a time, escalate when appropriate, frame confidence honestly. Don’t stack fixes.' },
    ],
  },
  {
    id: 'q-support-final', title: 'Support Specialist — Final Assessment', passingScore: 80, shuffle: true,
    questions: [
      { id: 'q-suf-1', kind: 'multiple-choice',
        prompt: 'Top first check for a "bad analysis" ticket?',
        options: ['Refund', 'Input quality (angle/framing/lighting)', 'Reinstall the OS', 'Blame the user'],
        correct: [1],
        explanation: 'Input quality first — it resolves the majority of these tickets.' },
      { id: 'q-suf-2', kind: 'multiple-choice',
        prompt: 'A user can’t find their data after switching phones. The likely fix?',
        options: ['Tell them it’s gone', 'Confirm they’re signed in to the same account so cloud sync restores it (or restore from a backup file)', 'Issue a refund', 'Escalate to legal'],
        correct: [1],
        explanation: 'Signed-in data syncs to the account across devices; otherwise Backup & Restore. Know the hybrid storage model.' },
      { id: 'q-suf-3', kind: 'true-false',
        prompt: 'You should promise AI accuracy to calm an upset user.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'Never overpromise AI accuracy. Stay honest; fix the input or escalate.' },
    ],
  },
  {
    id: 'q-sales-final', title: 'Sales Demo — Final Assessment', passingScore: 80, shuffle: true,
    questions: [
      { id: 'q-saf-1', kind: 'multiple-choice',
        prompt: 'Best demo opener for a coach persona?',
        options: ['Open the pricing page', 'Show the coach dashboard and the one-priority feedback loop on a real swing', 'Read the privacy policy', 'List every feature'],
        correct: [1],
        explanation: 'Lead with the coach’s job-to-be-done: manage players + give one clear fix, shown live.' },
      { id: 'q-saf-2', kind: 'multiple-choice',
        prompt: 'Objection: "Isn’t this just a video app?" Best reply?',
        options: ['Agree', 'Differentiate: multi-sport AI coaching that prioritizes the next fix, with privacy and progress tracking', 'Offer a discount', 'End the call'],
        correct: [1],
        explanation: 'Reframe to the differentiated value, not storage.' },
    ],
  },
  {
    id: 'q-ai-coaching', title: 'AI Coaching Engine — Knowledge Check', passingScore: 80, shuffle: true,
    questions: [
      { id: 'q-aic-1', kind: 'multiple-choice',
        prompt: 'How are drill recommendations generated?',
        options: ['Randomly', 'Matched to the diagnosed priority issue using sport-specific logic', 'By popularity only', 'By the user’s mood'],
        correct: [1],
        explanation: 'Drills map to the single diagnosed priority issue, using sport-specific coaching logic.' },
      { id: 'q-aic-2', kind: 'multiple-choice',
        prompt: 'When should the AI defer to a human coach or professional?',
        options: ['Never', 'For pain/injury or needs beyond its confidence', 'Always', 'Only for pros'],
        correct: [1],
        explanation: 'Escalate to a human for pain/injury or anything beyond the AI’s confidence — never make medical claims.' },
      { id: 'q-aic-3', kind: 'true-false',
        prompt: 'Stacking many fixes at once produces faster improvement.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'One fix at a time. Overcorrection slows progress and overwhelms the athlete.' },
    ],
  },
  {
    id: 'q-qa', title: 'Product QA — Knowledge Check', passingScore: 80, shuffle: true,
    questions: [
      { id: 'q-qa-1', kind: 'multiple-choice',
        prompt: 'A solid QA test case for video upload includes…',
        options: ['Only the happy path', 'Happy path PLUS bad-angle, backlit, and partial-frame edge cases', 'Nothing in particular', 'Random taps'],
        correct: [1],
        explanation: 'Test the realistic failure modes (angle/lighting/framing), not just the happy path.' },
      { id: 'q-qa-2', kind: 'multi-select',
        prompt: 'When validating AI output, QA should confirm it… (Select all.)',
        options: ['Leads with one priority', 'Labels a confidence level', 'Avoids medical/guarantee claims', 'Is always the longest possible response'],
        correct: [0, 1, 2],
        explanation: 'One priority, honest confidence, and no medical/guarantee claims — length is irrelevant.' },
      { id: 'q-qa-3', kind: 'true-false',
        prompt: 'Accessibility and mobile-web testing are out of scope for QA.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'Accessibility and mobile-first behavior are in scope — the product is mobile-first.' },
    ],
  },
  {
    id: 'q-marketing', title: 'Marketing Enablement — Knowledge Check', passingScore: 80, shuffle: true,
    questions: [
      { id: 'q-mk-1', kind: 'multiple-choice',
        prompt: 'SwingVantage brand voice is best described as…',
        options: ['Hype and overpromise', 'Confident, honest, plain-language — no guarantees', 'Dense technical jargon', 'Negative about competitors'],
        correct: [1],
        explanation: 'Confident but honest, plain-language, no guarantees — honesty is a brand asset.' },
      { id: 'q-mk-2', kind: 'multi-select',
        prompt: 'Which performance claims are acceptable in marketing? (Select all.)',
        options: ['"Data-backed estimates that sharpen with more data"', '"Pairs with a qualified coach"', '"Guaranteed pro-level results"', '"Cures swing flaws and injuries"'],
        correct: [0, 1],
        explanation: 'Estimate framing and coach-pairing are fine. Guarantees and medical/injury claims are never allowed.' },
      { id: 'q-mk-3', kind: 'true-false',
        prompt: 'Marketing may publish a performance or medical guarantee if it boosts conversion.',
        options: ['True', 'False'],
        correct: [1],
        explanation: 'Never. No guaranteed outcomes and no medical claims, regardless of conversion impact.' },
    ],
  },
  {
    id: 'q-exec', title: 'Executive Fluency — Knowledge Check', passingScore: 75,
    questions: [
      { id: 'q-ex-1', kind: 'multiple-choice',
        prompt: 'What is SwingVantage’s current go-to-market priority order?',
        options: ['Monetize subscriptions first', 'Grow free users → ads (first revenue) → membership tiers', 'Ads only', 'Charge before launch'],
        correct: [1],
        explanation: 'Grow free users first, then ads as first revenue, then membership tiers. Subscriptions are later, not next.' },
      { id: 'q-ex-2', kind: 'multiple-choice',
        prompt: 'The most durable competitive moat is…',
        options: ['Having the most features', 'Honest, prioritized AI coaching + multi-sport + privacy + a growing base of the athlete’s own progress data', 'The lowest price', 'The biggest ad budget'],
        correct: [1],
        explanation: 'Honesty, prioritization, multi-sport breadth, privacy, and accumulated personal progress data are hard to copy.' },
    ],
  },
];
