// ============================================================
// SwingIQ — Slow Pitch Softball Drill Library
// All YouTube links are SEARCH LINKS only — never hardcoded.
// ============================================================

import type { SportDrillRecommendation } from '../types';

function ytSearch(query: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
}

export const SLOW_PITCH_DRILLS: SportDrillRecommendation[] = [
  {
    id: 'sp_arc_contact_tee',
    sport_id: 'softball_slow',
    issue_id: 'dropping_back_shoulder',
    phase: 'contact_arc',
    name: 'High-Tee Arc Contact Drill',
    goal: 'Train contact on a descending arc ball with slight upward bat angle',
    steps: [
      'Set batting tee at shoulder height — mimicking the high arc of a slow pitch',
      'Practice hitting through the ball at this high contact point',
      'Focus on matching the ball\'s downward trajectory at contact',
      'Drive the ball at a low outfield line-drive trajectory, not straight up',
      'Vary tee heights (shoulder → belt) to simulate different pitch arcs',
    ],
    reps_or_duration: '4 sets of 15 per tee height',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, adjustable batting tee, balls',
    safety_note: null,
    youtube_search_query: 'slow pitch softball batting tee high contact arc drill',
    youtube_search_url: ytSearch('slow pitch softball batting tee high contact arc drill'),
    coach_channel_hint: 'Softball Spot',
    focus_feel: 'Contact feels like driving through the top of a tennis ball — firm and through.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },
  {
    id: 'sp_hip_rotation_step',
    sport_id: 'softball_slow',
    issue_id: 'no_hip_drive_soft',
    phase: 'hip_fire',
    name: 'Step-and-Fire Hip Rotation Drill',
    goal: 'Establish hip rotation as the power source, not the arms',
    steps: [
      'Start with your weight loaded on the back foot',
      'Step forward with the front foot and immediately fire the hips open',
      'Arms follow — do NOT swing the arms first',
      'Hold the finish: belt buckle must face the pitcher',
      'Repeat 10 times without a ball, then add tee work',
    ],
    reps_or_duration: '3 sets of 15 — hold finish 2 seconds',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat',
    safety_note: null,
    youtube_search_query: 'slow pitch softball hip rotation drill power hitting',
    youtube_search_url: ytSearch('slow pitch softball hip rotation drill power hitting'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Hips drag the arms through — not the other way around.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },
  {
    id: 'sp_stay_back_soft',
    sport_id: 'softball_slow',
    issue_id: 'lunging_forward',
    phase: 'stride',
    name: 'Patience Drill — Watch It Drop',
    goal: 'Train patience on the slow pitch arc — do not commit weight until ball drops into zone',
    steps: [
      'Have a partner lob slow-pitch style tosses from 30 feet',
      'Your only job: do NOT swing until the ball drops below the peak of its arc',
      'Watch the ball arc and peak — only begin load as it starts down',
      'Practice soft, late weight transfer to avoid lunging',
      'Start with just observing (no swing), then progress to contact',
    ],
    reps_or_duration: '3 sets of 20 pitches — call out "now" when you start load',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, partner, softballs',
    safety_note: null,
    youtube_search_query: 'slow pitch softball patience drill timing arc pitch',
    youtube_search_url: ytSearch('slow pitch softball patience drill timing arc pitch'),
    coach_channel_hint: 'Softball Tutor',
    focus_feel: 'Wait, wait, wait — then fire.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },
  {
    id: 'sp_follow_through_full',
    sport_id: 'softball_slow',
    issue_id: 'arm_short_follow',
    phase: 'follow_through',
    name: 'Full Finish Pose Hold',
    goal: 'Reinforce complete follow-through to proper high finish',
    steps: [
      'After each swing (on tee or live), hold your finish position for 3 seconds',
      'Bat should be over your front shoulder, weight on front foot',
      'Take a photo or have a partner check your finish',
      'If you can\'t hold the finish steadily, you stopped the swing too early',
    ],
    reps_or_duration: '3 sets of 12 — 3-second holds',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee',
    safety_note: null,
    youtube_search_query: 'slow pitch softball follow through finish high drill',
    youtube_search_url: ytSearch('slow pitch softball follow through finish high drill'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Bat over the shoulder, weight forward, face the pitcher.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },
  {
    id: 'sp_opposite_field_tee',
    sport_id: 'softball_slow',
    issue_id: 'early_shoulder_pull',
    phase: 'hip_fire',
    name: 'Opposite Field Tee Drill',
    goal: 'Eliminate early shoulder opening by training opposite-field contact',
    steps: [
      'Set tee deep in the contact zone (back half of plate)',
      'Drive the ball to the opposite field gap',
      'Front shoulder must stay closed until hips clear — only then release',
      'Opposite-field contact forces hips to lead and shoulders to stay back',
    ],
    reps_or_duration: '3 sets of 15 opposite-field contact swings',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, tee, balls',
    safety_note: null,
    youtube_search_query: 'slow pitch softball opposite field drill shoulder stay closed',
    youtube_search_url: ytSearch('slow pitch softball opposite field drill shoulder stay closed'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Keep the shoulder in — drive the outside pitch the other way.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Stance Setup ─────────────────────────────────────────
  {
    id: 'sp_stance_groove',
    sport_id: 'softball_slow',
    issue_id: 'sp_poor_stance_setup',
    phase: 'load',
    name: 'Stance Setup Routine Drill',
    goal: 'Build a consistent, balanced stance before every pitch',
    steps: [
      'Stand in front of a mirror in full batting stance',
      'Check feet: shoulder-width, slight toe-in, weight even 50/50',
      'Check knees: soft flex — neither locked nor overly bent',
      'Check posture: slight forward tilt at hips, spine neutral',
      'Repeat 20 times until the feeling is automatic',
    ],
    reps_or_duration: '20 setup reps before every batting practice session',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, mirror optional',
    safety_note: null,
    youtube_search_query: 'slow pitch softball stance setup drill balanced position',
    youtube_search_url: ytSearch('slow pitch softball stance setup drill balanced position'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Comfortable, balanced, ready — athletic position waiting for the arc.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Pitch Tracking ───────────────────────────────────────
  {
    id: 'sp_arc_tracking_drill',
    sport_id: 'softball_slow',
    issue_id: 'sp_poor_pitch_tracking',
    phase: 'load',
    name: 'Arc Peak Identification Drill',
    goal: 'Build the habit of visually tracking the full arc — especially the peak',
    steps: [
      'Have a partner throw slow-pitch arcs — do NOT swing',
      'Your only job: call out "peak!" when the ball reaches the top of its arc',
      'Repeat 20 tosses calling the peak each time',
      'After 20, begin tracking peak AND descent: call "peak — drop — now!"',
      'Add the swing trigger only when the ball begins descending',
    ],
    reps_or_duration: '3 sets of 20 arc-tracking calls before adding swing',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Softballs, partner',
    safety_note: null,
    youtube_search_query: 'slow pitch softball arc tracking drill timing peak',
    youtube_search_url: ytSearch('slow pitch softball arc tracking drill timing peak'),
    coach_channel_hint: 'Softball Tutor',
    focus_feel: 'See the arc all the way. The peak is your trigger — then load, then fire.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Mistimed Load Arc ─────────────────────────────────────────
  {
    id: 'sp_load_delay_drill',
    sport_id: 'softball_slow',
    issue_id: 'sp_mistimed_load_arc',
    phase: 'load',
    name: 'Peak-Triggered Load Drill',
    goal: 'Delay the load until the ball reaches the peak of the arc',
    steps: [
      'Partner throws slow pitch arcs — you wait motionless until the ball peaks',
      'Only begin weight shift onto back foot as the ball starts descending',
      'Partner calls "peak!" as a cue during early reps to train the trigger',
      'Practice 15 reps where you delay load until the verbal cue',
      'Progress: remove verbal cue and self-trigger on visual peak recognition',
    ],
    reps_or_duration: '3 sets of 15 peak-triggered loads',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, softballs, partner',
    safety_note: null,
    youtube_search_query: 'slow pitch softball load timing delay arc pitch trigger',
    youtube_search_url: ytSearch('slow pitch softball load timing delay arc pitch trigger'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Be patient — the arc is slow. Load only when the ball starts coming down.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Weight Transfer ──────────────────────────────────────
  {
    id: 'sp_rock_and_fire_drill',
    sport_id: 'softball_slow',
    issue_id: 'sp_poor_weight_transfer',
    phase: 'stride',
    name: 'Rock and Fire Weight Transfer Drill',
    goal: 'Establish smooth back-to-front weight transfer in the slow pitch swing',
    steps: [
      'Stand in batting stance — rock weight slowly onto back foot (load)',
      'Then rock forward onto front foot (stride landing) as you fire hips',
      'Practice the rock-and-fire motion 10 times without a ball',
      'Add a tee: rock back, rock forward, fire hips, contact',
      'Feel the momentum transfer — not a sudden shift, but a flowing rock',
    ],
    reps_or_duration: '3 sets of 15 rock-and-fire tee swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee',
    safety_note: null,
    youtube_search_query: 'slow pitch softball weight transfer drill rock and fire',
    youtube_search_url: ytSearch('slow pitch softball weight transfer drill rock and fire'),
    coach_channel_hint: 'Softball Spot',
    focus_feel: 'Rock back, rock forward — a smooth wave of weight, not a fall.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Long Looping Swing ────────────────────────────────────────
  {
    id: 'sp_inside_knob_drill',
    sport_id: 'softball_slow',
    issue_id: 'sp_long_looping_swing',
    phase: 'hip_fire',
    name: 'Inside Knob Drill',
    goal: 'Eliminate the loop by training knob-first, inside-the-ball path',
    steps: [
      'Set tee at belt height in the center of the plate',
      'Swing with the intent of driving the knob of the bat to the ball first',
      'The barrel arrives last — drag the barrel behind your hands',
      'Feel hands close to the body — no barrel drop',
      'Progress to two-tee setup: back tee at contact, front tee 6 inches in front',
    ],
    reps_or_duration: '3 sets of 20 tee swings focusing on knob-first',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, tee or two tees',
    safety_note: null,
    youtube_search_query: 'slow pitch softball inside the ball drill knob first path',
    youtube_search_url: ytSearch('slow pitch softball inside the ball drill knob first path'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Knob leads the way — barrel follows. Short path to the ball.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Too Uppercut ─────────────────────────────────────────────
  {
    id: 'sp_line_drive_tee',
    sport_id: 'softball_slow',
    issue_id: 'sp_too_uppercut',
    phase: 'contact_arc',
    name: 'Line-Drive Angle Tee Drill',
    goal: 'Match the bat angle to a line-drive trajectory, not a steep uppercut',
    steps: [
      'Set tee at shoulder height to mimic arc pitch height at contact',
      'Focus on driving the ball level — not straight up',
      'Bat should contact the top half of the ball, not the bottom',
      'Ball should travel at a flat or low line-drive angle off the tee',
      'If it pops straight up, bat angle is too steep — adjust back shoulder',
    ],
    reps_or_duration: '4 sets of 15 line-drive tee swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, adjustable tee, softballs',
    safety_note: null,
    youtube_search_query: 'slow pitch softball line drive contact drill tee arc height',
    youtube_search_url: ytSearch('slow pitch softball line drive contact drill tee arc height'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Drive the ball through the pitcher — not up to the sky.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Arc Timing Breakdown ──────────────────────────────────────
  {
    id: 'sp_full_timing_sequence',
    sport_id: 'softball_slow',
    issue_id: 'sp_poor_pitch_arc_timing',
    phase: 'load',
    name: 'Full Arc Timing Sequence Drill',
    goal: 'Coordinate the entire timing chain to the arc pitch delivery',
    steps: [
      'Partner throws 20 arc pitches — you call out each phase: "release, peak, descend, fire, contact"',
      'After calling each phase, start adding physical responses: load on "descend," stride on "fire," swing on "contact"',
      'Use a verbal routine every at-bat: "see it arc, wait, load, fire"',
      'If timing is consistently off: have partner alter arc heights so you adapt',
      'Progress: eliminate verbal cues when sequence feels automatic',
    ],
    reps_or_duration: '3 sets of 20 arc pitches with full timing sequence calls',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, softballs, partner',
    safety_note: null,
    youtube_search_query: 'slow pitch softball timing sequence arc pitch drill',
    youtube_search_url: ytSearch('slow pitch softball timing sequence arc pitch drill'),
    coach_channel_hint: 'Softball Tutor',
    focus_feel: 'Arc, peak, descend, fire — a rhythm that matches the ball\'s journey.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Finish Balance ───────────────────────────────────────
  {
    id: 'sp_balance_finish_hold',
    sport_id: 'softball_slow',
    issue_id: 'sp_poor_finish_balance',
    phase: 'follow_through',
    name: 'Balanced Finish 3-Second Hold',
    goal: 'Build a stable, balanced follow-through position after each swing',
    steps: [
      'After every swing (tee or live), hold your finish for 3 full seconds',
      'Weight should be on front foot, bat over front shoulder, back toe down',
      'If you stumble or step, you lost balance during the swing — reset',
      'Check: can you hold perfectly still for 3 seconds without wobbling?',
      'Partner photographs or videos the finish to check position',
    ],
    reps_or_duration: '3 sets of 15 — 3-second finish holds each',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee',
    safety_note: null,
    youtube_search_query: 'slow pitch softball finish balance hold drill stability',
    youtube_search_url: ytSearch('slow pitch softball finish balance hold drill stability'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Statue still at the finish — balanced, controlled, complete.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Pulling Off Early ─────────────────────────────────────────
  {
    id: 'sp_oppo_slow_pitch',
    sport_id: 'softball_slow',
    issue_id: 'sp_pulling_off_early',
    phase: 'contact_arc',
    name: 'Opposite-Field Arc Contact Drill',
    goal: 'Eliminate early pull-off by training opposite-field contact on arc pitches',
    steps: [
      'Partner throws arc pitches to the outside half of the plate',
      'Drive every ball to the opposite-field gap — no pull-side contact',
      'Front shoulder stays in — only release after ball goes the other way',
      'If ball goes to pull side, front shoulder opened early',
      'Progress to full-field hitting once pull-off habit is broken',
    ],
    reps_or_duration: '3 sets of 15 opposite-field arc contact swings',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, softballs, partner',
    safety_note: null,
    youtube_search_query: 'slow pitch softball opposite field drill pull off arc pitch',
    youtube_search_url: ytSearch('slow pitch softball opposite field drill pull off arc pitch'),
    coach_channel_hint: 'Softball Spot',
    focus_feel: 'Drive it the other way — shoulder stays in until the ball is gone.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },
];

export function getSlowPitchDrillsForIssue(issueId: string): SportDrillRecommendation[] {
  return SLOW_PITCH_DRILLS.filter((d) => d.issue_id === issueId);
}

export function getSlowPitchDrillsForPhase(phase: string): SportDrillRecommendation[] {
  return SLOW_PITCH_DRILLS.filter((d) => d.phase === phase);
}
