// ============================================================
// SwingIQ — Fast Pitch Softball Drill Library
// All YouTube links are SEARCH LINKS only — never hardcoded.
// ============================================================

import type { SportDrillRecommendation } from '../types';

function ytSearch(query: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
}

export const FAST_PITCH_DRILLS: SportDrillRecommendation[] = [
  // ── Compact Load / Quick Stride ───────────────────────────────
  {
    id: 'fp_compact_stride_drill',
    sport_id: 'softball_fast',
    issue_id: 'lunging_forward',
    phase: 'rapid_stride',
    name: 'Compact Stride Constraint Drill',
    goal: 'Train the short, quick stride required for fast pitch timing',
    steps: [
      'Place a 6-inch flat marker where your front foot should land',
      'Practice the load and stride landing on or just before the marker',
      'Stride should be soft and quick — no pause at landing',
      'Hands must stay back — check by video or partner observation',
      'Repeat until stride is consistently short and soft without conscious effort',
    ],
    reps_or_duration: '3 sets of 20 stride-only reps, then 20 tee swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee, small flat marker or tape',
    safety_note: null,
    youtube_search_query: 'fast pitch softball short stride drill compact hitting',
    youtube_search_url: ytSearch('fast pitch softball short stride drill compact hitting'),
    coach_channel_hint: 'Fastpitch TV, Softball Excellence',
    focus_feel: 'Step like you\'re stepping on ice — quick, quiet, and compact.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Hip Stall / Arms Only ─────────────────────────────────────
  {
    id: 'fp_hip_fire_wall',
    sport_id: 'softball_fast',
    issue_id: 'hip_stall',
    phase: 'hip_fire',
    name: 'Wall Hip-Fire Drill',
    goal: 'Train explosive hip rotation as the first movement in the downswing',
    steps: [
      'Stand with your back 4-6 inches from a wall in your batting stance',
      'Load up, then fire the hips open — back hip should brush the wall initially',
      'As the swing progresses, the hips should clear the wall',
      'Arms follow the hip rotation — never lead it',
      'Check: belt buckle should face the wall by end of swing',
    ],
    reps_or_duration: '3 sets of 15 shadow swings, then 15 tee swings',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, wall space, tee',
    safety_note: 'Ensure no bat contact with the wall during the swing.',
    youtube_search_query: 'fast pitch softball hip rotation drill wall drive',
    youtube_search_url: ytSearch('fast pitch softball hip rotation drill wall drive'),
    coach_channel_hint: 'Fastpitch TV',
    focus_feel: 'Feel the back hip brushing the wall, then clearing it as hips rotate through.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Head Off Ball / Rising Pitch ─────────────────────────────
  {
    id: 'fp_rising_ball_eyes',
    sport_id: 'softball_fast',
    issue_id: 'head_off_ball',
    phase: 'contact',
    name: 'Rising Ball Visual Tracking Drill',
    goal: 'Train head-down discipline against the rising fast pitch trajectory',
    steps: [
      'Have a partner soft-toss at an upward angle to simulate a rising pitch',
      'Your only job: keep your head down and see the ball contact the bat',
      'Do NOT look up — call out what you see ("saw it" or "lost it")',
      'Progress to machine at low velocity with a rising setting',
      'Mark balls with numbers; call out the number at contact',
    ],
    reps_or_duration: '4 sets of 10 rising-angle tosses',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, balls with numbers marked, partner',
    safety_note: null,
    youtube_search_query: 'fast pitch softball eyes on ball rising pitch drill tracking',
    youtube_search_url: ytSearch('fast pitch softball eyes on ball rising pitch drill tracking'),
    coach_channel_hint: 'NFCA, Fastpitch TV',
    focus_feel: 'The rising ball wants to fool your eyes. Trust your hands and stay down.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Casting / Bat Barrel Drops ────────────────────────────────
  {
    id: 'fp_knob_to_ball',
    sport_id: 'softball_fast',
    issue_id: 'casting_hands',
    phase: 'hip_fire',
    name: 'Knob to the Ball Drill',
    goal: 'Keep hands inside the ball path — eliminate casting in the fast pitch swing',
    steps: [
      'Set a tee at waist height in the center of the plate',
      'Swing with the focus of driving the knob of the bat toward the ball first',
      'The barrel trails behind — arriving last',
      'Feel the hands staying close to the body on the way to the ball',
      'Check by video: the barrel should not drop below the hands at any point before contact',
    ],
    reps_or_duration: '3 sets of 20 tee swings',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, tee, balls',
    safety_note: null,
    youtube_search_query: 'fast pitch softball knob to ball drill hands inside casting',
    youtube_search_url: ytSearch('fast pitch softball knob to ball drill hands inside casting'),
    coach_channel_hint: 'Softball Excellence, Fastpitch TV',
    focus_feel: 'Feel the knob leading, the barrel dragging. Like cracking a whip.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Short Follow-Through ──────────────────────────────────────
  {
    id: 'fp_high_finish',
    sport_id: 'softball_fast',
    issue_id: 'arm_short_follow',
    phase: 'follow_through',
    name: 'High Finish Hold Drill',
    goal: 'Reinforce complete follow-through — important for deceleration after contact, not before it',
    steps: [
      'After each swing (tee or soft-toss), freeze and hold the finish',
      'Bat should be above or at front shoulder level',
      'Freeze for 2 seconds — take a photo or check with a partner',
      'If you can\'t hold the finish, you stopped the swing too early',
      'Progress to calling out "finish!" on every rep where you complete it properly',
    ],
    reps_or_duration: '3 sets of 15 with 2-second holds',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee',
    safety_note: null,
    youtube_search_query: 'fast pitch softball follow through finish drill high',
    youtube_search_url: ytSearch('fast pitch softball follow through finish drill high'),
    coach_channel_hint: 'NFCA',
    focus_feel: 'The swing is done when the barrel is past your shoulder — never before.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Opposite Field — Front Shoulder ──────────────────────────
  {
    id: 'fp_oppo_tee',
    sport_id: 'softball_fast',
    issue_id: 'early_shoulder_pull',
    phase: 'hip_fire',
    name: 'Opposite Field Power Drill',
    goal: 'Build hip-shoulder separation habit by demanding opposite-field contact',
    steps: [
      'Set tee in the back half of the plate (outside pitch position)',
      'Drive the ball to the opposite field gap — not the pull side',
      'Front shoulder must stay closed until hips clear',
      'If ball goes to pull side, front shoulder opened too early',
      'Progress to outside-corner machine pitches at low velocity',
    ],
    reps_or_duration: '3 sets of 15 opposite-field contact swings',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, tee, balls',
    safety_note: null,
    youtube_search_query: 'fast pitch softball opposite field drill shoulder closed hip separation',
    youtube_search_url: ytSearch('fast pitch softball opposite field drill shoulder closed hip separation'),
    coach_channel_hint: 'Fastpitch TV',
    focus_feel: 'Keep that front shoulder shut — let the hips do the work first.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Stance Setup ─────────────────────────────────────────
  {
    id: 'fp_stance_routine',
    sport_id: 'softball_fast',
    issue_id: 'fp_poor_stance_setup',
    phase: 'load',
    name: 'Fast Pitch Stance Routine Drill',
    goal: 'Build a compact, balanced stance optimized for fast pitch reaction time',
    steps: [
      'Stand in front of a mirror in full batting stance',
      'Feet shoulder-width or slightly narrower than baseball for quicker stride',
      'Hands at rear shoulder height — no lower, no higher',
      'Knees slightly bent — ready to move in any direction',
      'Repeat 20 times until the position feels completely natural',
    ],
    reps_or_duration: '20 setup reps before every fast pitch practice session',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, mirror optional',
    safety_note: null,
    youtube_search_query: 'fast pitch softball stance setup drill athletic compact',
    youtube_search_url: ytSearch('fast pitch softball stance setup drill athletic compact'),
    coach_channel_hint: 'Fastpitch TV, NFCA',
    focus_feel: 'Balanced, compact, hands ready — loaded for the fastest pitch you will face.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Late Load ─────────────────────────────────────────────────
  {
    id: 'fp_load_trigger_drill',
    sport_id: 'softball_fast',
    issue_id: 'fp_late_load',
    phase: 'load',
    name: 'Pitcher-Motion Load Trigger Drill',
    goal: 'Train the load to begin with the pitcher\'s arm circle, not at release',
    steps: [
      'Watch video of a pitcher or use a pitching machine with a visual windup cue',
      'Begin weight shift onto the back foot as the pitcher\'s arm starts its circle',
      'Practice 20 pitches calling out "load!" the instant the circle starts',
      'You should be fully loaded by the time the ball releases',
      'Test: if you feel rushed, your load trigger is too late — move it earlier',
    ],
    reps_or_duration: '3 sets of 20 pitched reps with load trigger focus',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, pitching partner or machine',
    safety_note: null,
    youtube_search_query: 'fast pitch softball early load timing pitcher arm circle drill',
    youtube_search_url: ytSearch('fast pitch softball early load timing pitcher arm circle drill'),
    coach_channel_hint: 'Fastpitch TV',
    focus_feel: 'Load begins with the circle — you are already moving when the ball releases.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Stride Direction ─────────────────────────────────────
  {
    id: 'fp_stride_line_drill',
    sport_id: 'softball_fast',
    issue_id: 'fp_poor_stride_direction',
    phase: 'rapid_stride',
    name: 'Stride Direction Line Drill',
    goal: 'Train stride foot to land straight toward the pitcher consistently',
    steps: [
      'Draw a straight chalk line from back foot toward the pitcher',
      'Every stride must land on or parallel to that line',
      'Video from the front to verify foot direction clearly',
      'If foot opens or closes, practice with eyes on foot during stride-only reps',
      'Progress to full swings after 50 correct directional strides',
    ],
    reps_or_duration: '3 sets of 20 stride-direction-only reps',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, chalk or tape',
    safety_note: null,
    youtube_search_query: 'fast pitch softball stride direction drill straight line pitcher',
    youtube_search_url: ytSearch('fast pitch softball stride direction drill straight line pitcher'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Toe points at the pitcher — stride is an arrow to the mound.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Hip-Shoulder Separation ──────────────────────────────
  {
    id: 'fp_separation_drill',
    sport_id: 'softball_fast',
    issue_id: 'fp_poor_separation',
    phase: 'hip_fire',
    name: 'Hip-Fire Shoulder-Hold Drill',
    goal: 'Build hip-shoulder separation in the compact fast pitch swing',
    steps: [
      'Stand in batting stance with a bat across the back of your shoulders',
      'Fire your hips open while keeping the bat (and shoulders) closed as long as possible',
      'Feel the stretch between hips and shoulders at maximum separation',
      'Hold that stretch for 1 second, then let the hands fire through',
      'Progress: add a tee and replicate the sequence with a swing',
    ],
    reps_or_duration: '3 sets of 15 hip-hold reps',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, tee',
    safety_note: null,
    youtube_search_query: 'fast pitch softball hip shoulder separation drill X factor',
    youtube_search_url: ytSearch('fast pitch softball hip shoulder separation drill X factor'),
    coach_channel_hint: 'Fastpitch TV, NFCA',
    focus_feel: 'Hips spin — shoulders wait — then hands explode. Feel the rubber band.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Hand Drop ─────────────────────────────────────────────────
  {
    id: 'fp_no_hitch_drill',
    sport_id: 'softball_fast',
    issue_id: 'fp_hand_drop',
    phase: 'load',
    name: 'No-Hitch Hand Position Drill',
    goal: 'Eliminate hand drop by training high, stable hand position at load',
    steps: [
      'Stand in batting stance — place hands at launch position (rear shoulder height)',
      'Take 5 slow practice swings, hands staying at or above launch position throughout load',
      'Video yourself from the side — look for any drop below the shoulder',
      'If hands drop: place a tee at launch-position height beside your hands as a reminder',
      'Hands should stay at or above that height during the load and swing',
    ],
    reps_or_duration: '3 sets of 15 tee swings with hand-height check',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee, video optional',
    safety_note: null,
    youtube_search_query: 'fast pitch softball no hitch hand position drill high hands',
    youtube_search_url: ytSearch('fast pitch softball no hitch hand position drill high hands'),
    coach_channel_hint: 'NFCA, Softball Excellence',
    focus_feel: 'Hands stay high — no dip, no loop, straight to the ball.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Poor Extension at Contact ─────────────────────────────────
  {
    id: 'fp_extension_through_drill',
    sport_id: 'softball_fast',
    issue_id: 'fp_poor_extension_contact',
    phase: 'contact',
    name: 'Extension Through Contact Drill',
    goal: 'Build full arm extension through the contact zone on fast pitch swings',
    steps: [
      'Set tee in center of plate at belt height',
      'After contact, consciously reach the bat toward the outfield for a full second',
      'Arm should be at 80-90% extension at and just after contact',
      'Cone challenge: place a cone 18 inches past the tee — reach the bat toward it',
      'Progress to machine pitches replicating the same extension feel',
    ],
    reps_or_duration: '3 sets of 15 tee swings with extension hold',
    skill_level: 'beginner',
    difficulty: 'beginner',
    equipment_needed: 'Bat, tee, cone optional',
    safety_note: null,
    youtube_search_query: 'fast pitch softball extension through contact drill arm reach',
    youtube_search_url: ytSearch('fast pitch softball extension through contact drill arm reach'),
    coach_channel_hint: 'Fastpitch TV',
    focus_feel: 'Drive through the ball — arm extends toward the target before wrapping up.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Steep Attack Pattern ─────────────────────────────────────
  {
    id: 'fp_attack_angle_tee',
    sport_id: 'softball_fast',
    issue_id: 'fp_steep_attack_pattern',
    phase: 'hip_fire',
    name: 'Attack Angle Two-Tee Drill',
    goal: 'Replace steep downswing with a level-to-slight-upward attack matching pitch trajectory',
    steps: [
      'Set two tees: one at normal belt height, one 2 inches higher and 8 inches in front',
      'Swing the bat through the zone between the two tees without hitting either',
      'Barrel must travel upward slightly — not downward through the zone',
      'Check trajectory: ball should fly on a line, not a steep arc',
      'Adjust front tee height until ball consistently launches at line-drive angle',
    ],
    reps_or_duration: '4 sets of 15 two-tee swings',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, two batting tees, softballs',
    safety_note: null,
    youtube_search_query: 'fast pitch softball attack angle drill two tee line drive',
    youtube_search_url: ytSearch('fast pitch softball attack angle drill two tee line drive'),
    coach_channel_hint: 'Softball Excellence',
    focus_feel: 'Barrel enters low and exits high — driving through the ball on the right angle.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },

  // ── Contact Too Deep / Too Forward ────────────────────────────
  {
    id: 'fp_contact_zone_tee',
    sport_id: 'softball_fast',
    issue_id: 'fp_contact_too_deep',
    phase: 'contact',
    name: 'Contact Zone Positioning Drill',
    goal: 'Establish the correct contact point for different pitch locations',
    steps: [
      'Place tee for an inside pitch: in front of the front hip (forward contact)',
      'Place tee for a middle pitch: even with the front hip',
      'Place tee for an outside pitch: slightly deeper, beside the back hip',
      'Practice 10 reps at each location calling out "inside, middle, outside"',
      'Progress to pitching machine at low velocity, self-adjusting contact point',
    ],
    reps_or_duration: '3 sets of 30 (10 per tee location)',
    skill_level: 'intermediate',
    difficulty: 'intermediate',
    equipment_needed: 'Bat, adjustable tee, softballs',
    safety_note: null,
    youtube_search_query: 'fast pitch softball contact point location drill tee inside outside',
    youtube_search_url: ytSearch('fast pitch softball contact point location drill tee inside outside'),
    coach_channel_hint: 'NFCA, Fastpitch TV',
    focus_feel: 'Inside pitch — reach forward. Outside pitch — let it travel deeper.',
    source_ids: [],
    last_reviewed: '2024-01-01',
  },
];

export function getFastPitchDrillsForIssue(issueId: string): SportDrillRecommendation[] {
  return FAST_PITCH_DRILLS.filter((d) => d.issue_id === issueId);
}

export function getFastPitchDrillsForPhase(phase: string): SportDrillRecommendation[] {
  return FAST_PITCH_DRILLS.filter((d) => d.phase === phase);
}
