#!/usr/bin/env node
/**
 * SwingVantage — Weekly growth report generator.
 *
 * Produces a markdown snapshot of the current growth surface area
 * (published SEO pages, backlog, tools, challenges, email templates)
 * plus a KPI template to fill from analytics. Writes to
 * content/growth/reports/YYYY-MM-DD.md and prints the path.
 *
 * Run: npm run growth:report
 */
import { readFileSync, existsSync, mkdirSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';

const ROOT = process.cwd();
const today = new Date().toISOString().slice(0, 10);

function count(dir) {
  try { return readdirSync(join(ROOT, dir), { withFileTypes: true }).filter((d) => d.isDirectory()).length; }
  catch { return 0; }
}

// Published vs draft SEO pages
const seoSrc = existsSync(join(ROOT, 'apps/web/src/content/seoPages.ts'))
  ? readFileSync(join(ROOT, 'apps/web/src/content/seoPages.ts'), 'utf8') : '';
const publishedCount = (seoSrc.match(/publishStatus:\s*'published'/g) || []).length;
const draftCount = (seoSrc.match(/publishStatus:\s*'draft'/g) || []).length;

// Backlog by status
let backlog = { total: 0, byStatus: {} };
try {
  const data = JSON.parse(readFileSync(join(ROOT, 'content/growth/seo-backlog.json'), 'utf8'));
  backlog.total = data.items.length;
  for (const it of data.items) backlog.byStatus[it.status] = (backlog.byStatus[it.status] || 0) + 1;
} catch { /* ignore */ }

const tools = count('apps/web/src/app/tools') - 0; // includes index dir
const challenges = count('apps/web/src/app/challenges');
let emails = 0;
try { emails = readdirSync(join(ROOT, 'content/emails')).filter((f) => f.endsWith('.md')).length; } catch {}

const md = `# SwingVantage Growth Report — ${today}

## Growth surface area (auto-counted)
- Published SEO pages: **${publishedCount}**
- Draft SEO pages: **${draftCount}**
- SEO backlog items: **${backlog.total}** (${Object.entries(backlog.byStatus).map(([k, v]) => `${k}: ${v}`).join(', ') || 'n/a'})
- Free tool routes: **${Math.max(tools - 1, 0)}** (excluding index)
- Challenge routes: **${Math.max(challenges - 1, 0)}** (excluding index)
- Lifecycle email templates: **${emails}**

## KPIs (fill in from analytics)
| Metric | This week | Last week | Δ |
|---|---|---|---|
| Qualified organic sessions |  |  |  |
| Completed analyses |  |  |  |
| Tool results generated |  |  |  |
| Email captures |  |  |  |
| Returning users |  |  |  |
| Report copies / shares |  |  |  |

## Notes
- Wins:
- Misses:
- Next priority:

> Generated by scripts/growth-report.mjs. Pair with \`npm run growth:plan\`.
`;

const dir = join(ROOT, 'content/growth/reports');
mkdirSync(dir, { recursive: true });
const out = join(dir, `${today}.md`);
writeFileSync(out, md, 'utf8');
console.log('✅ Growth report written to content/growth/reports/' + today + '.md');
console.log(`   Published SEO: ${publishedCount} · Backlog: ${backlog.total} · Tools: ${Math.max(tools - 1, 0)} · Challenges: ${Math.max(challenges - 1, 0)} · Emails: ${emails}`);
