#!/usr/bin/env node
/**
 * SwingVantage — Weekly content calendar generator.
 *
 * Generates content/growth/weekly-plans/YYYY-MM-DD.md with:
 *   - 1 SEO article (next highest-priority backlog item)
 *   - 5 short-form video scripts (prompts)
 *   - 10 outreach tasks
 *   - 3 community post drafts (reminders, manual only)
 *   - 1 product/conversion improvement
 *
 * Does NOT post anything anywhere. Run: npm run growth:plan
 */
import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = process.cwd();
const today = new Date().toISOString().slice(0, 10);

// Pick the top backlog items not yet published.
let candidates = [];
try {
  const data = JSON.parse(readFileSync(join(ROOT, 'content/growth/seo-backlog.json'), 'utf8'));
  candidates = data.items
    .filter((i) => i.status !== 'published')
    .sort((a, b) => a.priority - b.priority);
} catch { /* ignore */ }

const article = candidates[0];
const articleLine = article
  ? `Write **/${article.slug}** — target keyword "${article.keyword}" (${article.sport}, ${article.funnelStage}). CTA: ${article.cta}. Use the AEO/GEO template (direct answer → diagnosis → drills → mistakes → coach → FAQ → schema). Promote to seoPages.ts only when fully written.`
  : 'Pick the next keyword from content/growth/seo-backlog.json (lowest priority number first).';

const videoSeeds = [
  'A myth-bust for your top sport ("Your slice isn\'t a face problem").',
  'A single high-leverage cue, demoed slowly.',
  'A 30-second drill walkthrough tied to a published article.',
  'A "what your data actually means" explainer.',
  'A parent-friendly youth tip (keep it simple, supervised).',
];

const outreachSeeds = [
  '2 golf coaches (use content/growth/coach-outreach.md)',
  '2 tennis coaches',
  '2 baseball/softball coaches',
  '1 facility/range (partners template)',
  '1 youth league',
  '1 creator DM (creator-outreach.md)',
  'Follow up with 1 prior contact',
];

const md = `# SwingVantage Weekly Plan — ${today}

> Generated by scripts/growth-plan.mjs. Drafts only — a human reviews, films,
> sends, and posts. **No automated posting to any social platform.**

## 1 SEO article
- ${articleLine}

## 5 short-form video scripts (draft in content/growth/video-ideas.md)
${videoSeeds.map((v, i) => `${i + 1}. ${v}`).join('\n')}

## 10 outreach tasks (send manually, personalized)
${[...outreachSeeds, ...outreachSeeds].slice(0, 10).map((o, i) => `${i + 1}. ${o}`).join('\n')}

## 3 community post drafts (manual only — see community-posts.md)
1. One genuinely helpful answer in a relevant golf community.
2. One helpful answer in a softball/baseball community.
3. One tennis or parent community answer.

## 1 product / conversion improvement
- Pick one: improve a tool's result clarity, add a trust block to a high-intent
  page, tighten a CTA, or speed up a slow page. Measure before/after.

## Before you ship
- [ ] \`npm run audit:growth\` is green
- [ ] No thin pages, no overclaiming, youth content stays parent-oriented
`;

const dir = join(ROOT, 'content/growth/weekly-plans');
mkdirSync(dir, { recursive: true });
const out = join(dir, `${today}.md`);
if (existsSync(out)) {
  console.log('ℹ️  Weekly plan already exists: content/growth/weekly-plans/' + today + '.md (leaving as-is)');
  process.exit(0);
}
writeFileSync(out, md, 'utf8');
console.log('✅ Weekly plan written to content/growth/weekly-plans/' + today + '.md');
