// ============================================================
// Theme Lab — periodic theme generation (#3 step 8). Deterministically derive
// new theme CANDIDATES from a base theme and drop them into the library as
// DRAFTS — never auto-published (the operator refines one in the builder and
// commits its CSS). Generation rotates HUE only, so each variant keeps the
// base's lightness/saturation relationships (and therefore its AA contrast).
// PURE — uses the color helpers, no randomness, no network.
// ============================================================

import type { ThemeId } from '@/lib/theme/themes';
import { getTheme } from '@/lib/theme/themes';
import { parseHslTriple, formatHslTriple } from './color';
import type { LibraryTheme } from './library';

export interface GenerateOptions {
  /** How many variants to produce (1–12, default 3). */
  count?: number;
  /** Degrees of hue rotation per step (default 40). */
  stepDegrees?: number;
}

/** Rotate the hue of an `hsl(H S% L%)` swatch string, preserving S and L. */
function rotateSwatch(swatch: string, deg: number): string {
  const hsl = parseHslTriple(swatch);
  if (!hsl) return swatch;
  return `hsl(${formatHslTriple({ ...hsl, h: (hsl.h + deg + 360) % 360 })})`;
}

/**
 * Generate `count` draft library themes from a base, each hue-rotated by a
 * multiple of `stepDegrees`. Deterministic: same inputs → same variants (same
 * ids), so re-running is idempotent against the library.
 */
export function generateThemeVariants(
  baseThemeId: ThemeId,
  opts: GenerateOptions = {},
): LibraryTheme[] {
  const count = Math.max(1, Math.min(12, opts.count ?? 3));
  const step = opts.stepDegrees ?? 40;
  const base = getTheme(baseThemeId);
  const now = new Date().toISOString();

  const out: LibraryTheme[] = [];
  for (let i = 1; i <= count; i++) {
    const deg = (step * i) % 360;
    out.push({
      id: `gen-${baseThemeId}-h${deg}`,
      name: `${base.name} +${deg}°`,
      source: 'generated',
      status: 'draft',
      category: base.category,
      swatches: {
        bg: rotateSwatch(base.swatches.bg, deg),
        surface: rotateSwatch(base.swatches.surface, deg),
        text: rotateSwatch(base.swatches.text, deg),
        primary: rotateSwatch(base.swatches.primary, deg),
        accent: rotateSwatch(base.swatches.accent, deg),
      },
      baseThemeId,
      version: 1,
      createdAt: now,
      note: `Generated by hue-rotating ${base.name} +${deg}°. Draft — refine in the builder, then export its CSS to publish. Hue-only, so contrast is preserved.`,
    });
  }
  return out;
}
