import type { DiagnosisCategory, SkillLevel, TrainingRoutine } from '../types';

export const TRAINING_ROUTINES: Record<DiagnosisCategory, TrainingRoutine[]> = {
  slice_weak_fade: [
    {
      id: 'face-control-beginner',
      diagnosis_category: 'slice_weak_fade',
      name: 'Face Control — Block Practice',
      goal: 'Square the face at impact to reduce the open face relationship with the path',
      data_point_being_improved: 'face_to_path',
      why_it_matters: 'An open face at impact is the #1 cause of slice spin. Reducing face-to-path by just 3° can eliminate most of the rightward curve.',
      skill_level: 'beginner',
      setup: 'Half a bucket of balls, one club (7-iron or driver). Alignment stick on the ground pointing at target. Tee peg or foam noodle 6 inches outside the ball as a gate.',
      drill_steps: [
        'Take your normal setup. Check grip — make sure you can see 2-3 knuckles on your lead hand.',
        'Make 10 practice swings at 50% speed, feeling the clubface rotate to square at impact.',
        'Hit 10 balls at 50% speed focusing only on the feeling of the face rotating closed through impact.',
        'Hit 10 balls at 75% speed. Watch start direction — the ball should start more to the left than normal.',
        'Hit 10 balls at full speed. Focus on the face, not the result.',
        'Rest 2 minutes. Repeat once more.',
      ],
      ball_count: 40,
      intensity: 'medium',
      feedback_metric: 'Face-to-path on launch monitor. Start direction of ball flight.',
      success_criteria: 'Face-to-path moves from positive to under +2.5°. Ball starts at or left of target.',
      common_mistakes: [
        'Trying to "steer" the ball — trust the face and let the club swing freely',
        'Gripping too tight — loosens rotation',
        'Looking up early — disrupts impact position',
      ],
      progression: 'Once face-to-path is consistently under +2.5°, move to path work to create the correct face/path combination for a controlled draw or straight shot.',
      retest_protocol: {
        shot_count: 30,
        club: 'Same club used in practice',
        focus_metrics: ['face_to_path', 'spin_axis', 'lateral_offline'],
        success_criteria: 'Face-to-path under +2.5°, lateral miss under 10 yards right',
        notes: 'Compare to pre-practice baseline. Look for spin axis moving toward 0.',
      },
      drill_recommendations: [
        {
          id: 'face-control-1',
          name: 'Towel Under Arm Face Control',
          category: 'face_control',
          difficulty: 'beginner',
          why_this_matches: 'Helps feel connection and promotes forearm rotation at impact',
          youtube_search_query: 'golf face control drill towel under arm slice fix',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+face+control+drill+towel+under+arm+slice+fix',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
        {
          id: 'face-control-2',
          name: 'Impact Bag Face Rotation Drill',
          category: 'face_control',
          difficulty: 'beginner',
          why_this_matches: 'Direct feedback on face angle at impact using an impact bag',
          youtube_search_query: 'golf impact bag face rotation drill closed face impact',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+impact+bag+face+rotation+drill+closed+face+impact',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
        {
          id: 'face-control-3',
          name: 'Gate Drill Start Line',
          category: 'start_line',
          difficulty: 'intermediate',
          why_this_matches: 'Forces correct start line which requires face control to maintain',
          youtube_search_query: 'golf start line gate drill tee peg face control',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+start+line+gate+drill+tee+peg+face+control',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 25,
    },
  ],
  hook_strong_draw: [
    {
      id: 'hook-control-beginner',
      diagnosis_category: 'hook_strong_draw',
      name: 'Face Control — Open Face Awareness',
      goal: 'Reduce excessive face closure to bring face-to-path from negative toward neutral',
      data_point_being_improved: 'face_to_path',
      why_it_matters: 'A closed face causes hook spin. Neutralizing face-to-path will straighten the ball flight and improve consistency.',
      skill_level: 'beginner',
      setup: 'Half bucket of balls. Alignment stick on ground. Practice at 50% speed initially.',
      drill_steps: [
        'Check grip — weaken it slightly (turn hands slightly away from trail side) if you have a very strong grip.',
        'Make 10 slow practice swings feeling the face stay slightly open longer through impact.',
        'Hit 10 balls at 50% speed — allow the ball to start right of target (normal for this drill).',
        'Hit 15 balls at full speed. Focus on holding the face open slightly longer.',
        'Check launch monitor: face-to-path should be closer to 0.',
      ],
      ball_count: 35,
      intensity: 'medium',
      feedback_metric: 'Face-to-path, spin_axis, curve',
      success_criteria: 'Face-to-path within -2.5° to 0°, spin axis > -5',
      common_mistakes: [
        'Over-correcting and creating a push/slice',
        'Blocking rather than holding — the feeling is "hold" not "block"',
      ],
      progression: 'Once face-to-path is neutral, work on path to create the intended draw shape with controlled face-to-path.',
      retest_protocol: {
        shot_count: 25,
        club: 'Same club',
        focus_metrics: ['face_to_path', 'spin_axis', 'curve'],
        success_criteria: 'Face-to-path within -2.5° to +2.5°',
        notes: 'Look for ball flight straightening or curving less left.',
      },
      drill_recommendations: [
        {
          id: 'hook-1',
          name: 'Weak Grip Hook Fix',
          category: 'face_control',
          difficulty: 'beginner',
          why_this_matches: 'Grip is often the root cause of a strong hook — weakening it reduces face closure rate',
          youtube_search_query: 'golf hook fix weak grip drill reduce face closure',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+hook+fix+weak+grip+drill+reduce+face+closure',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  pull: [
    {
      id: 'pull-path-correction',
      diagnosis_category: 'pull',
      name: 'Path Correction — Inside Out Drill',
      goal: 'Move club path from outside-in toward neutral or slightly inside-out',
      data_point_being_improved: 'club_path',
      why_it_matters: 'Pull shots cost significant distance and accuracy. Path correction brings the ball back to target.',
      skill_level: 'beginner',
      setup: 'Alignment stick in the ground outside the ball on a 45-degree angle pointing away from target. Practice swinging inside the stick.',
      drill_steps: [
        'Place alignment stick in the ground just outside the ball pointing at 45° away from target.',
        'Take 10 slow practice swings where the club passes inside (not hitting) the stick.',
        'Hit 15 balls at 60% speed focusing on swinging inside the stick.',
        'Hit 15 balls at full speed. Do not try to swing right — just avoid the stick.',
        'Check path on launch monitor after each set.',
      ],
      ball_count: 35,
      intensity: 'medium',
      feedback_metric: 'club_path, start_direction',
      success_criteria: 'Club path moves from negative to -1° or better',
      common_mistakes: [
        'Swinging too far right to compensate — this creates a push',
        'Forgetting to check alignment — many pulls start with poor alignment',
      ],
      progression: 'Once path is neutral, work on face control to match face to the new path.',
      retest_protocol: {
        shot_count: 25,
        club: 'Same club',
        focus_metrics: ['club_path', 'face_angle', 'start_direction'],
        success_criteria: 'Club path within -1° to +2°',
        notes: 'Check alignment sticks at setup each time.',
      },
      drill_recommendations: [
        {
          id: 'pull-1',
          name: 'Alignment Stick Gate Drill Path',
          category: 'club_path_control',
          difficulty: 'beginner',
          why_this_matches: 'Direct physical feedback for inside-out path',
          youtube_search_query: 'golf alignment stick drill fix outside in path pull',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+alignment+stick+drill+fix+outside+in+path+pull',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  fat_contact: [
    {
      id: 'low-point-control',
      diagnosis_category: 'fat_contact',
      name: 'Low Point Control — Ball First Contact',
      goal: 'Move the low point of the swing to match or be ahead of the ball at impact',
      data_point_being_improved: 'low_point_position',
      why_it_matters: 'Fat contact destroys distance and creates massive inconsistency. Ball-first contact is the foundation of solid iron play.',
      skill_level: 'beginner',
      setup: 'Place a tee peg in the ground 3 inches behind the ball. The goal is to NOT hit the tee. Or use a towel placed 3 inches behind the ball.',
      drill_steps: [
        'Place a tee or fold a towel 3 inches behind the ball.',
        'Make 10 practice swings brushing the ground AT the ball position, not behind it.',
        'Hit 10 balls at 50% speed — focus only on avoiding the tee/towel behind the ball.',
        'Hit 15 balls at 75% speed. Shift your weight forward before impact.',
        'Hit 10 balls at full speed. Feel your lead hip clearing toward the target through impact.',
      ],
      ball_count: 40,
      intensity: 'medium',
      feedback_metric: 'smash_factor, carry_distance, low_point_position',
      success_criteria: 'Smash factor above 1.33. No ground contact behind the ball. Carry distance increases.',
      common_mistakes: [
        'Hanging on the trail foot through impact',
        'Scooping at the ball rather than driving the handle forward',
        'Trying to lift the ball — the loft does that, not you',
      ],
      progression: 'Once consistently hitting ball first, add pressure-shift drills and step-through drills for dynamic weight transfer.',
      retest_protocol: {
        shot_count: 30,
        club: '7-iron',
        focus_metrics: ['smash_factor', 'low_point_position', 'carry_distance', 'launch_angle'],
        success_criteria: 'Smash factor > 1.33, low point at or ahead of ball',
        notes: 'Divots should appear at or ahead of ball position.',
      },
      drill_recommendations: [
        {
          id: 'fat-1',
          name: 'Towel Behind Ball Low Point Drill',
          category: 'low_point_control',
          difficulty: 'beginner',
          why_this_matches: 'Immediate feedback if low point is behind the ball',
          youtube_search_query: 'golf towel drill low point ball first contact fat shots fix',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+towel+drill+low+point+ball+first+contact+fat+shots+fix',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
        {
          id: 'fat-2',
          name: 'Step Through Drill Weight Shift',
          category: 'low_point_control',
          difficulty: 'beginner',
          why_this_matches: 'Forces weight transfer to lead side which moves low point forward',
          youtube_search_query: 'golf step through drill weight shift fat shot fix',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+step+through+drill+weight+shift+fat+shot+fix',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 25,
    },
  ],
  thin_contact: [
    {
      id: 'thin-strike-fix',
      diagnosis_category: 'thin_contact',
      name: 'Strike Height — Ground Contact Drill',
      goal: 'Make consistent contact with the bottom of the ball, not the equator',
      data_point_being_improved: 'impact_location_vertical',
      why_it_matters: 'Thin contact loses significant distance and height. Low on face = low launch, low spin, and unpredictable distance.',
      skill_level: 'beginner',
      setup: 'Practice hitting balls off slightly taller tee pegs at 50% swing speed.',
      drill_steps: [
        'Tee ball up slightly to practice hitting the bottom half of the ball.',
        'Make 10 slow practice swings brushing the ground under where the ball would be.',
        'Hit 10 balls from tee at 50% speed. Focus on the bottom of the ball.',
        'Gradually lower tee until hitting off the mat.',
        'Hit 15 balls off mat focusing on ground contact at the ball.',
      ],
      ball_count: 35,
      intensity: 'low',
      feedback_metric: 'impact_location_vertical, launch_angle, ball_speed',
      success_criteria: 'Launch angle increases, ball speed increases, shots feel solid',
      common_mistakes: ['Trying to help the ball up', 'Bending the lead elbow before impact'],
      progression: 'Move to normal ground balls once consistent. Use impact tape to verify vertical strike location.',
      retest_protocol: {
        shot_count: 20,
        club: 'Same club',
        focus_metrics: ['impact_location_vertical', 'ball_speed', 'launch_angle'],
        success_criteria: 'Impact vertical at or above -0.1 (center or above)',
        notes: 'Use impact spray on face to confirm strike location.',
      },
      drill_recommendations: [
        {
          id: 'thin-1',
          name: 'Brush the Ground Drill',
          category: 'strike_location_control',
          difficulty: 'beginner',
          why_this_matches: 'Forces awareness of low point and ground contact for thin shots',
          youtube_search_query: 'golf thin shot fix brush the ground drill iron contact',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+thin+shot+fix+brush+the+ground+drill+iron+contact',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  dynamic_loft_high: [
    {
      id: 'shaft-lean-drill',
      diagnosis_category: 'dynamic_loft_high',
      name: 'Shaft Lean / Compression Drill',
      goal: 'Reduce delivered loft by increasing forward shaft lean at impact',
      data_point_being_improved: 'dynamic_loft',
      why_it_matters: 'Excess dynamic loft increases spin and reduces distance. Shaft lean = compression = better ball striking.',
      skill_level: 'intermediate',
      setup: 'Impact bag or alignment stick in ground just ahead of ball. Focus on handle leading the clubhead into impact.',
      drill_steps: [
        'Set up with an impact bag or towel just ahead of ball position.',
        'Make 10 slow swings where the handle reaches the bag BEFORE the head does.',
        'Feel the shaft lean forward — hands ahead of the ball at impact.',
        'Hit 15 punch shots at 60% speed — this naturally promotes shaft lean.',
        'Hit 15 full shots maintaining the feeling of handle-leading impact.',
      ],
      ball_count: 40,
      intensity: 'medium',
      feedback_metric: 'dynamic_loft, spin_loft, launch_angle, spin_rate',
      success_criteria: 'Dynamic loft reduces by 4°+. Launch angle drops slightly. Spin rate reduces.',
      common_mistakes: ['Flipping at the ball to add loft', 'Leaning too far forward (delofting too much)'],
      progression: 'Increase swing speed gradually while maintaining shaft lean. Check carry distance to ensure not delofting too aggressively.',
      retest_protocol: {
        shot_count: 25,
        club: '7-iron',
        focus_metrics: ['dynamic_loft', 'spin_loft', 'launch_angle', 'spin_rate'],
        success_criteria: 'Dynamic loft within target window for club',
        notes: 'Compare before/after carry distance — should increase with lower spin.',
      },
      drill_recommendations: [
        {
          id: 'loft-1',
          name: 'Impact Bag Shaft Lean Drill',
          category: 'dynamic_loft_control',
          difficulty: 'intermediate',
          why_this_matches: 'Teaches handle-leading impact which directly reduces dynamic loft',
          youtube_search_query: 'golf shaft lean drill compress irons dynamic loft impact bag',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+shaft+lean+drill+compress+irons+dynamic+loft+impact+bag',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
        {
          id: 'loft-2',
          name: 'Punch Shot Drill',
          category: 'shaft_lean',
          difficulty: 'beginner',
          why_this_matches: 'Punch shots naturally promote shaft lean and reduce delivered loft',
          youtube_search_query: 'golf punch shot drill shaft lean compress ball irons',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+punch+shot+drill+shaft+lean+compress+ball+irons',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 25,
    },
  ],
  dynamic_loft_low: [
    {
      id: 'loft-increase-drill',
      diagnosis_category: 'dynamic_loft_low',
      name: 'Launch Window — Increase Delivered Loft',
      goal: 'Add loft at impact to bring launch into the optimal window',
      data_point_being_improved: 'dynamic_loft',
      why_it_matters: 'Too little loft can reduce carry and create a very low ball flight. This is especially problematic with driver.',
      skill_level: 'intermediate',
      setup: 'Tee the ball slightly higher. Focus on a more neutral or slightly positive attack angle.',
      drill_steps: [
        'Tee driver higher than normal.',
        'Play ball position slightly more forward in stance.',
        'Make 10 slow practice swings feeling like you are "picking" the ball off the tee.',
        'Hit 20 drives focusing on hitting slightly up on the ball.',
        'Check attack angle on launch monitor — target 1-3° positive for driver.',
      ],
      ball_count: 30,
      intensity: 'low',
      feedback_metric: 'attack_angle, dynamic_loft, launch_angle, carry_distance',
      success_criteria: 'Attack angle moves into positive range. Launch angle increases.',
      common_mistakes: ['Overswinging to try to hit up on ball', 'Moving too far forward in stance'],
      progression: 'Once attack angle is consistently positive, work on optimizing spin loft ratio.',
      retest_protocol: {
        shot_count: 20,
        club: 'Driver',
        focus_metrics: ['attack_angle', 'dynamic_loft', 'launch_angle'],
        success_criteria: 'Attack angle > 0° with driver',
        notes: 'Compare carry distance before and after.',
      },
      drill_recommendations: [
        {
          id: 'low-loft-1',
          name: 'Driver Tee Height Ball Position Drill',
          category: 'launch_window_control',
          difficulty: 'beginner',
          why_this_matches: 'Ball position and tee height directly affect attack angle and dynamic loft',
          youtube_search_query: 'golf driver tee height ball position attack angle launch angle',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+driver+tee+height+ball+position+attack+angle+launch+angle',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  heel_strike: [
    {
      id: 'heel-gate-drill',
      diagnosis_category: 'heel_strike',
      name: 'Strike Location — Toe-Side Gate Drill',
      goal: 'Move impact location from heel toward the center of the face',
      data_point_being_improved: 'impact_location_lateral',
      why_it_matters: 'Heel strikes lose ball speed, create gear-effect curve, and are unpredictable. Center strikes maximize distance and control.',
      skill_level: 'beginner',
      setup: 'Place a headcover or empty ball tube just outside the ball on the toe side. Hit the ball without touching the gate.',
      drill_steps: [
        'Use impact spray or tape on the face to see strike location before starting.',
        'Place a headcover 1/4 inch outside the toe side of the club.',
        'Make 10 slow practice swings without touching the headcover.',
        'Hit 15 balls at 60% speed avoiding the gate. This forces you slightly closer to the ball.',
        'Hit 15 balls at full speed maintaining the same relationship to the ball.',
        'Check impact spray after every 5 shots.',
      ],
      ball_count: 35,
      intensity: 'medium',
      feedback_metric: 'impact_location_lateral, ball_speed, smash_factor',
      success_criteria: 'Impact location moves from heel toward center. Ball speed increases.',
      common_mistakes: ['Standing too far from the ball', 'Early extension pushing the body toward the ball through impact'],
      progression: 'Once consistently hitting center or toe-center, check setup distance and posture to maintain the improved pattern.',
      retest_protocol: {
        shot_count: 20,
        club: 'Same club',
        focus_metrics: ['impact_location_lateral', 'ball_speed', 'smash_factor'],
        success_criteria: 'Impact location lateral between -0.1 and +0.2',
        notes: 'Use impact spray to verify before and after.',
      },
      drill_recommendations: [
        {
          id: 'heel-1',
          name: 'Toe Gate Drill Heel Strike',
          category: 'strike_location_control',
          difficulty: 'beginner',
          why_this_matches: 'Forces club to approach from slightly further away, moving strike toward center',
          youtube_search_query: 'driver heel strike drill gate drill toe side fix',
          youtube_search_url: 'https://www.youtube.com/results?search_query=driver+heel+strike+drill+gate+drill+toe+side+fix',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 25,
    },
  ],
  toe_strike: [
    {
      id: 'toe-gate-drill',
      diagnosis_category: 'toe_strike',
      name: 'Strike Location — Heel-Side Gate Drill',
      goal: 'Move impact location from toe toward center of the face',
      data_point_being_improved: 'impact_location_lateral',
      why_it_matters: 'Toe strikes lose energy and create unpredictable ball flight via gear effect.',
      skill_level: 'beginner',
      setup: 'Place a headcover just inside (heel-side) the ball. Hit the ball without touching the gate.',
      drill_steps: [
        'Use impact spray on face.',
        'Place headcover 1/4 inch on the heel side.',
        'Hit 15 balls at 60% speed while avoiding the gate.',
        'Hit 15 balls at full speed. Check spray every 5 shots.',
      ],
      ball_count: 30,
      intensity: 'medium',
      feedback_metric: 'impact_location_lateral, ball_speed',
      success_criteria: 'Impact moves from toe toward center',
      common_mistakes: ['Standing too far from ball', 'Arms reaching at impact'],
      progression: 'Once centered, check setup distance.',
      retest_protocol: {
        shot_count: 20,
        club: 'Same club',
        focus_metrics: ['impact_location_lateral', 'ball_speed'],
        success_criteria: 'Impact lateral between -0.1 and +0.1',
        notes: 'Use impact spray.',
      },
      drill_recommendations: [
        {
          id: 'toe-1',
          name: 'Heel Gate Drill Toe Strike Fix',
          category: 'strike_location_control',
          difficulty: 'beginner',
          why_this_matches: 'Constrains path to promote more heel-side approach',
          youtube_search_query: 'golf toe strike fix heel side gate drill iron',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+toe+strike+fix+heel+side+gate+drill+iron',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  attack_angle_steep: [
    {
      id: 'shallow-attack-drill',
      diagnosis_category: 'attack_angle_steep',
      name: 'Shallowing Drill — Reduce Steep Attack',
      goal: 'Reduce attack angle steepness to improve ball flight and reduce spin',
      data_point_being_improved: 'attack_angle',
      why_it_matters: 'Too steep an attack angle increases spin, reduces distance, and creates inconsistent contact.',
      skill_level: 'intermediate',
      setup: 'Alignment stick in the ground 12 inches behind ball on a 45-degree angle. Practice shallowing approach to avoid hitting the stick.',
      drill_steps: [
        'Place alignment stick in ground behind ball at 45-degree angle pointing up.',
        'Make 10 slow swings from the top of backswing, feeling the club shallow (drop inside/under the stick).',
        'Hit 15 balls at 60% speed with the shallowing feel.',
        'Hit 15 balls at full speed. Check attack angle on monitor.',
      ],
      ball_count: 35,
      intensity: 'medium',
      feedback_metric: 'attack_angle, dynamic_loft, spin_rate',
      success_criteria: 'Attack angle moves toward target window (-4 to -1 for irons)',
      common_mistakes: ['Overcorrecting to too shallow (flip)', 'Losing power while shallowing'],
      progression: 'Once attack angle is in range, work on matching face control to new path.',
      retest_protocol: {
        shot_count: 25,
        club: '7-iron',
        focus_metrics: ['attack_angle', 'spin_rate', 'carry_distance'],
        success_criteria: 'Attack angle within target window',
        notes: 'Compare spin rate and carry distance before and after.',
      },
      drill_recommendations: [
        {
          id: 'steep-1',
          name: 'Shallowing Transition Drill',
          category: 'attack_angle_control',
          difficulty: 'intermediate',
          why_this_matches: 'Teaches transition shallowing which reduces steep angle of attack',
          youtube_search_query: 'golf shallowing drill steep downswing attack angle fix',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+shallowing+drill+steep+downswing+attack+angle+fix',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 25,
    },
  ],
  attack_angle_shallow: [
    {
      id: 'steepen-attack-drill',
      diagnosis_category: 'attack_angle_shallow',
      name: 'Steepen Attack — Descending Blow Drill',
      goal: 'Increase descending blow to bring attack angle into proper range for irons',
      data_point_being_improved: 'attack_angle',
      why_it_matters: 'Too shallow an attack angle with irons creates thin contact and weak ball flight.',
      skill_level: 'intermediate',
      setup: 'Practice hitting slightly deeper divots ahead of ball. Use headcover 3 inches ahead of ball as target.',
      drill_steps: [
        'Practice brushing the ground 3 inches ahead of the ball position.',
        'Hit 15 balls focusing on striking ball then turf.',
        'Feel the handle slightly more forward at impact.',
        'Hit 20 balls at full speed maintaining the descending feel.',
      ],
      ball_count: 35,
      intensity: 'medium',
      feedback_metric: 'attack_angle, smash_factor',
      success_criteria: 'Attack angle moves more negative for irons',
      common_mistakes: ['Hitting too steep causing a dig/fat', 'Losing distance while steepening'],
      progression: 'Once attack angle is in range, check dynamic loft is not too high.',
      retest_protocol: {
        shot_count: 25,
        club: '7-iron',
        focus_metrics: ['attack_angle', 'smash_factor'],
        success_criteria: 'Attack angle within -6 to -2 for irons',
        notes: 'Check divots should be ahead of ball position.',
      },
      drill_recommendations: [
        {
          id: 'shallow-1',
          name: 'Ball First Contact Descending Blow',
          category: 'attack_angle_control',
          difficulty: 'beginner',
          why_this_matches: 'Teaches descending blow for proper iron contact',
          youtube_search_query: 'golf iron descending blow attack angle ball first contact drill',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+iron+descending+blow+attack+angle+ball+first+contact+drill',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  spin_too_high: [
    {
      id: 'spin-reduction-drill',
      diagnosis_category: 'spin_too_high',
      name: 'Spin Reduction — Compression and Shaft Lean',
      goal: 'Reduce spin rate by improving impact conditions and reducing spin loft',
      data_point_being_improved: 'spin_rate',
      why_it_matters: 'High spin balloons the ball flight, loses distance, and magnifies wind effects.',
      skill_level: 'intermediate',
      setup: 'Practice punch shots and compression drills to reduce delivered loft.',
      drill_steps: [
        'Hit 10 punch shots at 60% speed feeling the ball come out low and penetrating.',
        'Hit 15 full shots with the same compression feel — handle leading at impact.',
        'Check spin rate after each set.',
        'If spin is still high, check ball type — high-spin balls can add 500+ rpm.',
      ],
      ball_count: 30,
      intensity: 'medium',
      feedback_metric: 'spin_rate, spin_loft, dynamic_loft',
      success_criteria: 'Spin rate reduces by 500+ rpm',
      common_mistakes: ['Over-compressing causing low launch', 'Incorrect ball for swing speed'],
      progression: 'Once spin is in range, optimize launch angle to maximize carry.',
      retest_protocol: {
        shot_count: 25,
        club: 'Same club',
        focus_metrics: ['spin_rate', 'spin_loft', 'carry_distance'],
        success_criteria: 'Spin within target window for club',
        notes: 'Also check ball type — try a lower-spin ball if issue persists.',
      },
      drill_recommendations: [
        {
          id: 'spin-1',
          name: 'Compression Drill Lower Spin',
          category: 'spin_window_control',
          difficulty: 'intermediate',
          why_this_matches: 'Direct compression drills reduce spin loft and spin rate',
          youtube_search_query: 'golf lower spin rate compression drill shaft lean punch shot',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+lower+spin+rate+compression+drill+shaft+lean+punch+shot',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  spin_too_low: [
    {
      id: 'spin-increase-drill',
      diagnosis_category: 'spin_too_low',
      name: 'Spin Optimization — Increase Ball Spin',
      goal: 'Increase spin rate to improve ball flight and stopping power',
      data_point_being_improved: 'spin_rate',
      why_it_matters: 'Too little spin causes knuckleball flight and shots that do not stop on greens.',
      skill_level: 'intermediate',
      setup: 'Focus on clean face contact and proper attack angle to generate more spin.',
      drill_steps: [
        'Check that clubface is clean — dirty face drastically reduces spin.',
        'Practice hitting with a slightly steeper attack angle for irons.',
        'Hit 20 balls focusing on clean face-to-ball contact.',
        'Check spin rate after each set.',
      ],
      ball_count: 25,
      intensity: 'low',
      feedback_metric: 'spin_rate, attack_angle',
      success_criteria: 'Spin rate moves toward target window',
      common_mistakes: ['Using worn grooves', 'Too shallow attack angle'],
      progression: 'Check equipment — worn grooves cannot generate spin.',
      retest_protocol: {
        shot_count: 20,
        club: 'Same club',
        focus_metrics: ['spin_rate', 'attack_angle'],
        success_criteria: 'Spin within target window',
        notes: 'Clean grooves before retesting.',
      },
      drill_recommendations: [
        {
          id: 'lowspin-1',
          name: 'Groove Engagement Spin Drill',
          category: 'spin_window_control',
          difficulty: 'beginner',
          why_this_matches: 'Clean face contact and proper angle generates maximum groove engagement',
          youtube_search_query: 'golf increase spin rate grooves attack angle wedge iron',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+increase+spin+rate+grooves+attack+angle+wedge+iron',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 15,
    },
  ],
  launch_too_high: [
    {
      id: 'launch-reduction-drill',
      diagnosis_category: 'launch_too_high',
      name: 'Launch Window — Reduce Excess Launch',
      goal: 'Lower launch angle to improve carry distance and reduce wind exposure',
      data_point_being_improved: 'launch_angle_vertical',
      why_it_matters: 'Excess launch with irons causes a high, ballooning ball flight that loses distance into the wind.',
      skill_level: 'intermediate',
      setup: 'Focus on shaft lean and reducing dynamic loft at impact.',
      drill_steps: [
        'Hit 10 punch shots at 50% speed — these naturally reduce launch angle.',
        'Hit 15 full shots focusing on handle-leading impact.',
        'Check launch angle on monitor after each set.',
      ],
      ball_count: 30,
      intensity: 'medium',
      feedback_metric: 'launch_angle_vertical, dynamic_loft',
      success_criteria: 'Launch angle within target window',
      common_mistakes: ['Over-delofting causing too-low launch', 'Losing distance'],
      progression: 'Once launch is in range, check spin rate to ensure correct ball flight.',
      retest_protocol: {
        shot_count: 20,
        club: 'Same club',
        focus_metrics: ['launch_angle_vertical', 'dynamic_loft', 'carry_distance'],
        success_criteria: 'Launch within target window for club',
        notes: 'Compare carry distance before and after.',
      },
      drill_recommendations: [
        {
          id: 'highlaunch-1',
          name: 'Punch Shot Launch Reduction',
          category: 'launch_window_control',
          difficulty: 'beginner',
          why_this_matches: 'Punch shots directly reduce launch angle by encouraging shaft lean',
          youtube_search_query: 'golf punch shot launch angle reduction shaft lean iron',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+punch+shot+launch+angle+reduction+shaft+lean+iron',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  launch_too_low: [
    {
      id: 'launch-increase-drill',
      diagnosis_category: 'launch_too_low',
      name: 'Launch Window — Increase Launch Angle',
      goal: 'Increase launch angle to maximize carry distance and ball flight',
      data_point_being_improved: 'launch_angle_vertical',
      why_it_matters: 'Too low launch reduces carry distance and creates a ball that runs instead of stops.',
      skill_level: 'intermediate',
      setup: 'Ball position forward, tee higher for driver. Focus on positive attack angle.',
      drill_steps: [
        'Move ball position forward in stance.',
        'For driver: tee ball higher.',
        'Hit 20 balls focusing on sweeping/picking the ball.',
        'Check launch angle on monitor.',
      ],
      ball_count: 25,
      intensity: 'low',
      feedback_metric: 'launch_angle_vertical, attack_angle',
      success_criteria: 'Launch moves toward target window',
      common_mistakes: ['Too far forward causing thin contact', 'Over-helping ball up'],
      progression: 'Once launch is in range, optimize spin rate.',
      retest_protocol: {
        shot_count: 20,
        club: 'Driver or same club',
        focus_metrics: ['launch_angle_vertical', 'attack_angle'],
        success_criteria: 'Launch within target window',
        notes: 'Check carry distance improves with higher launch.',
      },
      drill_recommendations: [
        {
          id: 'lowlaunch-1',
          name: 'Tee Height Attack Angle Drill',
          category: 'launch_window_control',
          difficulty: 'beginner',
          why_this_matches: 'Tee height and ball position adjustments directly affect launch angle',
          youtube_search_query: 'golf low launch fix attack angle driver tee height ball position',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+low+launch+fix+attack+angle+driver+tee+height+ball+position',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 15,
    },
  ],
  distance_loss: [
    {
      id: 'distance-recovery-drill',
      diagnosis_category: 'distance_loss',
      name: 'Distance Recovery — Smash Factor and Strike',
      goal: 'Recover lost distance by improving contact quality and impact conditions',
      data_point_being_improved: 'smash_factor',
      why_it_matters: 'Distance loss is usually not a speed problem — it is a contact and delivery problem. Improving smash factor can add 10-20 yards without swinging harder.',
      skill_level: 'beginner',
      setup: 'Use impact spray to track strike location. Check both center-face contact and low-point control.',
      drill_steps: [
        'Apply impact spray to face.',
        'Hit 10 balls at 70% speed focusing only on center contact.',
        'Check spray after each shot.',
        'Hit 20 balls at full speed maintaining center contact.',
        'Check ball speed and smash factor — should increase with better contact.',
      ],
      ball_count: 35,
      intensity: 'medium',
      feedback_metric: 'smash_factor, ball_speed, carry_distance',
      success_criteria: 'Smash factor improves by 0.05+. Ball speed increases without more club speed.',
      common_mistakes: ['Swinging harder instead of better', 'Ignoring strike location'],
      progression: 'Once smash factor is at target, work on optimizing launch and spin conditions.',
      retest_protocol: {
        shot_count: 25,
        club: 'Same club',
        focus_metrics: ['smash_factor', 'ball_speed', 'carry_distance'],
        success_criteria: 'Ball speed increases. Carry distance increases.',
        notes: 'Compare to pre-session baseline carry distance.',
      },
      drill_recommendations: [
        {
          id: 'distance-1',
          name: 'Impact Spray Distance Drill',
          category: 'strike_location_control',
          difficulty: 'beginner',
          why_this_matches: 'Center strikes are the fastest path to more distance without physical training',
          youtube_search_query: 'golf distance loss center strike impact spray smash factor drill',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+distance+loss+center+strike+impact+spray+smash+factor+drill',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 25,
    },
  ],
  inconsistent_carry: [
    {
      id: 'consistency-routine',
      diagnosis_category: 'inconsistent_carry',
      name: 'Consistency Routine — Pre-Shot Lock and Repeat',
      goal: 'Reduce carry variance by building a consistent pre-shot routine and repeatable impact position',
      data_point_being_improved: 'carry_distance',
      why_it_matters: 'Inconsistent carry makes club selection unreliable. ±5 yards consistency is the goal for scoring iron play.',
      skill_level: 'beginner',
      setup: 'Choose one club. Hit all shots with identical pre-shot routine, grip, and setup.',
      drill_steps: [
        'Choose one club and hit ONLY that club for this session.',
        'Develop and repeat a consistent pre-shot routine before every shot.',
        'Hit 30 balls with no change in routine. Log carry of every shot.',
        'Calculate your 10-shot average. Identify any outliers.',
        'Remove top and bottom 2 shots — remaining 6 is your "consistent window."',
      ],
      ball_count: 30,
      intensity: 'low',
      feedback_metric: 'carry_distance, carry_std_dev',
      success_criteria: 'Carry standard deviation under 6% of average',
      common_mistakes: ['Changing something after every shot', 'Inconsistent setup and alignment'],
      progression: 'Once variance reduces, move to scoring pressure drills with specific distance targets.',
      retest_protocol: {
        shot_count: 30,
        club: 'Same club',
        focus_metrics: ['carry_distance', 'smash_factor'],
        success_criteria: 'Carry std dev under 6% of average',
        notes: 'Record all 30 carries. Compare variance to baseline session.',
      },
      drill_recommendations: [
        {
          id: 'consistency-1',
          name: 'Carry Consistency Pre-Shot Routine',
          category: 'distance_control',
          difficulty: 'beginner',
          why_this_matches: 'Pre-shot routine is the most researched method for reducing shot-to-shot variance',
          youtube_search_query: 'golf consistency routine carry distance control pre shot routine',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+consistency+routine+carry+distance+control+pre+shot+routine',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 30,
    },
  ],
  poor_smash_factor: [
    {
      id: 'smash-factor-drill',
      diagnosis_category: 'poor_smash_factor',
      name: 'Smash Factor Recovery — Center Strike Focus',
      goal: 'Improve smash factor to the target range for the club being used',
      data_point_being_improved: 'smash_factor',
      why_it_matters: 'Every 0.05 improvement in smash factor at 100 mph club speed adds ~5 mph ball speed and ~10 yards carry.',
      skill_level: 'beginner',
      setup: 'Impact spray on face. Hit balls at 80% speed focused purely on center contact.',
      drill_steps: [
        'Apply impact spray to the entire face.',
        'Hit 5 shots at 50% speed — note spray pattern.',
        'Hit 10 shots at 70% speed — try to repeat the spray mark.',
        'Hit 15 shots at 85% speed — maintain center contact.',
        'Check smash factor after each block of 5.',
      ],
      ball_count: 30,
      intensity: 'medium',
      feedback_metric: 'smash_factor, ball_speed, impact_location_lateral',
      success_criteria: 'Smash factor reaches target minimum for club',
      common_mistakes: ['Swinging full speed before center contact is grooved', 'Ignoring the spray feedback'],
      progression: 'Once smash factor is at target, gradually increase club speed.',
      retest_protocol: {
        shot_count: 20,
        club: 'Same club',
        focus_metrics: ['smash_factor', 'ball_speed'],
        success_criteria: 'Smash factor at or above target minimum',
        notes: 'Use impact spray for every shot in retest.',
      },
      drill_recommendations: [
        {
          id: 'smash-1',
          name: 'Impact Spray Smash Factor Drill',
          category: 'strike_location_control',
          difficulty: 'beginner',
          why_this_matches: 'Impact spray directly identifies off-center strikes and allows correction',
          youtube_search_query: 'golf smash factor improve center strike impact spray ball speed',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+smash+factor+improve+center+strike+impact+spray+ball+speed',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  equipment_concern: [
    {
      id: 'equipment-eval',
      diagnosis_category: 'equipment_concern',
      name: 'Equipment Evaluation — Fitting Check',
      goal: 'Identify whether data patterns suggest an equipment-fit issue vs. a swing issue',
      data_point_being_improved: 'overall',
      why_it_matters: 'Playing with poorly fitted equipment creates compensations that look like swing problems.',
      skill_level: 'beginner',
      setup: 'Review the data patterns and compare to typical swing-caused vs. equipment-caused numbers.',
      drill_steps: [
        'Review your data report with a club fitter if possible.',
        'Check loft, lie angle, shaft flex, and shaft weight match your swing speed.',
        'Test a club fitting session to compare fitted vs. current equipment data.',
      ],
      ball_count: 0,
      intensity: 'low',
      feedback_metric: 'smash_factor, spin_rate, launch_angle',
      success_criteria: 'Data improves with equipment that matches swing profile',
      common_mistakes: ['Assuming it is always a swing issue', 'Not getting fitted for shaft flex'],
      progression: 'After fitting, rebuild baseline session to compare data to previous equipment.',
      retest_protocol: {
        shot_count: 30,
        club: 'Fitted club vs. current club',
        focus_metrics: ['smash_factor', 'ball_speed', 'carry_distance', 'spin_rate'],
        success_criteria: 'Measurable improvement with fitted equipment',
        notes: 'Compare same shot conditions, same ball, same session.',
      },
      drill_recommendations: [
        {
          id: 'equip-1',
          name: 'Club Fitting Session',
          category: 'equipment',
          difficulty: 'beginner',
          why_this_matches: 'Only way to confirm whether equipment is limiting performance',
          youtube_search_query: 'golf club fitting what to expect launch monitor data',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+club+fitting+what+to+expect+launch+monitor+data',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 60,
    },
  ],
  push: [
    {
      id: 'push-path-fix',
      diagnosis_category: 'push',
      name: 'Push Pattern — Path and Face Alignment',
      goal: 'Reduce push pattern by neutralizing face and path relationship',
      data_point_being_improved: 'club_path',
      why_it_matters: 'A push puts the ball into rough or OB right. Often caused by a face and path that are both right of target.',
      skill_level: 'beginner',
      setup: 'Alignment sticks and impact spray. Check alignment first before any swing changes.',
      drill_steps: [
        'Check alignment — many pushes start with aiming right without knowing it.',
        'Hit 10 shots with alignment sticks confirming square setup.',
        'If push persists, check club path — inside-out path with open face = push.',
        'Work on squaring face or neutralizing path depending on data.',
      ],
      ball_count: 30,
      intensity: 'medium',
      feedback_metric: 'club_path, face_angle, start_direction, lateral_offline',
      success_criteria: 'Ball starts at or left of previous pattern',
      common_mistakes: ['Overcorrecting to a pull', 'Not checking alignment first'],
      progression: 'Once push is reduced, work on controlled draw or straight shot.',
      retest_protocol: {
        shot_count: 25,
        club: 'Same club',
        focus_metrics: ['club_path', 'face_angle', 'start_direction'],
        success_criteria: 'Ball starts within ±5 yards of target',
        notes: 'Use alignment sticks for every shot.',
      },
      drill_recommendations: [
        {
          id: 'push-1',
          name: 'Push Fix Alignment and Path Drill',
          category: 'club_path_control',
          difficulty: 'beginner',
          why_this_matches: 'Alignment and path correction are the primary fixes for a push pattern',
          youtube_search_query: 'golf push fix alignment club path inside out face angle drill',
          youtube_search_url: 'https://www.youtube.com/results?search_query=golf+push+fix+alignment+club+path+inside+out+face+angle+drill',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  driver_attack_angle_down: [
    {
      id: 'driver-upswing-drill',
      diagnosis_category: 'driver_attack_angle_down',
      name: 'Driver Setup — Positive Attack Angle',
      goal: 'Change driver attack angle from downward to upward to maximize carry and reduce spin',
      data_point_being_improved: 'attack_angle',
      why_it_matters:
        'Hitting up on the driver (+1° to +4°) reduces spin and increases launch, adding 10-20 yards of carry without changing club speed.',
      skill_level: 'beginner',
      setup:
        'Ball teed high (top half above driver crown). Ball positioned off left heel. Shoulders tilted slightly away from target.',
      drill_steps: [
        'Tee the ball so half the ball is above the driver crown.',
        'Move the ball 1-2 inches forward in your stance (off left heel).',
        'At address, tilt your trail shoulder slightly lower than normal — this builds in an upswing attack angle.',
        'Hit 10 shots at 75% speed focusing on the feeling of sweeping up through the ball.',
        'Hit 20 shots at full speed maintaining the setup. Check attack angle on monitor.',
        'Target: attack angle moves to 0° or positive.',
      ],
      ball_count: 35,
      intensity: 'medium',
      feedback_metric: 'attack_angle, launch_angle, spin_rate, carry_distance',
      success_criteria: 'Attack angle reaches 0° or positive. Spin rate reduces. Carry increases.',
      common_mistakes: [
        'Hanging back too much causing a thin strike',
        'Flipping at the ball trying to help it up',
        'Ball too far forward causing a miss to the right',
      ],
      progression:
        'Once attack angle is positive, optimize tee height and ball speed for maximum carry distance.',
      retest_protocol: {
        shot_count: 20,
        club: 'Driver',
        focus_metrics: ['attack_angle', 'spin_rate', 'launch_angle', 'carry_distance'],
        success_criteria: 'Attack angle +1° or better, spin reduced by 300+ rpm',
        notes: 'Compare carry distance before and after.',
      },
      drill_recommendations: [
        {
          id: 'driver-upswing-1',
          name: 'Driver Upswing Attack Angle Drill',
          category: 'driver_setup',
          difficulty: 'beginner',
          why_this_matches:
            'Setup adjustments (tee height, ball position, shoulder tilt) are the fastest way to create positive attack angle',
          youtube_search_query:
            'golf driver attack angle positive upswing tee height ball position drill',
          youtube_search_url:
            'https://www.youtube.com/results?search_query=golf+driver+attack+angle+positive+upswing+tee+height+ball+position+drill',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 25,
    },
  ],
  launch_angle_low: [
    {
      id: 'low-launch-fix',
      diagnosis_category: 'launch_angle_low',
      name: 'Launch Angle Fix — Ball Position and Loft Delivery',
      goal: 'Increase launch angle to reach the target window for the club',
      data_point_being_improved: 'launch_angle_vertical',
      why_it_matters:
        'Too-low launch angle reduces carry distance and makes the ball prone to running through greens.',
      skill_level: 'beginner',
      setup:
        'One club (same as session). Alignment stick. Check ball position before starting.',
      drill_steps: [
        'Check ball position — move it 1-2 inches forward of current position.',
        'Check grip — an overly strong grip can close the face and reduce dynamic loft.',
        'Hit 10 shots at 70% speed feeling the ball launch higher.',
        'Hit 20 shots at full speed maintaining the setup change.',
        'Check launch angle after each block of 10.',
      ],
      ball_count: 30,
      intensity: 'low',
      feedback_metric: 'launch_angle_vertical, dynamic_loft, carry_distance',
      success_criteria: 'Launch angle moves into target window for club category',
      common_mistakes: [
        'Moving ball too far forward causing thin contact',
        'Helping the ball up with the hands (flipping)',
      ],
      progression:
        'Once launch is in range, check spin rate — increasing launch without changing spin loft is ideal.',
      retest_protocol: {
        shot_count: 20,
        club: 'Same club',
        focus_metrics: ['launch_angle_vertical', 'dynamic_loft', 'carry_distance'],
        success_criteria: 'Launch angle within target window',
        notes: 'Compare carry distance. Launch improvements often add 5-15 yards.',
      },
      drill_recommendations: [
        {
          id: 'low-launch-1',
          name: 'Ball Position Launch Angle Fix',
          category: 'launch_window_control',
          difficulty: 'beginner',
          why_this_matches:
            'Ball position is the primary setup variable controlling launch angle',
          youtube_search_query:
            'golf low launch angle fix ball position grip dynamic loft iron driver',
          youtube_search_url:
            'https://www.youtube.com/results?search_query=golf+low+launch+angle+fix+ball+position+grip+dynamic+loft+iron+driver',
          warning: null,
          curated_video_id: null,
          coach_channel: null,
        },
      ],
      estimated_duration_minutes: 20,
    },
  ],
  optimal: [],
  low_point_behind: [],
};

export function getRoutineForDiagnosis(
  category: DiagnosisCategory,
  skillLevel: SkillLevel,
): TrainingRoutine | undefined {
  const routines = TRAINING_ROUTINES[category];
  if (!routines || routines.length === 0) return undefined;
  return (
    routines.find((r) => r.skill_level === skillLevel) ??
    routines[0]
  );
}
