/**
 * GrowthOS — AI Strategist API Route (§31)
 *
 * POST /api/growth/ai
 *
 * Accepts a task ID + strategist context, builds a claim-safe prompt, and
 * returns a draft marketing asset generated by the configured AI provider.
 * If no AI key is configured the route returns a structured template fallback
 * so the module is useful immediately in development.
 *
 * Security:
 * - API keys are server-side only (never sent to client)
 * - taskId is validated against the STRATEGIST_TASKS catalog; unknown ids → 400
 * - All user-supplied context is sanitized (prompt-injection defense-in-depth)
 * - IP-based rate limit: 15 requests / 60 s (matches ai-coach pattern)
 * - provider.ts is only imported here (server route), never from client files
 */

import { NextRequest, NextResponse } from 'next/server';
import { checkRateLimit, rateLimitResponse } from '@/lib/rate-limit';
import {
  STRATEGIST_TASKS,
  buildStrategistPrompt,
  strategistFallback,
  type StrategistContext,
  type StrategistTaskId,
} from '@/lib/growth/ai/strategist';
import { generateMarketingDraft } from '@/lib/growth/ai/provider';

// ── Handler ───────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  // IP-based rate limiting (distributed when Upstash is configured)
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown';
  const rl = await checkRateLimit(`${ip}:growth-ai`, { limit: 15, windowMs: 60_000 });
  if (!rl.allowed) {
    return rateLimitResponse();
  }

  // Parse request body
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid request body.' }, { status: 400 });
  }

  if (typeof body !== 'object' || body === null) {
    return NextResponse.json({ error: 'Request body must be a JSON object.' }, { status: 400 });
  }

  const { taskId, context } = body as { taskId?: unknown; context?: unknown };

  // Validate taskId is one of the known STRATEGIST_TASKS ids
  if (typeof taskId !== 'string' || !taskId.trim()) {
    return NextResponse.json({ error: 'Missing taskId.' }, { status: 400 });
  }
  const validIds = STRATEGIST_TASKS.map((t) => t.id);
  if (!validIds.includes(taskId as StrategistTaskId)) {
    return NextResponse.json(
      { error: `Unknown taskId "${taskId}". Valid values: ${validIds.join(', ')}.` },
      { status: 400 },
    );
  }

  // context is optional — treat missing/non-object as empty
  const ctx: StrategistContext =
    typeof context === 'object' && context !== null ? (context as StrategistContext) : {};

  // Build the structured prompt (context is sanitized inside buildStrategistPrompt)
  const { system, user } = buildStrategistPrompt(taskId as StrategistTaskId, ctx);

  // Call the AI provider (degrades gracefully to a template fallback when no key is set)
  const result = await generateMarketingDraft(
    { system, user, maxTokens: 900 },
    strategistFallback(taskId as StrategistTaskId, ctx),
  );

  return NextResponse.json({
    text: result.text,
    provider: result.provider,
    isFallback: result.isFallback,
  });
}
