'use client';

// ============================================================
// GrowthOS — AI Strategist — Interactive UI (§31)
// ------------------------------------------------------------
// Task picker + context form + output panel + agent architecture.
// All AI output is DRAFT-first and clearly labeled. No AI key
// required — a structured template fallback is shown instead.
// provider.ts is SERVER-ONLY; this file never imports it.
// ============================================================

import { useState } from 'react';
import {
  Sparkles, Copy, Check, AlertTriangle, ShieldAlert, ChevronDown, ChevronUp,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { SectionCard, Badge } from '../_components/ui';
import {
  STRATEGIST_TASKS,
  type StrategistTaskId,
  type StrategistContext,
} from '@/lib/growth/ai/strategist';
import { AI_AGENTS, GLOBAL_AGENT_GUARDRAILS } from '@/lib/growth/ai/agents';

// ── Types ─────────────────────────────────────────────────────

interface GenerateResult {
  text: string;
  provider: 'openai' | 'anthropic' | 'google' | 'fallback';
  isFallback: boolean;
}

// ── Category grouping ─────────────────────────────────────────

const CATEGORY_LABELS: Record<string, string> = {
  plan: 'Planning',
  acquire: 'Acquisition',
  convert: 'Conversion',
  expand: 'Expansion',
  brand: 'Brand',
};

// ── Context field definitions ─────────────────────────────────

const TEXT_FIELDS: Array<{ key: keyof StrategistContext; label: string; placeholder: string; multi?: boolean }> = [
  { key: 'product', label: 'Product / app name', placeholder: 'e.g. SwingIQ' },
  { key: 'audience', label: 'Target audience', placeholder: 'e.g. Amateur golfers, age 30–55' },
  { key: 'valueProp', label: 'Value proposition', placeholder: 'e.g. Track every shot and fix your swing faster' },
  { key: 'goal', label: 'Current goal', placeholder: 'e.g. Increase free-to-paid conversion' },
  { key: 'channel', label: 'Channel', placeholder: 'e.g. Email, TikTok, Google Ads' },
  { key: 'funnelStage', label: 'Funnel stage', placeholder: 'e.g. Awareness, Activation, Retention' },
  { key: 'tone', label: 'Tone of voice', placeholder: 'e.g. Encouraging, direct, data-driven' },
  { key: 'offer', label: 'Offer / incentive', placeholder: 'e.g. 14-day free trial, 20% off annual' },
  { key: 'features', label: 'Key features', placeholder: 'e.g. AI shot tracking, video analysis, drill library', multi: true },
  { key: 'constraints', label: 'Constraints / notes', placeholder: 'e.g. No free-tier copy, avoid "best in class"', multi: true },
];

const EMPTY_CONTEXT: StrategistContext = {
  product: '',
  audience: '',
  valueProp: '',
  goal: '',
  channel: '',
  funnelStage: '',
  tone: '',
  offer: '',
  features: '',
  constraints: '',
};

// ── Confidence badge helper ───────────────────────────────────

function ConfidenceBadge({ confidence }: { confidence: string }) {
  const cls =
    confidence === 'high'
      ? 'bg-success/10 border-success/30 text-success-text'
      : confidence === 'medium'
      ? 'bg-primary/10 border-primary/30 text-link'
      : 'bg-muted border-border text-muted-foreground';
  return <Badge className={cls}>{confidence} confidence</Badge>;
}

// ── Provider label ────────────────────────────────────────────

function ProviderLine({ provider, isFallback }: { provider: GenerateResult['provider']; isFallback: boolean }) {
  if (isFallback) {
    return (
      <p className="text-xs text-muted-foreground mt-2">
        Template (no AI key configured — set{' '}
        <code className="text-muted-foreground">AI_PROVIDER</code> +{' '}
        <code className="text-muted-foreground">OPENAI_API_KEY</code>,{' '}
        <code className="text-muted-foreground">ANTHROPIC_API_KEY</code>, or{' '}
        <code className="text-muted-foreground">GOOGLE_AI_API_KEY</code> in{' '}
        <code className="text-muted-foreground">apps/web/.env.local</code> to generate AI drafts)
      </p>
    );
  }
  return (
    <p className="text-xs text-muted-foreground mt-2">
      Generated by <span className="text-foreground font-medium">{provider}</span>
    </p>
  );
}

// ── Main component ────────────────────────────────────────────

export function AiStrategistContent() {
  const [selectedTask, setSelectedTask] = useState<StrategistTaskId>('campaign-ideas');
  const [context, setContext] = useState<StrategistContext>(EMPTY_CONTEXT);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<GenerateResult | null>(null);
  const [copied, setCopied] = useState(false);
  const [agentExpandedId, setAgentExpandedId] = useState<string | null>(null);

  // Group tasks by category
  const groupedTasks = STRATEGIST_TASKS.reduce<Record<string, typeof STRATEGIST_TASKS>>(
    (acc, t) => {
      (acc[t.category] ??= []).push(t);
      return acc;
    },
    {},
  );

  function setField(key: keyof StrategistContext, value: string) {
    setContext((prev) => ({ ...prev, [key]: value }));
  }

  async function handleGenerate() {
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch('/api/growth/ai', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ taskId: selectedTask, context }),
      });

      if (!res.ok) {
        const data = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(data.error ?? `Request failed (${res.status})`);
      }

      const data = (await res.json()) as GenerateResult;
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unexpected error.');
    } finally {
      setLoading(false);
    }
  }

  async function handleCopy() {
    if (!result) return;
    await navigator.clipboard.writeText(result.text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const selectedTaskMeta = STRATEGIST_TASKS.find((t) => t.id === selectedTask);

  return (
    <div className="space-y-6">
      {/* Honesty callout */}
      <div className="rounded-xl border border-primary/30 bg-primary/10 p-4">
        <div className="flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 text-link shrink-0 mt-0.5" />
          <div className="text-sm text-link/90">
            <p className="font-semibold text-link">Draft-first &amp; claim-safe</p>
            <p className="mt-1 text-xs leading-relaxed">
              Every output is a <strong>DRAFT for your review</strong> — nothing auto-publishes.
              The AI is instructed never to fabricate metrics, testimonials, or unsupported claims.
              If no AI key is configured you still get a structured starting template.
              <strong className="block mt-1">Verify every claim before any asset goes live.</strong>
            </p>
          </div>
        </div>
      </div>

      {/* Generator + output — side-by-side on lg */}
      <div className="grid lg:grid-cols-2 gap-5 items-start">

        {/* Left: task picker + context form */}
        <div className="space-y-5">
          {/* Task picker */}
          <SectionCard title="1. Choose a task" icon={Sparkles}>
            <div className="space-y-4">
              {Object.entries(groupedTasks).map(([cat, tasks]) => (
                <div key={cat}>
                  <p className="text-2xs font-semibold uppercase tracking-wider text-muted-foreground mb-2">
                    {CATEGORY_LABELS[cat] ?? cat}
                  </p>
                  <div className="flex flex-col gap-1.5">
                    {tasks.map((task) => (
                      <button
                        key={task.id}
                        onClick={() => setSelectedTask(task.id)}
                        className={cn(
                          'w-full text-left rounded-lg border px-3 py-2.5 transition-colors',
                          selectedTask === task.id
                            ? 'border-success/50 bg-success/10 text-foreground'
                            : 'border-border bg-muted/40 text-foreground hover:border-border hover:bg-muted/60',
                        )}
                      >
                        <p className="text-sm font-medium">{task.label}</p>
                        <p className="text-xs text-muted-foreground mt-0.5">{task.description}</p>
                      </button>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Context form */}
          <SectionCard title="2. Add context (optional but improves output)">
            <div className="space-y-3">
              {TEXT_FIELDS.map(({ key, label, placeholder, multi }) => (
                <div key={key}>
                  <label className="block text-xs text-muted-foreground mb-1">{label}</label>
                  {multi ? (
                    <textarea
                      rows={2}
                      value={context[key] ?? ''}
                      onChange={(e) => setField(key, e.target.value)}
                      placeholder={placeholder}
                      className={cn(
                        'w-full rounded-lg border border-border bg-muted px-3 py-2',
                        'text-sm text-foreground placeholder:text-muted-foreground/70',
                        'focus:outline-none focus:ring-1 focus:ring-success/50 focus:border-success/50',
                        'resize-none',
                      )}
                    />
                  ) : (
                    <input
                      type="text"
                      value={context[key] ?? ''}
                      onChange={(e) => setField(key, e.target.value)}
                      placeholder={placeholder}
                      className={cn(
                        'w-full rounded-lg border border-border bg-muted px-3 py-2',
                        'text-sm text-foreground placeholder:text-muted-foreground/70',
                        'focus:outline-none focus:ring-1 focus:ring-success/50 focus:border-success/50',
                      )}
                    />
                  )}
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Generate button */}
          <button
            onClick={handleGenerate}
            disabled={loading}
            className={cn(
              'w-full flex items-center justify-center gap-2 rounded-xl px-4 py-3 font-semibold text-sm transition-colors',
              loading
                ? 'bg-success/40 text-success-text cursor-not-allowed'
                : 'bg-success hover:bg-success text-white',
            )}
          >
            <Sparkles className="w-4 h-4" />
            {loading ? 'Generating…' : `Generate draft — ${selectedTaskMeta?.label ?? selectedTask}`}
          </button>

          {error && (
            <div className="rounded-lg border border-error/30 bg-error/10 px-4 py-3 text-sm text-error-text">
              {error}
            </div>
          )}
        </div>

        {/* Right: output panel */}
        <div>
          {result ? (
            <SectionCard title="Draft output">
              {/* DRAFT badge + provider + copy */}
              <div className="flex items-center justify-between gap-3 mb-3 flex-wrap">
                <div className="flex items-center gap-2 flex-wrap">
                  <Badge className="bg-primary/15 border-primary/30 text-link">
                    DRAFT — review before use
                  </Badge>
                  {result.isFallback && (
                    <Badge className="bg-muted border-border text-muted-foreground">Template</Badge>
                  )}
                </div>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
                >
                  {copied ? (
                    <><Check className="w-3.5 h-3.5 text-success-text" /> Copied</>
                  ) : (
                    <><Copy className="w-3.5 h-3.5" /> Copy</>
                  )}
                </button>
              </div>

              {/* Output text */}
              <div className="rounded-lg border border-border bg-muted/60 p-4">
                <pre className="text-sm text-foreground whitespace-pre-wrap leading-relaxed font-sans">
                  {result.text}
                </pre>
              </div>

              <ProviderLine provider={result.provider} isFallback={result.isFallback} />
            </SectionCard>
          ) : (
            <div className="rounded-xl border border-dashed border-border bg-card/50 p-10 text-center h-full min-h-[200px] flex flex-col items-center justify-center gap-3">
              <Sparkles className="w-8 h-8 text-muted-foreground/70" />
              <p className="text-sm font-semibold text-muted-foreground">Your draft will appear here</p>
              <p className="text-xs text-muted-foreground/70 max-w-xs">
                Select a task, add context, then click Generate draft.
              </p>
            </div>
          )}
        </div>
      </div>

      {/* AI agent architecture */}
      <SectionCard title="AI agent architecture">
        <div className="space-y-2 mb-5">
          <p className="text-xs text-muted-foreground leading-relaxed">
            GrowthOS includes 15 specialised marketing agents. Each is a declarative spec — they
            produce drafts for human review; <strong className="text-foreground">no agent can take
            any external-facing action without explicit approval.</strong>
          </p>
        </div>

        <div className="space-y-2">
          {AI_AGENTS.map((ag) => {
            const isOpen = agentExpandedId === ag.id;
            return (
              <div key={ag.id} className="rounded-lg border border-border bg-muted/40 overflow-hidden">
                <button
                  onClick={() => setAgentExpandedId(isOpen ? null : ag.id)}
                  className="w-full flex items-center justify-between gap-3 px-4 py-3 text-left hover:bg-muted/60 transition-colors"
                >
                  <div className="flex items-center gap-3 min-w-0">
                    <p className="text-sm font-medium text-foreground truncate">{ag.name}</p>
                    <ConfidenceBadge confidence={ag.confidence} />
                  </div>
                  {isOpen
                    ? <ChevronUp className="w-4 h-4 text-muted-foreground shrink-0" />
                    : <ChevronDown className="w-4 h-4 text-muted-foreground shrink-0" />}
                </button>

                {isOpen && (
                  <div className="border-t border-border/60 px-4 py-4 space-y-3 text-xs">
                    <p className="text-foreground leading-relaxed">{ag.purpose}</p>

                    <div className="grid sm:grid-cols-2 gap-3">
                      <div>
                        <p className="text-2xs uppercase tracking-wider text-muted-foreground mb-1">Inputs</p>
                        <ul className="space-y-0.5">
                          {ag.inputs.map((inp) => (
                            <li key={inp} className="text-muted-foreground">· {inp}</li>
                          ))}
                        </ul>
                      </div>
                      <div>
                        <p className="text-2xs uppercase tracking-wider text-muted-foreground mb-1">Outputs</p>
                        <ul className="space-y-0.5">
                          {ag.outputs.map((out) => (
                            <li key={out} className="text-muted-foreground">· {out}</li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div>
                      <p className="text-2xs uppercase tracking-wider text-muted-foreground mb-1">Review requirements</p>
                      <p className="text-muted-foreground">{ag.reviewRequirements}</p>
                    </div>

                    <div>
                      <p className="text-2xs uppercase tracking-wider text-muted-foreground mb-1">Suggested next action</p>
                      <p className="text-muted-foreground">{ag.suggestedNextAction}</p>
                    </div>

                    <div>
                      <p className="text-2xs uppercase tracking-wider text-muted-foreground mb-1.5">Guardrails (inherited)</p>
                      <ul className="space-y-0.5">
                        {ag.guardrails.map((g) => (
                          <li key={g} className="text-muted-foreground">· {g}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Global guardrails callout */}
        <div className="mt-5 rounded-lg border border-error/25 bg-error/8 p-4">
          <div className="flex items-start gap-3">
            <ShieldAlert className="w-5 h-5 text-error-text shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-semibold text-error-text mb-2">The AI layer will never:</p>
              <ul className="space-y-1">
                {GLOBAL_AGENT_GUARDRAILS.map((g) => (
                  <li key={g} className="text-xs text-error-text/80">· {g}</li>
                ))}
              </ul>
              <p className="text-xs text-error-text/70 mt-3 leading-relaxed">
                Human approval is required before any external-facing action is taken.
                All AI output stays inside GrowthOS as a draft until you explicitly act on it.
              </p>
            </div>
          </div>
        </div>
      </SectionCard>
    </div>
  );
}
