// ============================================================
// SwingVantage — Data-point education pages. One page per
// meaningful analysis data point, mapped to the real fault
// ontology (lib/faults) where a matching fault exists. Original
// instruction; extensible (add an entry → page + sitemap row).
// ============================================================

import type { LearnEntry } from './types';

const REVIEWED = '2026-06-08';
const ALL_BALL_SPORTS: LearnEntry['sports'] = ['golf', 'baseball', 'softball_slow', 'softball_fast', 'tennis'];

const TEMPO: LearnEntry = {
  id: 'tempo',
  slug: 'tempo',
  kind: 'data-point',
  title: 'Tempo',
  category: 'sequencing',
  sports: ['golf', 'baseball', 'softball_slow', 'softball_fast', 'tennis', 'pickleball', 'padel'],
  difficultyLevels: ['beginner', 'intermediate', 'advanced'],
  status: 'published',
  descriptionShort: 'The overall rhythm and ratio of your backswing to your downswing — the timing that lets everything arrive together.',
  explanationBeginner: 'Tempo is the rhythm of your swing: how smooth and consistent it is from start to finish. It is not about being slow — fast swings can have great tempo. It is about repeating the same rhythm so your body and the club arrive at contact together.',
  explanationAdvanced: 'Tempo is best understood as the backswing-to-downswing time ratio (a roughly 3:1 ratio is common among efficient golfers) and the consistency of that ratio swing to swing. Stable tempo protects sequencing under pressure; tempo that speeds up from the top is a common trigger for over-the-top and casting.',
  whyItMatters: 'Consistent tempo is the cheapest consistency you can buy. When rhythm repeats, your sequence repeats, and contact and direction tighten — even without changing a single position.',
  detectionLogic: 'SwingVantage estimates relative timing of the backswing and downswing from video and flags rushes from the top or a jerky transition. It is a timing estimate from frames, not a precise measurement.',
  evidenceBasis: 'estimated',
  confidenceExplanation: 'Tempo is inferred from frame timing, so it is estimated. A clear, full-swing clip at a steady frame rate improves the read.',
  goodPattern: 'A smooth, unhurried transition where the change of direction is gradual and the same rhythm repeats every swing.',
  poorPatterns: ['Rushing the downswing from the top', 'A jerky, snatchy transition', 'Tempo that changes with club or pressure', 'Decelerating into contact'],
  commonCauses: ['Trying to hit hard', 'Tension in the hands and shoulders', 'No rhythm reference or count', 'Anxiety over the result'],
  symptoms: ['The swing feels rushed or out of control', 'You feel "quick" at the top', 'Effort feels high but speed feels low'],
  ballFlightOrResult: ['Rushed tempo: a two-way miss and inconsistent contact', 'Smooth tempo: a tighter, more repeatable pattern'],
  selfChecks: [
    { label: 'Count it', detail: 'Hum or count a simple "one—two" with a longer backswing and a quicker through-swing. Inconsistent counts mean inconsistent tempo.' },
    { label: 'Same finish', detail: 'Good tempo usually produces a balanced, repeatable finish. If your finish varies a lot, tempo is likely varying too.' },
  ],
  videoUploadTips: ['Capture the full swing start to finish at a steady frame rate.', 'Avoid slow-motion capture for tempo reads unless the app asks for it.'],
  drills: [
    { name: 'Three-to-One Count', goal: 'Stabilize the backswing/downswing ratio', how: 'Count "one-two-three" going back and "one" coming down on every rep, keeping the count identical.', feel: 'A patient top and a free release', reps: '10 swings', equipment: 'None', level: 'beginner' },
    { name: 'Feet-Together Rhythm', goal: 'Smooth out a snatchy transition', how: 'Hit soft shots with your feet together. Balance forces a smoother, rhythmic motion.', feel: 'Unhurried change of direction', reps: '3 sets of 6', equipment: 'None or a tee', level: 'intermediate' },
  ],
  practicePlan: ['Day 1–3: Three-to-One Count on slow swings.', 'Day 4–6: Feet-Together Rhythm into soft shots.', 'Day 7: Retest and compare contact consistency.'],
  progressionLadder: ['Repeat a count on slow swings', 'Keep it at full speed', 'Keep it under pressure in play'],
  relatedFaultIds: ['over_the_top', 'casting_hands'],
  relatedDataPointSlugs: ['over-the-top', 'casting'],
  relatedConceptSlugs: ['swing-plane'],
  relatedCoachStyleIds: ['feel'],
  drillFamilies: ['tempo & sequencing'],
  seoTitle: 'Swing Tempo: What Good Rhythm Looks Like (and Drills)',
  seoDescription: 'What swing tempo is, why a consistent backswing-to-downswing ratio matters, how SwingVantage estimates it, and simple drills to smooth your rhythm.',
  faqs: [
    { question: 'Does good tempo mean swinging slowly?', answer: 'No. Tempo is about a repeatable rhythm and ratio, not raw speed. Fast swings can have excellent tempo; the goal is to repeat the same rhythm every time.' },
    { question: 'What is a good tempo ratio?', answer: 'Many efficient golfers sit near a 3:1 backswing-to-downswing time ratio, but the most important thing is that yours stays consistent swing to swing.' },
  ],
  lastReviewedAt: REVIEWED,
};

const POSTURE: LearnEntry = {
  id: 'posture',
  slug: 'posture',
  kind: 'data-point',
  title: 'Posture',
  category: 'setup',
  sports: ALL_BALL_SPORTS,
  difficultyLevels: ['beginner', 'intermediate', 'advanced'],
  status: 'published',
  descriptionShort: 'How you set your spine, hips, and athletic angles at address — the foundation the whole motion rotates around.',
  explanationBeginner: 'Posture is how you stand at setup: the tilt of your spine, the bend from your hips, and your athletic balance. Good posture gives your body room to turn and return to the ball the same way every time.',
  explanationAdvanced: 'Setup posture establishes the rotational axis and the space the arms need to deliver the club on plane. Loss of posture (standing up, early extension, or slumping) during the swing changes that space and forces last-instant compensations in path and low point.',
  whyItMatters: 'Posture sets up everything downstream — rotation, plane, and low-point control all depend on keeping your athletic angles. Many "swing" faults are really posture faults in disguise.',
  detectionLogic: 'SwingVantage estimates spine tilt and hip hinge at setup from video and watches whether you hold those angles or lose posture during the swing. It is a visual estimate.',
  evidenceBasis: 'estimated',
  confidenceExplanation: 'Posture is read from setup and mid-swing frames, so it is estimated. A clean down-the-line view is the most useful for this.',
  goodPattern: 'Athletic hip hinge, neutral spine, weight balanced over the middle of the feet, and angles that hold through the turn.',
  poorPatterns: ['Slumped or rounded back at setup', 'Too upright with little hip hinge', 'Standing up out of posture in the downswing', 'Weight on heels or toes at address'],
  commonCauses: ['No setup routine', 'Mobility limits in the hips or upper back', 'Reaching for the ball or standing too far away', 'Copying a static photo instead of an athletic stance'],
  symptoms: ['You feel cramped or have to make room in the downswing', 'You feel off-balance at address', 'Lower back fatigue after sessions'],
  ballFlightOrResult: ['Lost posture: thin/fat contact and a two-way miss', 'Held posture: more consistent strike and path'],
  selfChecks: [
    { label: 'Mirror hinge', detail: 'In a mirror, hinge from the hips (not the waist) until your arms hang under your shoulders. That hanging point is your athletic posture.' },
    { label: 'Hold check', detail: 'Film a swing down the line and watch your spine angle from setup to impact — it should stay similar, not stand up.' },
  ],
  videoUploadTips: ['Film down the line at hip height to judge spine and hip angles.', 'Wear fitted clothing so your back and hip lines are visible.'],
  drills: [
    { name: 'Hinge-and-Hang', goal: 'Find a repeatable athletic posture', how: 'Stand tall, hinge from the hips until your arms hang naturally, add a slight knee flex. Repeat 10 times to groove the feel.', feel: 'Hinged from the hips, athletic and balanced', reps: '10 reps', equipment: 'Mirror', level: 'beginner' },
    { name: 'Wall-Behind Hold', goal: 'Stop standing up in the downswing', how: 'Set up with your hips lightly touching a wall behind you and make slow swings keeping contact with the wall until well into the downswing.', feel: 'Hips staying back, posture maintained', reps: '10 slow swings', equipment: 'Wall', level: 'intermediate' },
  ],
  practicePlan: ['Day 1–2: Hinge-and-Hang reps.', 'Day 3–5: Wall-Behind Hold slow swings.', 'Day 6: Normal swings keeping the angle.', 'Day 7: Retest and compare posture from setup to impact.'],
  progressionLadder: ['Build posture in a mirror', 'Hold it on slow swings', 'Hold it at speed', 'Keep it in play'],
  relatedFaultIds: ['early_extension'],
  relatedDataPointSlugs: ['early-extension', 'rotation'],
  relatedConceptSlugs: ['weight-distribution', 'swing-plane'],
  relatedCoachStyleIds: ['technical'],
  drillFamilies: ['setup & posture'],
  seoTitle: 'Golf Posture & Setup: Spine Angle, Hip Hinge, and Drills',
  seoDescription: 'How proper posture sets up rotation, plane, and contact — plus how SwingVantage detects lost posture and drills to hold your athletic angles.',
  faqs: [
    { question: 'What is good posture in a swing?', answer: 'An athletic hip hinge with a neutral spine, balanced weight, and arms hanging under the shoulders — angles you can hold from setup through impact.' },
    { question: 'How do I know if I lose posture?', answer: 'Film down the line and compare your spine angle at setup and at impact. If you stand up or your hips move toward the ball, you are losing posture (often called early extension).' },
  ],
  lastReviewedAt: REVIEWED,
};

const ROTATION: LearnEntry = {
  id: 'rotation',
  slug: 'rotation',
  kind: 'data-point',
  title: 'Rotation (Hip & Shoulder Turn)',
  category: 'motion',
  sports: ALL_BALL_SPORTS,
  difficultyLevels: ['beginner', 'intermediate', 'advanced'],
  status: 'published',
  descriptionShort: 'How much, and in what order, your hips and shoulders turn — the rotary engine behind effortless power.',
  explanationBeginner: 'Rotation is how your hips and shoulders turn back and through. Power comes from turning your body, not just swinging your arms. Good rotation lets you create speed without forcing it.',
  explanationAdvanced: 'Rotation quality is about both range and sequence: a full shoulder turn over more stable hips builds coil (separation), and the downswing unwinds hips-first, then torso, then arms. Stalled hips or an arms-dominant motion both leak speed and push the club off plane.',
  whyItMatters: 'Rotation is the biggest engine of speed available to most players, and the order it unwinds in controls both power and path. Improve rotation and you gain distance without swinging harder.',
  detectionLogic: 'SwingVantage estimates shoulder and hip turn ranges from video and infers the unwinding order from how the body moves in transition. Ranges are visual estimates unless paired with sensor data.',
  evidenceBasis: 'estimated',
  confidenceExplanation: 'Turn amounts and sequence are inferred from 2D video, so they are estimated. A down-the-line and a face-on clip together give the best read.',
  goodPattern: 'A full shoulder turn against more stable hips going back, then a downswing that unwinds from the ground up — hips, torso, arms, club.',
  poorPatterns: ['Arms-only swing with little body turn', 'Hips that stall and stop rotating through impact', 'Hips and shoulders turning together with no separation', 'Over-rotating and losing posture'],
  commonCauses: ['Trying to generate power with the arms', 'Mobility limits in the hips or thoracic spine', 'Poor sequencing — upper body starting the downswing', 'No stable lower-body base'],
  symptoms: ['The swing feels "all arms"', 'You feel blocked or stuck at impact', 'Power feels forced rather than free'],
  ballFlightOrResult: ['Stalled rotation: blocks, flips, and lost speed', 'Good rotation: more speed and a more reliable path'],
  selfChecks: [
    { label: 'Cross-arm turn', detail: 'Cross your arms on your chest and make a turn. Feel a fuller shoulder turn over quieter hips — that is the coil you want.' },
    { label: 'Lead-hip clearance', detail: 'On slow swings, feel your lead hip rotating open through impact rather than sliding or stalling.' },
  ],
  videoUploadTips: ['Film both face-on and down the line if possible.', 'Fitted clothing helps the body lines read clearly.'],
  drills: [
    { name: 'Cross-Arm Coil', goal: 'Build separation (shoulders over hips)', how: 'Arms crossed on chest, turn back feeling shoulders out-turn the hips, then unwind hips-first. No club.', feel: 'Stretch between ribcage and belt going back', reps: '10 reps', equipment: 'None', level: 'beginner' },
    { name: 'Lead-Leg Brace', goal: 'Stop the hip stall', how: 'Make swings focusing on posting into a firm lead leg so the hips can rotate fully open through contact.', feel: 'Rotating against a braced front leg', reps: '10 swings', equipment: 'None', level: 'advanced' },
  ],
  practicePlan: ['Day 1–3: Cross-Arm Coil reps.', 'Day 4–6: Lead-Leg Brace into soft shots.', 'Day 7: Retest and compare speed and impact feel.'],
  progressionLadder: ['Feel separation with no club', 'Add it to slow swings', 'Keep the sequence at speed', 'Trust it in play'],
  relatedFaultIds: ['hip_stall', 'poor_hip_shoulder_separation', 'open_hips_early'],
  relatedDataPointSlugs: ['early-extension', 'over-the-top'],
  relatedConceptSlugs: ['weight-distribution', 'swing-plane'],
  relatedCoachStyleIds: ['data', 'technical'],
  drillFamilies: ['rotation & separation', 'lower-body sequencing'],
  seoTitle: 'Swing Rotation: Hip & Shoulder Turn, Separation, and Drills',
  seoDescription: 'How hip and shoulder rotation and their sequence create effortless power, how SwingVantage estimates turn and separation, plus drills to fix a stall.',
  faqs: [
    { question: 'What is separation in the swing?', answer: 'Separation (or "X-factor") is the difference between your shoulder turn and hip turn at the top. More separation stores coil you can release for speed, as long as the downswing unwinds hips-first.' },
    { question: 'Why do my hips stall through impact?', answer: 'Often it is a weak or soft lead leg, poor sequencing, or simply never feeling the lead hip clear. Posting into a firm lead leg lets the hips keep rotating instead of stopping.' },
  ],
  lastReviewedAt: REVIEWED,
};

const EARLY_EXTENSION: LearnEntry = {
  id: 'early-extension',
  slug: 'early-extension',
  kind: 'data-point',
  title: 'Early Extension',
  category: 'motion',
  sports: ['golf', 'baseball', 'softball_slow', 'softball_fast'],
  difficultyLevels: ['intermediate', 'advanced'],
  status: 'published',
  descriptionShort: 'When your hips thrust toward the ball and you stand up out of posture in the downswing — a top cause of inconsistent contact.',
  explanationBeginner: 'Early extension is when your hips push toward the ball and your body stands up too soon on the way down. It steals the space your arms need, so you have to make last-second adjustments to find the ball.',
  explanationAdvanced: 'Early extension is a loss of the setup hip hinge in transition — the pelvis thrusts toward the target line and the spine extends early. It crowds the arms, pushes the hands up and out, and commonly produces blocks, hooks, and thin/heavy strike from a moving low point.',
  whyItMatters: 'It is one of the most common amateur faults and a direct cause of an inconsistent low point and a two-way miss. Holding posture frees the arms and steadies contact.',
  detectionLogic: 'SwingVantage compares your hip/torso position at setup and in the downswing from a down-the-line view and flags the hips moving toward the ball and the torso standing up. This maps to the fault ontology entry "early_extension."',
  evidenceBasis: 'estimated',
  confidenceExplanation: 'Read from a 2D down-the-line clip, so it is estimated. The right camera angle (true down the line, hip height) is essential for an honest read.',
  goodPattern: 'Hips holding their hinge and rotating (not thrusting toward the ball), keeping space for the arms to drop and deliver on plane.',
  poorPatterns: ['Hips thrusting toward the ball in transition', 'Torso standing up before impact', 'Hands getting "stuck" behind the body, forcing a flip', 'Belt line moving closer to the ball through the downswing'],
  commonCauses: ['Pushing off the ground vertically instead of rotating', 'Limited hip mobility or weak rotational pattern', 'Starting the downswing with the upper body', 'Setup too close to the ball'],
  symptoms: ['You feel "stuck" with no room for your arms', 'You flip the hands to save contact', 'Lower-back tiredness after sessions'],
  ballFlightOrResult: ['Blocks to the right and big hooks (two-way miss)', 'Thin and heavy strikes from a moving low point'],
  selfChecks: [
    { label: 'Wall test', detail: 'Set up with your hips lightly touching a wall behind you; make slow downswings keeping your hips back against the wall. If your hips leave the wall early, that is early extension.' },
    { label: 'Belt-line video', detail: 'Down the line, watch your belt line — it should not move toward the ball during the downswing.' },
  ],
  videoUploadTips: ['Film true down the line, behind the hands, at hip height.', 'Keep the lower body in frame for the whole swing.'],
  drills: [
    { name: 'Wall-Behind Hips', goal: 'Hold the hinge in transition', how: 'Hips lightly against a wall, make slow swings keeping contact with the wall well into the downswing.', feel: 'Hips staying back and rotating, not thrusting', reps: '10 slow swings', equipment: 'Wall or chair', level: 'intermediate' },
    { name: 'Rotate-Don’t-Thrust', goal: 'Replace a vertical push with rotation', how: 'Make swings focusing on turning your lead hip back and around behind you instead of pushing your belt toward the ball.', feel: 'Lead hip clearing behind you', reps: '10 swings', equipment: 'None', level: 'advanced' },
  ],
  practicePlan: ['Day 1–3: Wall-Behind Hips slow swings.', 'Day 4–6: Rotate-Don’t-Thrust into soft shots.', 'Day 7: Retest down the line and compare hip movement and contact.'],
  progressionLadder: ['Feel hips staying back on slow swings', 'Keep posture at half speed', 'Hold it at full speed', 'Own it in play'],
  relatedFaultIds: ['early_extension', 'hip_stall'],
  canonicalForFaultIds: ['early_extension'],
  relatedDataPointSlugs: ['posture', 'rotation', 'contact-quality'],
  relatedConceptSlugs: ['weight-distribution', 'swing-plane'],
  relatedCoachStyleIds: ['technical', 'data'],
  drillFamilies: ['posture retention', 'rotation & separation'],
  seoTitle: 'Early Extension: Causes, How to Detect It, and Fix Drills',
  seoDescription: 'What early extension is, why it wrecks contact and direction, how SwingVantage detects it from video, and drills to hold your posture and rotate instead.',
  faqs: [
    { question: 'What causes early extension?', answer: 'Usually pushing off the ground vertically instead of rotating, limited hip mobility, or starting the downswing with the upper body. The hips thrust toward the ball and the torso stands up too soon.' },
    { question: 'How do I fix early extension fast?', answer: 'The wall drill is the quickest feedback: keep your hips touching a wall behind you well into the downswing so you learn to rotate instead of thrust. Pair it with posture and rotation work.' },
  ],
  lastReviewedAt: REVIEWED,
  sourceNotes: 'Maps to fault ontology id early_extension. Synthesized from public concepts; no coach-specific material.',
};

const OVER_THE_TOP: LearnEntry = {
  id: 'over-the-top',
  slug: 'over-the-top',
  kind: 'data-point',
  title: 'Over the Top',
  category: 'motion',
  sports: ['golf', 'baseball', 'softball_slow', 'softball_fast', 'tennis'],
  difficultyLevels: ['beginner', 'intermediate', 'advanced'],
  status: 'published',
  descriptionShort: 'A steep, out-to-in downswing where the club moves out and over the ideal path — the number-one cause of the pull-slice.',
  explanationBeginner: 'Coming "over the top" means that as you start down, the club and arms throw outward, then cut across the ball from outside to in. It is the most common reason for a slice and for pulls.',
  explanationAdvanced: 'Over the top is an out-to-in downswing plane created when the upper body and arms dominate the start of the downswing instead of the lower body. Combined with an open face it yields the pull-slice; with a square/closed face it yields pulls. Fixing the cause (sequence) beats fixing the symptom (path) directly.',
  whyItMatters: 'It is the single most common ball-striking fault and the engine of the slice that frustrates most amateurs. Understanding it turns a mystery slice into a clear, fixable picture.',
  detectionLogic: 'From a down-the-line view, SwingVantage estimates the downswing path of the hands and club and flags an out-and-over move in transition. This maps to the fault ontology entry "over_the_top." Camera angle strongly affects accuracy.',
  evidenceBasis: 'estimated',
  confidenceExplanation: 'Path is read from a single 2D angle, so it is estimated and very camera-dependent. Film true down the line for a trustworthy read.',
  goodPattern: 'A transition where pressure shifts to the lead side and the club drops slightly to the inside before delivering from in-to-square-to-in.',
  poorPatterns: ['Club and arms throwing out and over at the start of the downswing', 'Shoulders spinning open early', 'A steep, cutting path across the ball', 'Divots pointing well left of target (right-handed)'],
  commonCauses: ['Upper body starting the downswing', 'A grip/face issue the body re-routes around', 'No pressure shift to the lead side', 'Trying to add speed from the top with the shoulders'],
  symptoms: ['You feel the club "throw out" away from you', 'You sense you are swinging across the ball', 'Steep, glancing contact'],
  ballFlightOrResult: ['Pull-slices and pulls', 'Steep, weak, glancing strikes', 'A ball that starts left and curves right (right-handed)'],
  selfChecks: [
    { label: 'Headcover gate', detail: 'Place a soft object just outside the ball. If your swing hits it on the way down, you are coming over the top.' },
    { label: 'Start line', detail: 'If your shots consistently start left of target (right-handed), an over-the-top path is a likely cause.' },
  ],
  videoUploadTips: ['Film true down the line — this read is the most camera-sensitive of all.', 'Keep the full club arc in frame.'],
  drills: [
    { name: 'Headcover Gate', goal: 'Train an inside approach', how: 'Put a headcover just outside the ball; swing to miss it. An over-the-top path strikes it, an inside path clears it.', feel: 'Approaching from inside the object', reps: '10 swings', equipment: 'Headcover / soft object', level: 'beginner' },
    { name: 'Pump-and-Drop', goal: 'Feel the club shallow', how: 'From the top, pump the downswing halfway three times feeling the club drop behind your hands, then swing through.', feel: 'Club falling into a slot', reps: '3 pumps + 1 swing × 8', equipment: 'None', level: 'intermediate' },
    { name: 'Lower-Body-First', goal: 'Fix the cause (sequence)', how: 'Start the downswing by shifting pressure to the lead foot before the arms move; exaggerate at half speed.', feel: 'Lower body leads, arms follow', reps: '10 slow swings', equipment: 'None', level: 'advanced' },
  ],
  practicePlan: ['Day 1–2: Headcover Gate at half speed.', 'Day 3–5: Pump-and-Drop to feel the shallow move.', 'Day 6: Lower-Body-First into normal swings.', 'Day 7: Retest down the line and compare path and start line.'],
  progressionLadder: ['See your path on slow swings', 'Clear the gate at half speed', 'Keep the inside approach at speed', 'Own a repeatable shape in play'],
  relatedFaultIds: ['over_the_top', 'poor_hip_shoulder_separation'],
  canonicalForFaultIds: ['over_the_top'],
  relatedDataPointSlugs: ['rotation', 'casting', 'face-control'],
  relatedConceptSlugs: ['swing-plane', 'weight-distribution'],
  relatedCoachStyleIds: ['technical', 'feel'],
  drillFamilies: ['plane & path', 'transition & sequencing'],
  seoTitle: 'Over the Top: Why You Slice and the Drills That Fix It',
  seoDescription: 'What "over the top" means, how it causes the pull-slice, how SwingVantage detects it from down-the-line video, and the best drills to fix the cause.',
  faqs: [
    { question: 'Does over the top cause a slice?', answer: 'Usually, yes. An out-to-in over-the-top path with an open face produces the classic pull-slice — the ball starts left and curves right for a right-handed player.' },
    { question: 'What is the fastest fix for over the top?', answer: 'Train an inside approach with a gate drill for instant feedback, but fix the cause by starting the downswing with a pressure shift to the lead side rather than the arms and shoulders.' },
  ],
  lastReviewedAt: REVIEWED,
  sourceNotes: 'Maps to fault ontology id over_the_top. Synthesized from public concepts; no coach-specific material.',
};

const CASTING: LearnEntry = {
  id: 'casting',
  slug: 'casting',
  kind: 'data-point',
  title: 'Casting (Early Release)',
  category: 'release',
  sports: ['golf', 'baseball', 'softball_slow', 'softball_fast'],
  difficultyLevels: ['intermediate', 'advanced'],
  status: 'published',
  descriptionShort: 'Releasing the wrist angles too early in the downswing — throwing away stored speed before impact.',
  explanationBeginner: 'Casting is when you "throw" the club or barrel out early with your hands, like casting a fishing rod. You lose the lever that creates speed, so you arrive at the ball with less power and often weak, scoopy contact.',
  explanationAdvanced: 'Casting is the premature loss of wrist lag in the downswing — the trail wrist un-cocks early, increasing the radius too soon. It bleeds clubhead speed, adds dynamic loft, and moves the low point behind the ball, producing weak, high, thin, or fat contact.',
  whyItMatters: 'Lag is free speed and compression. Casting throws both away, so it is a major cause of distance loss and weak contact even in otherwise good-looking swings.',
  detectionLogic: 'SwingVantage estimates when the wrist angle releases relative to impact from video and flags an early release. This maps to the fault ontology entry "casting_hands." It is a visual estimate.',
  evidenceBasis: 'estimated',
  confidenceExplanation: 'Wrist timing is read from 2D frames, so it is estimated. A clear down-the-line clip at a steady frame rate helps.',
  goodPattern: 'Wrist angles maintained into the downswing and released through impact, delivering the head with lag and a forward low point.',
  poorPatterns: ['Wrists un-cocking early in the downswing', 'A "scoop" through impact', 'The trail elbow straightening too soon', 'Adding loft and losing speed at the ball'],
  commonCauses: ['Trying to "lift" or help the ball up', 'Hitting from the top with the hands', 'Grip pressure too tight', 'No feel for retaining wrist angle'],
  symptoms: ['Weak, high contact with little compression', 'Effort feels high, speed feels low', 'A scooping sensation at the ball'],
  ballFlightOrResult: ['High, weak shots and a loss of distance', 'Thin or fat contact from a low point behind the ball'],
  selfChecks: [
    { label: 'Pump-down feel', detail: 'From the top, pump halfway down and feel whether your wrists stay cocked or release immediately. Early release is casting.' },
    { label: 'Swoosh test', detail: 'Hold a club upside down and swing; the loudest swoosh should be past impact, not before it. A swoosh before the ball signals casting.' },
  ],
  videoUploadTips: ['Film down the line at a steady frame rate.', 'Keep hands and club in frame through impact.'],
  drills: [
    { name: 'Swoosh-Past-Impact', goal: 'Move peak speed to impact', how: 'Swing a club upside down trying to make the loudest swoosh just after the bottom, not at the top.', feel: 'Speed arriving late, past the ball', reps: '10 swishes', equipment: 'A club', level: 'intermediate' },
    { name: 'Pump-and-Hold', goal: 'Retain wrist angle', how: 'Pump the downswing to waist height keeping the wrist angle, then release through. Exaggerate the retained angle.', feel: 'Lag held into the delivery', reps: '10 reps', equipment: 'None', level: 'advanced' },
  ],
  practicePlan: ['Day 1–3: Swoosh-Past-Impact reps.', 'Day 4–6: Pump-and-Hold into soft shots.', 'Day 7: Retest and compare compression and distance.'],
  progressionLadder: ['Feel retained lag on slow reps', 'Keep it at half speed', 'Keep it at full speed', 'Trust it in play'],
  relatedFaultIds: ['casting_hands'],
  canonicalForFaultIds: ['casting_hands'],
  relatedDataPointSlugs: ['contact-quality', 'over-the-top', 'face-control'],
  relatedConceptSlugs: ['grip', 'weight-distribution'],
  relatedCoachStyleIds: ['feel', 'technical'],
  drillFamilies: ['release & face control', 'tempo & sequencing'],
  seoTitle: 'Casting in the Golf Swing: Early Release Causes and Fix Drills',
  seoDescription: 'What casting (early release) is, why it costs you speed and compression, how SwingVantage detects it, and drills to retain lag for better contact.',
  faqs: [
    { question: 'What is casting in a golf swing?', answer: 'Casting is releasing your wrist angles too early in the downswing — throwing the club out with the hands like casting a fishing rod. It wastes stored speed and usually causes weak, high, or scoopy contact.' },
    { question: 'How do I stop casting?', answer: 'Train the feeling of speed arriving past impact (the swoosh drill) and retaining wrist angle into the delivery (pump-and-hold). Lighter grip pressure and trusting loft instead of lifting also help.' },
  ],
  lastReviewedAt: REVIEWED,
  sourceNotes: 'Maps to fault ontology id casting_hands. Synthesized from public concepts; no coach-specific material.',
};

const CONTACT_QUALITY: LearnEntry = {
  id: 'contact-quality',
  slug: 'contact-quality',
  kind: 'data-point',
  title: 'Contact Quality',
  category: 'contact',
  sports: ALL_BALL_SPORTS,
  difficultyLevels: ['beginner', 'intermediate', 'advanced'],
  status: 'published',
  descriptionShort: 'How flush you strike it — where the ball meets the face/barrel and how clean the low point is.',
  explanationBeginner: 'Contact quality is how cleanly you hit the ball: centered on the face or barrel, with the low point in the right place. Clean contact is what makes the ball jump off the face with control.',
  explanationAdvanced: 'Contact quality combines strike location (toward the center of percussion) and low-point control (bottom of the arc relative to the ball). Off-center strikes lose speed and twist the face; a low point behind the ball causes fat/thin and scoopy compression.',
  whyItMatters: 'Centered contact is the biggest single factor in distance and consistency — bigger than swing speed. Most distance and accuracy gains come from cleaning up the strike, not swinging harder.',
  detectionLogic: 'SwingVantage infers contact quality from ball flight, strike feedback, and (where available) launch-monitor smash/efficiency numbers, plus the swing patterns that move the low point. Pure video reads are estimated; data-backed reads are stronger.',
  evidenceBasis: 'ai_inferred',
  confidenceExplanation: 'Without strike tape or a launch monitor, contact is inferred from flight and motion, so it is labeled inferred. Adding launch-monitor data raises confidence to measured for several of these numbers.',
  goodPattern: 'Centered strike with the low point at or just ahead of the ball, producing consistent, compressed contact.',
  poorPatterns: ['Toe/heel strikes that lose speed and twist the face', 'Low point behind the ball (fat/thin/scoopy)', 'Wildly varying strike location shot to shot'],
  commonCauses: ['Pressure hanging back (low point behind ball)', 'Casting / early release', 'Lost posture / early extension', 'Setup distance or ball position off'],
  symptoms: ['Stingy, vibrating hits (off-center)', 'Heavy or thin contact', 'Distance that varies a lot for the same effort'],
  ballFlightOrResult: ['Off-center: knuckle-balls, distance loss, curve', 'Behind the ball: fat, thin, weak high shots', 'Centered: a solid, predictable flight'],
  selfChecks: [
    { label: 'Strike tape / foot spray', detail: 'Light foot spray or impact tape on the face shows exactly where you are striking it — the cheapest contact feedback there is.' },
    { label: 'Towel-behind test', detail: 'Place a towel a few inches behind the ball; if you hit the towel first, your low point is too far back.' },
  ],
  videoUploadTips: ['Add launch-monitor data if you have it for a much stronger contact read.', 'Otherwise film down the line to judge low point.'],
  drills: [
    { name: 'Towel Gate Low Point', goal: 'Move the low point forward', how: 'Place a towel a few inches behind the ball and hit shots without touching the towel, brushing the ground after the ball.', feel: 'Ball first, then ground', reps: '3 sets of 8', equipment: 'Towel', level: 'beginner' },
    { name: 'Center-Strike Spray', goal: 'Centre the strike', how: 'Apply foot spray to the face and adjust setup/ball position until strikes cluster in the center.', feel: 'A solid, quiet strike', reps: '15 shots', equipment: 'Foot spray', level: 'intermediate' },
  ],
  practicePlan: ['Day 1–3: Towel Gate Low Point.', 'Day 4–6: Center-Strike Spray feedback.', 'Day 7: Retest and compare strike consistency / smash factor.'],
  progressionLadder: ['Find center with feedback', 'Repeat it on slow swings', 'Keep it at speed', 'Trust it in play'],
  relatedFaultIds: ['early_extension', 'casting_hands', 'lunging_forward'],
  relatedDataPointSlugs: ['casting', 'early-extension'],
  relatedConceptSlugs: ['weight-distribution', 'grip'],
  relatedCoachStyleIds: ['data', 'feel'],
  drillFamilies: ['low-point control', 'strike quality'],
  seoTitle: 'Contact Quality: Centered Strike, Low Point, and Drills',
  seoDescription: 'Why centered contact beats swing speed for distance and consistency, how SwingVantage infers strike and low point, and drills to flush it more often.',
  faqs: [
    { question: 'What matters more, swing speed or contact?', answer: 'For most players, centered contact matters more. An off-center strike loses speed and twists the face, so cleaning up the strike usually adds more distance and consistency than swinging harder.' },
    { question: 'How can I check my contact at home?', answer: 'Light foot spray or impact tape on the face shows your strike location, and a towel placed behind the ball reveals whether your low point is too far back.' },
  ],
  lastReviewedAt: REVIEWED,
};

const FACE_CONTROL: LearnEntry = {
  id: 'face-control',
  slug: 'face-control',
  kind: 'data-point',
  title: 'Face Control',
  category: 'release',
  sports: ['golf', 'tennis', 'pickleball', 'padel'],
  difficultyLevels: ['intermediate', 'advanced'],
  status: 'published',
  descriptionShort: 'How square the face is at impact relative to your path — the biggest driver of start direction and curve.',
  explanationBeginner: 'Face control is how well you manage where the face points at contact. The face direction is the main reason the ball starts where it does and curves the way it does. Controlling it is the key to hitting your target.',
  explanationAdvanced: 'At impact, face angle is the dominant factor in start line (roughly 75–85% of start direction for a golf ball), and face-to-path determines curve. Face control is set primarily by grip and release timing, which is why it is the through-line connecting grip, casting, and over-the-top.',
  whyItMatters: 'Because the face controls start line and curve, face control is the most direct lever on accuracy. Stabilize the face and your dispersion shrinks dramatically.',
  detectionLogic: 'SwingVantage infers face control from start line and curve, release pattern in video, and any launch-monitor face/path numbers. Flight-based inference is labeled accordingly; launch data is stronger.',
  evidenceBasis: 'ai_inferred',
  confidenceExplanation: 'Inferred from ball flight and release look unless launch-monitor face numbers are present, in which case it becomes measured.',
  goodPattern: 'A face that returns to a repeatable relationship with the path, producing a consistent one-way shot shape.',
  poorPatterns: ['Face wildly open or shut at impact', 'A timing-based hand flip to square the face', 'Two-way miss from an unpredictable face'],
  commonCauses: ['Grip too strong/weak for the player', 'Casting or flipping (release timing)', 'Path issues the hands fight (e.g., over the top)', 'Grip pressure too tight to release'],
  symptoms: ['The face feels out of your hands', 'You must time a flip to square it', 'Both a hook and a slice in the same session'],
  ballFlightOrResult: ['Open face: slices/pushes and weak high contact', 'Shut face: hooks/pulls', 'Controlled face: a reliable one-way shape'],
  selfChecks: [
    { label: 'Start-line read', detail: 'Note where shots start: well right means an open face at impact, well left means a closed face (right-handed).' },
    { label: 'Grip first', detail: 'Because grip sets the face, re-check your grip reference before blaming the swing for face problems.' },
  ],
  videoUploadTips: ['Add launch-monitor data if available for face/path numbers.', 'Film face-on and down the line to see release.'],
  drills: [
    { name: 'Gate Start-Line', goal: 'Control start direction', how: 'Set two tees a club-head apart a few feet in front of the ball; hit shots that start through the gate.', feel: 'Face matching the gate at impact', reps: '15 shots', equipment: 'Two tees', level: 'intermediate' },
    { name: 'Logo-Down Release', goal: 'Train a repeatable release', how: 'On slow swings, feel the trail forearm rotate over the lead through impact so the face squares without a last-instant flip.', feel: 'Smooth forearm rotation, no flip', reps: '10 swings', equipment: 'None', level: 'advanced' },
  ],
  practicePlan: ['Day 1–2: Re-check grip + Gate Start-Line.', 'Day 3–5: Logo-Down Release on slow swings.', 'Day 6: Normal swings reading start line.', 'Day 7: Retest and compare start line and curve.'],
  progressionLadder: ['Re-check grip reference', 'Control start line through a gate', 'Repeat the release at speed', 'Own a one-way shape in play'],
  relatedFaultIds: ['casting_hands', 'over_the_top'],
  relatedDataPointSlugs: ['casting', 'over-the-top'],
  relatedConceptSlugs: ['grip', 'swing-plane'],
  relatedCoachStyleIds: ['data', 'technical'],
  drillFamilies: ['release & face control', 'plane & path'],
  seoTitle: 'Face Control: Start Line, Curve, and Drills to Square the Face',
  seoDescription: 'How clubface control drives start line and curve, why grip and release set it, how SwingVantage infers it, and drills to square the face reliably.',
  faqs: [
    { question: 'What controls where the ball starts?', answer: 'For a golf ball, the face angle at impact controls roughly 75–85% of the start direction; path and face-to-path then determine the curve. That is why face control is the biggest lever on accuracy.' },
    { question: 'Why is my face open at impact?', answer: 'Most often a grip that is too weak for you, or a release that flips or casts. Because grip sets the face, re-check your grip reference first, then train a repeatable release.' },
  ],
  lastReviewedAt: REVIEWED,
};

export const DATA_POINT_ENTRIES: LearnEntry[] = [
  TEMPO,
  POSTURE,
  ROTATION,
  EARLY_EXTENSION,
  OVER_THE_TOP,
  CASTING,
  CONTACT_QUALITY,
  FACE_CONTROL,
];
